Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2018-09, with the labels that each got.

#51 Fix small typos in release-versioning.md
  docs/release-versioning.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#50 add NSGs verification e2e test
  tests/e2e/network/network_security_group.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#55 Fix some typos in doc dependency-management.md
  docs/dependency-management.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#54 update disk issues
  docs/azuredisk-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#56 Update TOC for docs
  README.md
  docs/azuredisk-issues.md
  docs/azurefile-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#58 Add documentation for cross resource group nodes
  README.md
  docs/using-cross-resource-group-nodes.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#57 Add documentation for Azure availability zones
  README.md
  docs/using-availability-zones.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#59 Add timestamp in testing resource group name
  tests/k8s-azure/k8s-azure
Labels: approved, cncf-cla: yes, lgtm, size/XS

#61 Fix typo: dependecies -> dependencies
  docs/dependency-management.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
