Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2018-04, with the labels that each got.

#3 Update package import path
  Dockerfile
  cloud-controller-manager/main.go
  glide.yaml
  scripts/pkg-config.sh
  scripts/update-dependencies.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#9 Add cloud provider config doc
  README.md
  docs/cloud-provider-config.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#13 Typo fix: kuberentes->kubernetes
  docs/e2e-tests.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
