Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2018-08, with the labels that each got.

#44 adding code-of-conduct.md file
  code-of-conduct.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#46 Update OWNERS / SECURITY_CONTACTS
  OWNERS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, sig/azure, size/XS

#47 add azure internal and subnet service annotation test
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/ip_utils.go
  tests/e2e/utils/ip_utils_test.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/node_utils.go
  tests/e2e/utils/pod_utils.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
