Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2018-07, with the labels that each got.

#30 add azuredisk-issues.md & azurefile-issues.md
  docs/azuredisk-issues.md
  docs/azurefile-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#35 Update azuredisk-issues.md
  docs/azuredisk-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#34 Add `SECURITY_CONTACTS`
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, sig/azure, size/S

#36 Fix test-check
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#37 Add docs for LB idle timeouts
  docs/development-loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#41 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#39 e2e lint check
  Makefile
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/log.go
  tests/e2e/utils/node_utils.go
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#43 update docs
  docs/azuredisk-issues.md
  docs/azurefile-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S
