Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2018-05, with the labels that each got.

#14 Typo fix: skiped->skipped
  tests/k8s-azure/k8s-azure
Labels: approved, cncf-cla: yes, lgtm, size/XS

#17 Update doc for cloud-controller-manager
  docs/cloud-controller-manager.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#16 Add e2e in makefile
  Makefile
  scripts/image-tag.sh
  tests/k8s-azure/Dockerfile
  tests/k8s-azure/init.sh
  tests/k8s-azure/k8s-azure
  tests/k8s-azure/skip.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#18 Update test acs-engine version
  tests/k8s-azure/Dockerfile
  tests/k8s-azure/manifest/linux.json
  tests/k8s-azure/skip.txt
Labels: approved, cncf-cla: yes, lgtm, size/S

#21 Fix typo
  docs/cloud-provider-config.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
