Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2019-09, with the labels that each got.

#223 Upgrade golang to 1.12.9
  Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#225 Update documentation
  README.md
  docs/azure-permissions.md
  docs/persistentvolumes/azuredisk/README.md
  docs/persistentvolumes/azuredisk/issues.md
  docs/persistentvolumes/azurefile/README.md
  docs/persistentvolumes/azurefile/issues.md
  docs/services/README.md
  docs/using-availability-zones.md
  examples/cloud-controller-manager.yaml
  examples/in-tree/kube-apiserver.yaml
  examples/in-tree/kube-controller-manager.yaml
  examples/in-tree/kube-scheduler.yaml
  examples/in-tree/kubelet.manifest
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/kube-apiserver.yaml
  examples/out-of-tree/kube-controller-manager.yaml
  examples/out-of-tree/kube-scheduler.yaml
  examples/out-of-tree/kubelet.manifest
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XL

#226 Enable ServiceLoadBalancerFinalizer for slow e2e test cases.
  tests/k8s-azure/manifest/e2e-slow.json
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, ok-to-test, release-note-none, size/M

#229 Enable ccm feature flag ServiceLoadBalancerFinalizer.
  tests/k8s-azure/manifest/e2e-slow.json
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#230 Enlarge the vm sku for slow and slow-vmss tests.
  tests/k8s-azure/manifest/e2e-slow.json
  tests/k8s-azure/manifest/linux-vmss-multi-zones.json
  tests/k8s-azure/manifest/linux-vmss.json
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S

#232 Update docs for Kubernetes go modules upgrade
  docs/dependency-management.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#234 Update hack/deploy-cluster.sh and corresponding doc.
  docs/e2e-tests.md
  hack/deploy-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#236 Rebase base image of cloud controller manager and cloud node manager to distroless.
  Dockerfile
  Dockerfile.node
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#237 Update examples of v0.3.0
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#243 Use the subnetPrefix when determining the available private IP
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S

#242 Add e2e case for credential provider.
  tests/e2e/BUILD.bazel
  tests/e2e/auth/BUILD.bazel
  tests/e2e/auth/cred.go
  tests/e2e/e2e_test.go
  tests/e2e/utils/BUILD.bazel
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/container_registry_utils.go
  tests/e2e/utils/pod_utils.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/BUILD.bazel
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/classicadministrators.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/globaladministrator.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/permissions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/provideroperationsmetadata.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/roleassignments.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/roledefinitions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry/BUILD.bazel
  vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry/registries.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry/replications.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry/runs.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry/tasks.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry/webhooks.go
Labels: approved, cncf-cla: yes, kind/testing, lgtm, release-note-none, size/XXL
