Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2019-02, with the labels that each got.

#89 update azuredisk issues
  docs/azuredisk-issues.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#90 Update documentation on multiple scale set support
  docs/cloud-provider-config.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#92 Update tests and docs to use aks-engine
  Makefile
  docs/azuredisk-issues.md
  docs/azurefile-issues.md
  docs/cloud-controller-manager.md
  docs/cloud-provider-config.md
  docs/component-versioning.md
  docs/e2e-tests.md
  tests/k8s-azure/Dockerfile
  tests/k8s-azure/k8s-azure
  tests/k8s-azure/manifest/linux-kcm.json
  tests/k8s-azure/manifest/linux.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#95 Bump aks-engine to v0.31.1 to support private ACR
  Makefile
  docs/e2e-tests.md
  tests/k8s-azure/Dockerfile
  tests/k8s-azure/k8s-azure
  tests/k8s-azure/manifest/linux-kcm.json
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#96 add Issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/support.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#97 Update README
  README.md
  docs/azure-loadbalancer.md
  docs/cloud-controller-manager.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M
