Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2019-05, with the labels that each got.

#156 Cleanup deploy script
  hack/deploy-cluster.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/L

#157 Add support of testing standard LB and fix e2e docs
  docs/e2e-tests-azure.md
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/utils/azure_auth.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/M

#160 Add availabiity zone feature to deploy-cluster.sh
  examples/az.json
  hack/deploy-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M
