Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2019-06, with the labels that each got.

#161 Removing translation dir
  translations/en_US/LC_MESSAGES/acsengine.mo
  translations/en_US/LC_MESSAGES/acsengine.po
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#163 Update documents for new options
  docs/azure-loadbalancer.md
  docs/cloud-provider-config.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#165 Config the minimal permissions for azure-cloud-provider-secret-getter
  docs/cloud-provider-config.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#167 Update Kubernetes version to v1.15.0
  Makefile
  examples/aks-engine.json
  examples/az.json
  go.mod
  go.sum
  tests/k8s-azure/manifest/linux-autoscaler.json
  tests/k8s-azure/manifest/linux-kcm.json
  tests/k8s-azure/manifest/linux-vmss.json
  tests/k8s-azure/manifest/linux.json
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, release-note, size/M

#168 docs/cloud-provider-config.md: fix typo
  docs/cloud-provider-config.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/XS

#170 Fix link of Azure cloud provider since it has been moved to staging
  docs/cloud-controller-manager.md
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none, size/XS
