Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2019-04, with the labels that each got.

#136 add ensure load balancer e2e test
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#141 Create deploy-cluster.sh
  hack/deploy-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#143 Updated Makefile with deploy target
  .gitignore
  Makefile
  examples/aks-engine.json
  hack/deploy-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#144 Create linux-vmss.json
  tests/k8s-azure/manifest/linux-vmss.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#146 Add deploy plugin for AzureFile and Azure Disk CSI
  hack/deploy-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#147 Updating e2e documentation-ongoing updation
  docs/e2e-tests.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#148 Fix KUBECONFIG setup in hack/deploy-cluster.sh
  hack/deploy-cluster.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#149 Remove the perl script
  Makefile
  hack/deploy-cluster.sh
  hack/test_k8s_e2e.sh
  tests/k8s-azure/Dockerfile
  tests/k8s-azure/init.sh
  tests/k8s-azure/k8s-azure
  translations/en_US/LC_MESSAGES/acsengine.mo
  translations/en_US/LC_MESSAGES/acsengine.po
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XL

#152 Describe configuration required for Azure Stack
  docs/cloud-provider-config.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note, size/M
