Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2019-10, with the labels that each got.

#246 removed links that led to 404s and updated documentation
  docs/cloud-controller-manager.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note, size/S

#248 Upload control-plane and node component logs to artifacts folder
  hack/log-dump/log-dump-daemonset.yaml
  hack/log-dump/log-dump.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#239 fix:"pacakge" should be package
  docs/dependency-management.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#241 fix:about
  docs/release-versioning.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#240 fix :junit should be JUnit
  docs/e2e-tests-azure.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#238 fix: loadbalancer should be capital
  docs/cloud-provider-config.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#250 Add test case to test zone label on nodes.
  tests/e2e/network/node.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/utils.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, kind/testing, lgtm, release-note-none, size/L

#251 Limit --concurrent-service-syncs to 1
  cmd/cloud-controller-manager/app/options/options.go
  cmd/cloud-controller-manager/app/options/options_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#252 Convert json-based logs to slightly more human-readable logs
  hack/log-dump/log-dump.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#254 Check if the log file can be parsed by jq
  hack/log-dump/log-dump.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#253 Add test cases for node resources.
  tests/e2e/network/node.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_interface_utils.go
  tests/e2e/utils/node_utils.go
  tests/e2e/utils/route_table_utils.go
  tests/e2e/utils/utils.go
  tests/e2e/utils/vm_utils.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, kind/testing, lgtm, release-note-none, size/XL
