Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2020-01, with the labels that each got.

#277 Check if TAG exists before IMAGE_TAG is assigned.
  Makefile
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, ok-to-test, release-note-none, size/XS

#279 Add a config for `./hack/pkg-config.sh`.
  Makefile
  hack/pkg-config.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, ok-to-test, release-note-none, size/S

#280 Update README.md with correct image registry
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/XS

#282 Fixes flakiness in cloud-provider-azure-autoscaling job
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#284 Add virtual kubelet manifest and update k8s version to 1.17.
  tests/k8s-azure/manifest/autoscaler-virtual-kubelet.json
  tests/k8s-azure/manifest/e2e-slow.json
  tests/k8s-azure/manifest/linux-autoscaler.json
  tests/k8s-azure/manifest/linux-kcm.json
  tests/k8s-azure/manifest/linux-vmss-multi-zones.json
  tests/k8s-azure/manifest/linux-vmss-serial.json
  tests/k8s-azure/manifest/linux-vmss.json
  tests/k8s-azure/manifest/linux.json
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/L

#285 Update k8s.io/legacy-cloud-providers to v0.17.2
  go.mod
  go.sum
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go
  vendor/k8s.io/legacy-cloud-providers/azure/auth/azure_auth.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_standard.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_vmss.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_standard.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_vmss.go
  vendor/k8s.io/legacy-cloud-providers/azure/azure_vmss_cache.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/L
