Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2020-09, with the labels that each got.

#383 Add v0.6.0 release note.
  site/content/en/blog/releases/v0.6.0.md
Labels: approved, cncf-cla: yes, do-not-merge/hold, kind/documentation, release-note, size/S

#386 Fix edit url in doc website.
  site/config.toml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#389 docs: update documentation in how to deploy azure disk/file csi drivers
  site/content/en/install/azure-ccm.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#382 add healthz/readyz probes in the example manifest and bump the image to the lastest available
  examples/out-of-tree/cloud-controller-manager.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/S

#390 Fix an error log
  tests/e2e/autoscaling/autoscaler.go
Labels: approved, cncf-cla: yes, kind/bug, release-note-none, size/XS

#391 Add e2e log
  tests/e2e/network/node.go
  tests/e2e/utils/utils.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#392 chore: set the cloud-provider flag to external
  examples/out-of-tree/kube-apiserver.yaml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, release-note-none, size/XS

#394 Fix readyz probe
  cmd/cloud-controller-manager/app/controllermanager.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#395 Cherry pick of #394 to release 0.5: fix readyz probe
  cmd/cloud-controller-manager/app/controllermanager.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#396 Cherry pick of #394 to release 0.6: fix readyz probe
  cmd/cloud-controller-manager/app/controllermanager.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#397 Ignore in-cluster config when --master or --kubeconfig is set explicitly
  cmd/cloud-controller-manager/app/options/options.go
  cmd/cloud-node-manager/app/options/options.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#398 Cherry pick of #397 to release 0.5: Ignore in-cluster config when --master or --kubeconfig is set explicitly
  cmd/cloud-controller-manager/app/options/options.go
  cmd/cloud-node-manager/app/options/options.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#399 Cherry pick of #397 to release 0.6: Ignore in-cluster config when --master or --kubeconfig is set explicitly
  cmd/cloud-controller-manager/app/options/options.go
  cmd/cloud-node-manager/app/options/options.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS
