Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2020-10, with the labels that each got.

#406 cleanup: remove the duplicated options loadBalancerResourceGroup and loadBalancerName
  site/content/en/install/configs.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#404 Add e2e test cases for multiple services sharing one ip address
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#411 Add docs on cache TTLs for various resources
  site/content/en/install/configs.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#409 Add e2e test cases for shared IP and node label
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#412 Add docs for shared IP and node exclusion
  site/content/en/topics/loadbalancer.md
  site/content/en/topics/shared-ip.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#413 Use vmas for masters
  tests/k8s-azure/manifest/linux-vmss-multi-zones.json
Labels: approved, cncf-cla: yes, kind/failing-test, release-note-none, size/XS

#408 Add design doc for the feature "support multiple slbs in one cluster"
  site/content/en/development/design-docs/_index.md
  site/content/en/development/design-docs/multiple-slb.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M
