Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2020-04, with the labels that each got.

#327 Fix wrong init url.
  tests/kubemark/extensions/config-kubemark-master/v1/template.json
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#328 Update images for out-of-tree examples
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
  examples/out-of-tree/kube-apiserver.yaml
  examples/out-of-tree/kube-controller-manager.yaml
  examples/out-of-tree/kube-scheduler.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#329 Use a service account for CCM
  docs/cloud-controller-manager.md
  examples/out-of-tree/cloud-controller-manager.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L

#332 Enabled ENABLE_GIT_COMMAND in dockerfile
  Dockerfile
  cloud-node-manager.Dockerfile
  go.mod
  go.sum
  hack/verify-golint.sh
  pkg/nodemanager/nodemanager.go
  tests/e2e/utils/azure_auth.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M
