Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2020-12, with the labels that each got.

#429 Add docs for service annotation service.beta.kubernetes.io/azure-load-balancer-enable-high-availability-ports
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#432 increase the timeout in e2e test
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, kind/flake, lgtm, release-note-none, size/XS

#434 Use k8s.io/legacy-cloud-providers instead of k/k/staging/src/legacy-cloud-providers in go.mod
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#436 Move the kubernetes to require in go.mod
  go.mod
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#435 fix: Fix ListByResourceGroup in azure diskClient mock
  pkg/azureclients/diskclient/mockdiskclient/interface.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#439 Fix nil VMSS name when setting service to auto mode
  hack/test-unit.sh
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#441 add feature gate ExecProbeTimeout=true
  tests/k8s-azure/manifest/kubernetes.json
Labels: approved, cncf-cla: yes, release-note-none, size/XS

#440 add lb limits in docs
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#442 Update manifests for some failing e2e tests
  tests/k8s-azure/manifest/autoscaler-virtual-kubelet.json
  tests/k8s-azure/manifest/e2e-slow.json
  tests/k8s-azure/manifest/linux-autoscaler-multi-nodepool.json
  tests/k8s-azure/manifest/linux-autoscaler.json
  tests/k8s-azure/manifest/linux-ipv6.json
  tests/k8s-azure/manifest/linux-kcm.json
  tests/k8s-azure/manifest/linux-vmss-basic-lb.json
  tests/k8s-azure/manifest/linux-vmss-multi-zones.json
  tests/k8s-azure/manifest/linux-vmss-serial.json
  tests/k8s-azure/manifest/linux-vmss.json
  tests/k8s-azure/manifest/linux.json
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/M

#443 Use network.Interface.VirtualMachine.ID to get the VM
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#446 Download golangci-lint directly
  .golangci.yml
  go.mod
  go.sum
  hack/verify-golint.sh
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#447 Get node before tag it
  tests/e2e/network/ensureloadbalancer.go
Labels: approved, cncf-cla: yes, kind/flake, release-note-none, size/XS

#445 Support change the LB selection mode on the existing services
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmss.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#448 Skip standalone VM when reconciling LoadBalancer
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_standard.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/XS

#450 Refine the doc of the mode selection annotation
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#452 Add a node pool in basic lb test
  tests/k8s-azure/manifest/linux-vmss-basic-lb.json
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#457 Explicitly set mod=mod in go list
  hack/update-dependencies.sh
Labels: approved, cncf-cla: yes, kind/bug, release-note-none, size/XS

#455 Skip the exclude LB test on multi node pool cluster
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/M

#453 use batch operation for azure disk attach/detach
  pkg/mockvmsets/BUILD.bazel
  pkg/mockvmsets/doc.go
  pkg/provider/azure.go
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_common_test.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_standard_test.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmss_test.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_managedDiskController_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_routes_test.go
  pkg/provider/azure_vmsets.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XL
