Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2020-06, with the labels that each got.

#336 Switch to a stable version of aks-engine.
  tests/kubemark/build-kubemark.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#335 docs: add current default rate limit config
  docs/cloud-provider-config.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#339 Use old version of azure cli.
  tests/kubemark/build-kubemark.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#340 Update version matrix
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#341 Refine cloud provider docs
  docs/cloud-provider-config.md
  docs/services/README.md
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none, size/M

#343 Update docs for cross resource group nodes
  docs/using-cross-resource-group-nodes.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S
