Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2020-07, with the labels that each got.

#345 Enable running ccm e2e test in a job
  .dockerignore
  Makefile
  e2e.Dockerfile
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/job/clusterrolebinding.yaml
  tests/e2e/job/run.sh
  tests/e2e/job/test_in_cluster_job.yaml
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#346 Fix image format
  Makefile
  tests/e2e/job/test_in_cluster_job.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#347 fix: fix error from log-dumping script
  hack/log-dump/log-dump-daemonset.yaml
  hack/log-dump/log-dump.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#349 fix: fix autoscaling job
  hack/log-dump/log-dump.sh
  tests/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#350 Partly decouple k/k
  cmd/cloud-controller-manager/app/BUILD.bazel
  cmd/cloud-controller-manager/app/core.go
  cmd/cloud-controller-manager/app/options/BUILD.bazel
  cmd/cloud-controller-manager/app/options/options.go
  cmd/cloud-node-manager/app/BUILD.bazel
  cmd/cloud-node-manager/app/options/BUILD.bazel
  cmd/cloud-node-manager/app/options/options.go
  go.mod
  pkg/nodemanager/BUILD.bazel
  pkg/nodemanager/nodemanager.go
  pkg/nodemanager/nodemanager_test.go
  pkg/util/controller/BUILD.bazel
  pkg/util/controller/client_builder.go
  pkg/util/controller/testutil/BUILD.bazel
  pkg/util/controller/testutil/test_utils.go
  tests/e2e/BUILD.bazel
  vendor/k8s.io/kubernetes/pkg/controller/testutil/BUILD
  vendor/k8s.io/kubernetes/pkg/util/node/BUILD
  vendor/k8s.io/kubernetes/pkg/util/node/node.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XXL

#353 Increase VMSS polling operation interval
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#357 Add index page for building github pages
  docs/index.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#356 Update cloudbuild.yaml
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#355 Update E2E test related docs and script
  docs/dependency-management.md
  docs/e2e-tests.md
  examples/aks-engine.json
  hack/deploy-cluster.sh
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#360 Ensure github actions only run on master branch
  .github/workflows/gh-pages.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#359 Add repo SECURITY.md
  SECURITY.md
Labels: cncf-cla: yes, ok-to-test, release-note-none, size/S

#361 Prettify the index page of the doc web site
  site/content/en/_index.html
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/XS

#362 Fix cloud build for image building
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS
