Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2021-03, with the labels that each got.

#526 Update image references to v0.7.2
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
  site/content/en/blog/releases/v0.7.2.md
  site/content/en/install/configs.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#529 fix: account name logging in azure file
  pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#534 chore: remove get file in CreateFileShare
  pkg/azureclients/fileclient/azure_fileclient.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#514 Add assumption docs for provisioning tools
  site/content/en/topics/assumptions.md
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none, size/S

#523 enable gocyclo linter
  .golangci.yml
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XXL

#536 Ensure only LoadBalancer rule is created when HA mode is enabled
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#528 Route updates wait a while for new routes to take effect
  cmd/cloud-node-manager/app/config/config.go
  cmd/cloud-node-manager/app/nodemanager.go
  cmd/cloud-node-manager/app/options/options.go
  pkg/nodemanager/nodemanager.go
  pkg/provider/azure.go
  pkg/provider/azure_routes.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#524 enable gosec linter
  .golangci.yml
  cmd/cloud-controller-manager/app/options/options.go
  cmd/cloud-controller-manager/app/testing/testserver.go
  cmd/cloud-node-manager/app/options/options.go
  pkg/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/nodeipam/ipam/range_allocator.go
  pkg/nodeipam/node_ipam_controller_test.go
  pkg/provider/azure_config.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_test.go
  pkg/retry/azure_retry.go
  pkg/util/controller/testutil/test_utils.go
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/container_registry_utils.go
  tests/e2e/utils/network_interface_utils.go
  tests/e2e/utils/node_utils.go
  tests/e2e/utils/route_table_utils.go
  tests/e2e/utils/vm_utils.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#540 Fix node public IP fetching from instance metadata service
  pkg/provider/azure.go
  pkg/provider/azure_instance_metadata.go
  pkg/provider/azure_instances_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#542 add service account issuer flag
  tests/k8s-azure/manifest/kubernetes.json
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#543 add get/set azure file ServiceProperties client
  pkg/azureclients/fileclient/azure_fileclient.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#544 feat: refine ServiceProperties interface
  pkg/azureclients/fileclient/azure_fileclient.go
  pkg/azureclients/fileclient/interface.go
  pkg/azureclients/fileclient/mockfileclient/interface.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#545 feat: add disable RetentionPolicy parameter
  pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#546 fix: remove ExecProbeTimeout kubelet feature gate
  tests/k8s-azure/manifest/kubernetes.json
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#539 feat: implement cloud cidr allocator for VMSS
  cmd/cloud-controller-manager/app/core.go
  cmd/cloud-controller-manager/app/options/nodeipamcontroller.go
  cmd/cloud-controller-manager/app/options/options.go
  cmd/cloud-controller-manager/app/options/options_test.go
  pkg/auth/azure_auth.go
  pkg/auth/azure_auth_test.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/consts/consts.go
  pkg/consts/doc.go
  pkg/metrics/azure_metrics.go
  pkg/nodeipam/ipam/cidr_allocator.go
  pkg/nodeipam/ipam/cidrset/cidr_set.go
  pkg/nodeipam/ipam/cidrset/cidr_set_test.go
  pkg/nodeipam/ipam/cloud_cidr_allocator.go
  pkg/nodeipam/ipam/cloud_cidr_allocator_test.go
  pkg/nodeipam/ipam/range_allocator.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_blobDiskController.go
  pkg/provider/azure_blobDiskController_test.go
  pkg/provider/azure_config.go
  pkg/provider/azure_config_test.go
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_common_test.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmss_test.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_instance_metadata.go
  pkg/provider/azure_instances.go
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_managedDiskController_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_ratelimit.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_storage.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
  pkg/provider/azure_zones.go
  pkg/retry/azure_error.go
  pkg/util/controller/testutil/test_utils.go
  pkg/version/verflag/verflag.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#537 Fix availability set cache in vmss cache
  Makefile
  pkg/provider/azure.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#551 Fix: ignore not a VMSS error for VMAS nodes in reconcileBackendPools
  pkg/provider/azure_vmss.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#554 chore: move consts in azure_vmss.go to consts.go
  pkg/consts/consts.go
  pkg/nodeipam/ipam/cloud_cidr_allocator_test.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#556 fix flaky test
  tests/e2e/network/standard_lb.go
Labels: approved, cncf-cla: yes, kind/failing-test, release-note, size/XS

#553 doc: add doc for out-of-tree node ipam controller
  site/content/en/development/design-docs/ipam.md
  site/content/en/topics/ipam.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/L

#560 fix: add logs for flaky tests
  tests/e2e/network/standard_lb.go
Labels: approved, cncf-cla: yes, kind/flake, release-note, size/S

#561 fix: convert backend pool id to lower case before using it
  tests/e2e/network/standard_lb.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#564 fix: check disk state before attach disk
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_common_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#558 feat: support system tag
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_routes.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#555 feat: implement cloud allocator for vmas
  pkg/azureclients/vmasclient/azure_vmasclient.go
  pkg/azureclients/vmasclient/azure_vmasclient_test.go
  pkg/azureclients/vmasclient/doc.go
  pkg/azureclients/vmasclient/interface.go
  pkg/azureclients/vmasclient/mockvmasclient/doc.go
  pkg/azureclients/vmasclient/mockvmasclient/interface.go
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_ratelimit.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#565 fix: retry removing lb backend pool reference from vmss and deleting lb if the previous lb deletion was blocked by LoadBalancerInUseByVirtualMachineScaleSet
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/retry/azure_error.go
  pkg/retry/azure_error_test.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/L

#567 chore: enrich docs for tags
  site/content/en/install/configs.md
  site/content/en/topics/tagging-resources.md
Labels: cncf-cla: yes, release-note

#568 Fix: avoid panic when RouteTablePropertiesFormat is nil
  pkg/provider/azure_routes.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#566 api-model: remove --service-account-issuer
  tests/k8s-azure/manifest/kubernetes.json
  tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json
  tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#552 enable unconvert linter
  .golangci.yml
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_routes.go
  pkg/retry/azure_retry_test.go
  tests/e2e/autoscaling/autoscaler.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#571 chore: add issuer url in apiserver config for dual-stack and ipv6
  tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json
  tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json
  tests/k8s-azure/manifest/linux-ipv6.json
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#572 chore: add verbose logs for load balancer rules/probes
  pkg/provider/azure_loadbalancer.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#574 fix: not delete existing pip when service is deleted
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/ensureloadbalancer.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XL

#576 chore: use aks-ubuntu-16.04 distro for dual-stack and ipv6
  tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json
  tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json
  tests/k8s-azure/manifest/linux-ipv6.json
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S

#577 Use extended location for managed disks
  pkg/azureclients/azure_client_config.go
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/diskclient/interface.go
  pkg/provider/azure.go
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_managedDiskController_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L
