Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2021-06, with the labels that each got.

#649 serviceOwnsFrontendIP shouldn't report error when the public IP doesn't match
  pkg/provider/azure_standard.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note, size/XS

#645 cherry-pick of #664 to 1.0 release
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, release-note, size/M

#647 chore: update docs for service tags NSG
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/XS

#643 Update Azure Go SDK to v55.0.0
  go.mod
  go.sum
  pkg/azureclients/storageaccountclient/azure_storageaccountclient_test.go
  vendor/github.com/Azure/azure-sdk-for-go/services/authorization/mgmt/2015-07-01/authorization/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-12-01/compute/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/containerregistry/mgmt/2019-05-01/containerregistry/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-04-01/containerservice/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-04-01/containerservice/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2020-04-01/containerservice/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2020-08-01/network/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2020-08-01/network/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2020-08-01/network/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-02-01/storage/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-02-01/storage/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-02-01/storage/models.go
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/github.com/Azure/go-autorest/autorest/adal/go.mod
  vendor/github.com/Azure/go-autorest/autorest/adal/go.sum
  vendor/github.com/Azure/go-autorest/autorest/adal/sender.go
  vendor/github.com/Azure/go-autorest/autorest/adal/token.go
  vendor/github.com/Azure/go-autorest/autorest/adal/token_1.13.go
  vendor/github.com/Azure/go-autorest/autorest/adal/token_legacy.go
  vendor/github.com/Azure/go-autorest/autorest/client.go
  vendor/github.com/Azure/go-autorest/autorest/go.mod
  vendor/github.com/Azure/go-autorest/autorest/go.sum
  vendor/github.com/Azure/go-autorest/autorest/to/go.mod
  vendor/github.com/Azure/go-autorest/autorest/to/go.sum
  vendor/github.com/Azure/go-autorest/autorest/to/go_mod_tidy_hack.go
  vendor/github.com/Azure/go-autorest/logger/logger.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XXL

#644 cherry-pick of #645 to release-1.0
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, kind/feature, release-note, size/M

#650 test: add windows dual-stack manifest
  tests/k8s-azure/manifest/windows-dual-stack.json
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#646 fix: wait for the success of the initial run of syncRegionZonesMap
  cmd/cloud-controller-manager/app/controllermanager.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/provider/azure.go
  pkg/provider/azure_config.go
  pkg/provider/azure_config_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_zones.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/L

#656 chore: add more buckets for operation metrics
  pkg/metrics/azure_metrics.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XS

#663 Add coverage report and status badge
  .github/workflows/test-coverage.yml
  README.md
Labels: cncf-cla: yes, release-note-none, size/S

#664 Cherry pick #656 to release-1.0
  pkg/metrics/azure_metrics.go
Labels: approved, cncf-cla: yes, kind/cleanup, release-note, size/XS

#665 cherry-pick #646 and #661 to release-1.0
  cmd/cloud-controller-manager/app/controllermanager.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/provider/azure.go
  pkg/provider/azure_config.go
  pkg/provider/azure_config_test.go
  pkg/provider/azure_routes.go
  pkg/provider/azure_routes_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_zones.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#666 chore: update the master count in testing
  tests/k8s-azure/manifest/autoscaler-virtual-kubelet.json
  tests/k8s-azure/manifest/e2e-slow.json
  tests/k8s-azure/manifest/kubernetes.json
  tests/k8s-azure/manifest/linux-autoscaler-multi-nodepool.json
  tests/k8s-azure/manifest/linux-autoscaler.json
  tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json
  tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json
  tests/k8s-azure/manifest/linux-ipv6.json
  tests/k8s-azure/manifest/linux-kcm.json
  tests/k8s-azure/manifest/linux-vmss-basic-lb.json
  tests/k8s-azure/manifest/linux-vmss-multi-zones.json
  tests/k8s-azure/manifest/linux-vmss-serial.json
  tests/k8s-azure/manifest/linux-vmss.json
  tests/k8s-azure/manifest/windows-dual-stack.json
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/M

#662 chore: set default config secret name and namespace
  cmd/cloud-controller-manager/app/options/dynamic.go
  cmd/cloud-controller-manager/app/options/options_test.go
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_config_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#667 chore: add resource param into GetServicePrincipalToken
  pkg/auth/azure_auth.go
  pkg/auth/azure_auth_test.go
  pkg/provider/azure.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#668 docs: add securityGroupResourceGroup cloud config value
  site/content/en/install/configs.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, needs-ok-to-test, release-note, size/XS

#670 chore: add more tests for auth
  pkg/auth/azure_auth_test.go
  pkg/auth/testdata/test.pfx
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/M

#671 chore: only reconciling routes in cloud controller manager
  pkg/provider/azure.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/S

#669 fix: make tags case-insensitive for both keys and values
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#672 cherry-pick of #669: make tags case-insensitive for both keys and values
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#673 doc: release v1.0.1
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
  site/content/en/blog/releases/v1.0.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/M

#675 chore: upgrade TLS1.0 to TLS1.2 in account creation
  pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XS

#678 fix: remove GetDisk operation in AttachDisk
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_common_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#652 Enable creation of private endpoint for storage account
  pkg/azureclients/privatednsclient/azure_privatednsclient.go
  pkg/azureclients/privatednsclient/interface.go
  pkg/azureclients/privatednsclient/mockprivatednsclient/doc.go
  pkg/azureclients/privatednsclient/mockprivatednsclient/interface.go
  pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
  pkg/azureclients/privatednszonegroupclient/interface.go
  pkg/azureclients/privatednszonegroupclient/mockprivatednszonegroupclient/doc.go
  pkg/azureclients/privatednszonegroupclient/mockprivatednszonegroupclient/interface.go
  pkg/azureclients/privateendpointclient/azure_privateendpointclient.go
  pkg/azureclients/privateendpointclient/interface.go
  pkg/azureclients/privateendpointclient/mockprivateendpointclient/doc.go
  pkg/azureclients/privateendpointclient/mockprivateendpointclient/interface.go
  pkg/azureclients/storageaccountclient/interface.go
  pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient.go
  pkg/azureclients/virtualnetworklinksclient/interface.go
  pkg/azureclients/virtualnetworklinksclient/mockvirtualnetworklinksclient/doc.go
  pkg/azureclients/virtualnetworklinksclient/mockvirtualnetworklinksclient/interface.go
  pkg/provider/azure.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/enums.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/privatezones.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/recordsets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/privatedns/mgmt/2018-09-01/privatedns/virtualnetworklinks.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#679 fix: return empty VMAS name if using standalone VM
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#680 fix: leave the probe path empty for TCP probes
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#681 Cherry pick of #680: fix: leave the probe path empty for TCP probes
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#683 fix: avoid nil-pointer panic when checking the frontend IP configuration
  pkg/provider/azure_standard.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#682 Cherry pick of #680: fix: leave the probe path empty for TCP probes
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#685 chore: increase log level for creating private endpoint in account
  pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#686 chore: only put pip if it is necessary
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/L
