Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2021-04, with the labels that each got.

#578 feat: support sharing the primary slb with multiple vmSets
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_utils.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#579 Update compute API version to 2020-12-01
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/diskclient/interface.go
  pkg/azureclients/snapshotclient/interface.go
  pkg/azureclients/vmasclient/interface.go
  pkg/azureclients/vmclient/interface.go
  pkg/azureclients/vmsizeclient/interface.go
  pkg/azureclients/vmssclient/interface.go
  pkg/azureclients/vmssvmclient/interface.go
  pkg/azureclients/zoneclient/azure_zoneclient.go
  pkg/azureclients/zoneclient/interface.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/S

#580 feat: add ARM node provider
  cmd/cloud-node-manager/app/config/config.go
  cmd/cloud-node-manager/app/nodemanager.go
  cmd/cloud-node-manager/app/options/options.go
  pkg/node/BUILD.bazel
  pkg/node/nodearm.go
  pkg/node/nodeproviderfactory.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L

#583 Avoid caching the VMSS instances whose network profile is nil
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#584 Ensure service deleted when the Azure resource group has been deleted
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#586 Disable blobfuse-flexvolume addon in tests
  tests/k8s-azure/manifest/linux-autoscaler-multi-nodepool.json
  tests/k8s-azure/manifest/linux-autoscaler.json
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/L

#587 chore: dump CSI Drivers logs on master
  hack/log-dump/log-dump.sh
Labels: approved, cncf-cla: yes, kind/flake, lgtm, release-note-none, size/XS

#592 feat: add update vm interface
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_common_test.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_standard_test.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmss_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_vmsets.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#588 fix: support sharing the primary slb when there are both external and internal load balancers in the cluster
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/node_utils.go
  tests/e2e/utils/pod_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XL

#590 chore: enrich docs
  site/content/en/topics/assumptions.md
  site/content/en/topics/images/pip-labels.png
  site/content/en/topics/multiple-slb.md
  site/content/en/topics/shared-ip.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/M

#594 doc: release v0.7.3
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
  site/content/en/blog/releases/v0.7.3.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/M

#593 fix: potential race condition in detach disk
  pkg/provider/azure_controller_common.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#595 fix: arm node provider Windows initialization
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/nodemanager/mock/mock_node_provider.go
  pkg/nodemanager/nodemanager.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/S

#598 chore: update and cleanup docs
  examples/out-of-tree/cloud-node-manager.yaml
  site/content/en/development/custom-images.md
  site/content/en/install/azure-ccm.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#597 fix: call the counterpart function of availabilitySet when the instance is not a vmss vm
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#600 doc: release v0.7.4
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
  site/content/en/blog/releases/v0.7.3.md
  site/content/en/blog/releases/v0.7.4.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/M

#602 Fix hack/update-dependencies.sh and tidy go modules
  go.mod
  go.sum
  hack/update-dependencies.sh
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XXL

#608 chore: only logs rate limiting configurations when rate limit is enabled
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/azureclients/deploymentclient/azure_deploymentclient.go
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/routeclient/azure_routeclient.go
  pkg/azureclients/routetableclient/azure_routetableclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/subnetclient/azure_subnetclient.go
  pkg/azureclients/vmasclient/azure_vmasclient.go
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmsizeclient/azure_vmsizeclient.go
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/L

#609 chore: only logs rate limiting configurations when rate limit is enabled
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/azureclients/deploymentclient/azure_deploymentclient.go
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/routeclient/azure_routeclient.go
  pkg/azureclients/routetableclient/azure_routetableclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/subnetclient/azure_subnetclient.go
  pkg/azureclients/vmasclient/azure_vmasclient.go
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmsizeclient/azure_vmsizeclient.go
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
Labels: approved, cncf-cla: yes, release-note, size/L

#606 feat: Enable creation of storage accounts that support large file shares
  pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#610 Edge zone managed disk bug fix.
  pkg/provider/azure.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#611 Edge zone managed disk bug fix.
  pkg/provider/azure.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#599 Rename E2E environment variables for consistency across projects
  hack/deploy-cluster.sh
  site/content/en/development/e2e/e2e-tests-azure.md
  site/content/en/development/e2e/e2e-tests.md
  tests/e2e/job/test_in_cluster_job.yaml
  tests/e2e/utils/azure_auth.go
  tests/kubemark/build-kubemark.sh
Labels: cncf-cla: yes, lgtm, release-note, size/M
