Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2021-12, with the labels that each got.

#920 images: use k8s-staging-test-infra/gcb-docker-gcloud
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none

#921 build: cross-compile under linux/amd64 platform
  cloud-node-manager.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#929 fix: detach disk should return error when throttled
  pkg/consts/consts.go
  pkg/provider/azure_controller_common.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#918 feat: support attaching node private IP to the load balancer backendpools
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm

#925 add a rest client config for configuring polling and retries on ARM clients
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/azure_client_config.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/azureclients/deploymentclient/azure_deploymentclient.go
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/routeclient/azure_routeclient.go
  pkg/azureclients/routetableclient/azure_routetableclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/subnetclient/azure_subnetclient.go
  pkg/azureclients/vmasclient/azure_vmasclient.go
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmsizeclient/azure_vmsizeclient.go
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/zoneclient/azure_zoneclient.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#934 chore: bump k8s.io/cloud-provider to v0.23.0
  cmd/cloud-controller-manager/app/controllermanager.go
  cmd/cloud-controller-manager/app/core.go
  go.mod
  go.sum
  pkg/nodemanager/nodemanager.go
  vendor/k8s.io/cloud-provider/config/v1alpha1/zz_generated.conversion.go
  vendor/k8s.io/cloud-provider/config/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/cloud-provider/config/v1alpha1/zz_generated.defaults.go
  vendor/k8s.io/cloud-provider/config/zz_generated.deepcopy.go
  vendor/k8s.io/cloud-provider/controllers/node/node_controller.go
  vendor/k8s.io/cloud-provider/controllers/nodelifecycle/node_lifecycle_controller.go
  vendor/k8s.io/cloud-provider/controllers/route/route_controller.go
  vendor/k8s.io/cloud-provider/controllers/service/config/v1alpha1/zz_generated.conversion.go
  vendor/k8s.io/cloud-provider/controllers/service/config/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/cloud-provider/controllers/service/config/zz_generated.deepcopy.go
  vendor/k8s.io/cloud-provider/controllers/service/controller.go
  vendor/k8s.io/cloud-provider/options/options.go
  vendor/k8s.io/component-helpers/LICENSE
  vendor/k8s.io/component-helpers/node/util/cidr.go
  vendor/k8s.io/component-helpers/node/util/conditions.go
  vendor/k8s.io/component-helpers/node/util/status.go
  vendor/modules.txt
Labels: release-note, approved, cncf-cla: yes, lgtm, size/XL, kind/cleanup

#926 build: support building ccm for multi-platform
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test

#930 feat: add private link service client
  go.mod
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go
  pkg/azureclients/privatelinkserviceclient/doc.go
  pkg/azureclients/privatelinkserviceclient/interface.go
  pkg/azureclients/privatelinkserviceclient/mockprivatelinkserviceclient/doc.go
  pkg/azureclients/privatelinkserviceclient/mockprivatelinkserviceclient/interface.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note-none, ok-to-test

#938 cherry-pick from #921 to release-1.0 (build: cross-compile under linux/amd64 platform)
  cloud-node-manager.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#936 build: build and push ccm images for all platforms by default
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test

#937 cherry-pick from #921 to release-1.1 (build: cross-compile under linux/amd64 platform)
  cloud-node-manager.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#941 doc: add doc for loadBalancerBackendPoolConfigurationType and unite LB related docs
  site/content/en/install/configs.md
  site/content/en/topics/custom-health-probe.md
  site/content/en/topics/loadbalancer.md
  site/content/en/topics/multiple-slb.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/L, release-note-none

#940 doc: release v1.23.0
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
  site/content/en/blog/releases/v1.23.0.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/L, release-note-none

#945 fix: always include the primary load balancer when listing managed load balancers
  pkg/provider/azure_backoff.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none

#947 fix: always include the primary load balancer when listing managed load balancers
  pkg/provider/azure_backoff.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none

#946 fix: always include the primary load balancer when listing managed load balancers
  pkg/provider/azure_backoff.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none

#950 Add numOfProbe and probeInterval in health probe configuration
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#944 chore: simplify reconcileSharedLoadBalancer
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_vmss.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#953 feat: support sending sync requests concurrently in batches when putting vmss vm
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
  pkg/azureclients/vmssvmclient/interface.go
  pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go
  pkg/provider/azure.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#954 feat: add docs for probeinterval and numofprobe
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none, ok-to-test

#955 chore: add vnetRG, vnetName, subnetName in account settings
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_storageaccount.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup
