Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2021-11, with the labels that each got.

#889 feat: add disk online resize support
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_managedDiskController_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XS

#890 fix: create private endpoint failure on Government cloud
  pkg/azureclients/privatednsclient/azure_privatednsclient.go
  pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
  pkg/azureclients/privateendpointclient/azure_privateendpointclient.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#891 fix: remove outdated ipv4 route when the corresponding node is deleted
  pkg/provider/azure_routes.go
  pkg/provider/azure_routes_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#893 kubemark: replace deprecated --log-file parameter
  tests/kubemark/templates/hollow-node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test

#892 feat: support json style tags
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_routes.go
  pkg/provider/azure_utils.go
  site/content/en/install/configs.md
  site/content/en/topics/tagging-resources.md
  tests/e2e/network/service_annotations.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#896 feat: support json style tags
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_routes.go
  pkg/provider/azure_utils.go
  site/content/en/install/configs.md
  site/content/en/topics/tagging-resources.md
  tests/e2e/network/service_annotations.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#895 feat: support json style tags
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_routes.go
  pkg/provider/azure_utils.go
  site/content/en/install/configs.md
  site/content/en/topics/tagging-resources.md
  tests/e2e/network/service_annotations.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#898 chore: enable mixed protocol service feature gates in e2e templates
  tests/k8s-azure/manifest/linux-vmss-basic-lb.json
  tests/k8s-azure/manifest/linux-vmss.json
  tests/k8s-azure/manifest/linux.json
Labels: release-note, cncf-cla: yes, size/XS, kind/cleanup

#899 fix: panic due to nil pointer
  pkg/provider/azure_instances.go
  pkg/provider/azure_standard.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#897 chore: add mixed protocol service e2e test
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/standard_lb.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup

#905 cherry-pick of #841: fix test failures on capz clusters
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm

#909 cleanup: remove blob disk controller
  go.mod
  go.sum
  pkg/provider/azure.go
  pkg/provider/azure_blobDiskController.go
  pkg/provider/azure_blobDiskController_test.go
  pkg/provider/azure_controller_common.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/README.md
  vendor/github.com/Azure/azure-sdk-for-go/storage/appendblob.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/authorization.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/blob.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/blobsasuri.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/blobserviceclient.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/blockblob.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/client.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/commonsasuri.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/container.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/copyblob.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/directory.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/entity.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/file.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/fileserviceclient.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/leaseblob.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/message.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/odata.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/pageblob.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/queue.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/queuesasuri.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/queueserviceclient.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/share.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/storagepolicy.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/storageservice.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/table.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/table_batch.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/tableserviceclient.go
  vendor/github.com/Azure/azure-sdk-for-go/storage/util.go
  vendor/github.com/gofrs/uuid/.gitignore
  vendor/github.com/gofrs/uuid/.travis.yml
  vendor/github.com/gofrs/uuid/LICENSE
  vendor/github.com/gofrs/uuid/README.md
  vendor/github.com/gofrs/uuid/codec.go
  vendor/github.com/gofrs/uuid/fuzz.go
  vendor/github.com/gofrs/uuid/generator.go
  vendor/github.com/gofrs/uuid/sql.go
  vendor/github.com/gofrs/uuid/uuid.go
  vendor/github.com/rubiojr/go-vhd/LICENSE
  vendor/github.com/rubiojr/go-vhd/vhd/util.go
  vendor/github.com/rubiojr/go-vhd/vhd/vhd.go
  vendor/modules.txt
Labels: size/XXL, release-note, approved, cncf-cla: yes, lgtm, kind/cleanup

#911 cleanup: remove blob disk operations
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_common_test.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_standard_test.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmss_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#912 doc: release v0.7.10, v1.0.7 and v1.1.3
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
  site/content/en/blog/releases/v0.7.10.md
  site/content/en/blog/releases/v1.0.7.md
  site/content/en/blog/releases/v1.1.3.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/L, release-note-none

#913 chore: add warning logs for ARM request body on failures
  pkg/azureclients/armclient/azure_armclient.go
  pkg/provider/azure_backoff.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup
