Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2021-05, with the labels that each got.

#607 Fix e2e tests to work with CAPZ
  pkg/consts/consts.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmss.go
  tests/e2e/e2e_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/node_utils.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#613 feat: support reloading cloud controller manager from secret dynamically
  cmd/cloud-controller-manager/app/config/config.go
  cmd/cloud-controller-manager/app/controllermanager.go
  cmd/cloud-controller-manager/app/dynamic/watch_secret.go
  cmd/cloud-controller-manager/app/options/dynamic.go
  cmd/cloud-controller-manager/app/options/options.go
  cmd/cloud-controller-manager/app/options/options_test.go
  cmd/cloud-controller-manager/app/testing/testserver.go
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_config.go
  pkg/provider/azure_config_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XL

#615 fix: avoid nil-pointer panic when checking the frontend IP configuration
  pkg/provider/azure_standard.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#616 fix: not tagging static public IP
  pkg/provider/azure_loadbalancer.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#617 doc: release v1.0.0
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
  site/content/en/blog/releases/v1.0.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/M

#614 docs: add docs for ccm dynamic reloading
  site/content/en/install/configs.md
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#620 Add CreateOrUpdateBackendPools() interface for LoadBalancer client
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient_test.go
  pkg/azureclients/loadbalancerclient/interface.go
  pkg/azureclients/loadbalancerclient/mockloadbalancerclient/interface.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#621 fix: reduce crp throttling in attach disk scenario
  pkg/provider/azure_controller_common.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#622 fix: dangling volume issue
  pkg/provider/azure_controller_common.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#623 fix: delete non existing disk issue
  pkg/provider/azure_managedDiskController.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#629 fix: no sleep when GetDisk is throttled
  pkg/provider/azure_managedDiskController.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#625 Remove azure disable-tcp-reset annotations
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#630 Do not set cached Sku when updating VMSS and VMSS instances
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#631 Do not set cached Sku when updating VMSS and VMSS instances
  hack/deploy-cluster.sh
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  site/content/en/development/e2e/e2e-tests-azure.md
  site/content/en/development/e2e/e2e-tests.md
  tests/e2e/job/test_in_cluster_job.yaml
  tests/e2e/utils/azure_auth.go
  tests/kubemark/build-kubemark.sh
Labels: approved, cncf-cla: yes, release-note, size/M

#633 feat: add NFSv3 account creation support
  pkg/provider/azure_storage_test.go
  pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#632 chore: only get vmset when it's needed
  pkg/provider/azure_controller_common.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#627 chore: add e2e test for byo public IP
  site/content/en/topics/tagging-resources.md
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/L

#637 fix: remove --service-account-issuer from api model
  tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json
  tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json
  tests/k8s-azure/manifest/linux-ipv6.json
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS
