Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2021-01, with the labels that each got.

#458 Release Cloud Provider Azure v0.7.0
  README.md
  site/content/en/blog/releases/v0.7.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#459 Change the expression of the mode selection annotation in multiple SLB doc
  site/content/en/topics/multiple-slb.md
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none

#456 feat: Add LogicalSectorSize support for UltraSSD
  pkg/azureclients/diskclient/interface.go
  pkg/provider/azure_managedDiskController.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#460 feat: add CreateAccount option in EnsureStorageAccount
  pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/S

#464 chore: add logs in ARM GET and PUT
  pkg/azureclients/armclient/azure_armclient.go
Labels: approved, cncf-cla: yes, kind/cleanup, release-note, size/S

#465 Cleanup subnet in frontend IP configs
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XL

#484 Skip the always failed test case caused by underlying SLB issue
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S

#468 feat: interface client changes for Azure Stack Hub support
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
  pkg/azureclients/interfaceclient/interface.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#483 feat: Support etag when putting network interface
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#466 Implement cloudprovider.InstancesV2 interface
  pkg/provider/azure.go
  pkg/provider/azure_instances.go
  pkg/provider/azure_instances_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#486 output rerr to log rather than previous err from GET
  pkg/provider/azure_vmss.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#479 feat: vmss client changes for Azure Stack Hub support
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssclient/azure_vmssclient_test.go
  pkg/azureclients/vmssclient/interface.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#480 feat: vmss vm client changes for Azure Stack Hub support
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
  pkg/azureclients/vmssvmclient/interface.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#477 feat: vm client changes for Azure Stack Hub support
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmclient/azure_vmclient_test.go
  pkg/azureclients/vmclient/interface.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/M

#467 feat: disk client changes for Azure Stack Hub support
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/diskclient/azure_diskclient_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/S

#482 Aggregate errors when putting vmss
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#487 feat: Add service annotation `ServiceAnnotationDenyAllExpectSourceRanges`
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#478 feat: vm size client changes for Azure Stack Hub support
  pkg/azureclients/vmsizeclient/azure_vmsizeclient.go
  pkg/azureclients/vmsizeclient/azure_vmsizeclient_test.go
  pkg/azureclients/vmsizeclient/interface.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#476 feat: subnet client changes for Azure Stack Hub support
  pkg/azureclients/subnetclient/azure_subnetclient.go
  pkg/azureclients/subnetclient/azure_subnetclient_test.go
  pkg/azureclients/subnetclient/interface.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#488 fix: Ignore the default load balancer ranges when adding the deny rule
  pkg/provider/azure_loadbalancer.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/XS

#490 feat: skip account matching with special tags
  pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#492 doc: add doc for the service annotation `service.beta.kubernetes.io/azure-deny-all-except-load-balancer-source-ranges`
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none

#493 add error detail in a verbose log
  pkg/provider/azure_loadbalancer.go
Labels: approved, cncf-cla: yes, kind/cleanup, release-note, size/XS

#469 feat: load balancerclient changes for Azure Stack Hub support
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient_test.go
  pkg/azureclients/loadbalancerclient/interface.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#475 feat: storage account client test changes for Azure Stack Hub support
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/S

#473 feat: security group client changes for Azure Stack Hub support
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient_test.go
  pkg/azureclients/securitygroupclient/interface.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#471 feat: route client changes for Azure Stack Hub support
  pkg/azureclients/routeclient/azure_routeclient.go
  pkg/azureclients/routeclient/azure_routeclient_test.go
  pkg/azureclients/routeclient/interface.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#472 feat: route table client changes for Azure Stack Hub support
  pkg/azureclients/routetableclient/azure_routetableclient.go
  pkg/azureclients/routetableclient/azure_routetableclient_test.go
  pkg/azureclients/routetableclient/interface.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#474 feat: snapshot client changes for Azure Stack Hub support
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
  pkg/azureclients/snapshotclient/interface.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#470 feat: public ip client changes for Azure Stack Hub support
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/publicipclient/azure_publicipclient_test.go
  pkg/azureclients/publicipclient/interface.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#491 feat: add AddStorageAccountTags func
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient_test.go
  pkg/azureclients/storageaccountclient/interface.go
  pkg/azureclients/storageaccountclient/mockstorageaccountclient/interface.go
  pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#494 Deploy cluster script fix
  hack/deploy-cluster.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/S

#497 chore: add log level in armclient
  pkg/azureclients/armclient/azure_armclient.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/S

#496 feat: add RemoveStorageAccountTag func
  pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, release-note, size/M

#500 Fix package names for a set of files
  pkg/azureclients/azure_client_config.go
  pkg/azureclients/azure_client_config_test.go
  pkg/azureclients/doc.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_blobDiskController.go
  pkg/provider/azure_blobDiskController_test.go
  pkg/provider/azure_config.go
  pkg/provider/azure_config_test.go
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_common_test.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_standard_test.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmss_test.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_file.go
  pkg/provider/azure_instance_metadata.go
  pkg/provider/azure_instances.go
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_managedDiskController_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_ratelimit.go
  pkg/provider/azure_ratelimit_test.go
  pkg/provider/azure_routes.go
  pkg/provider/azure_routes_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_storage.go
  pkg/provider/azure_storage_test.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
  pkg/provider/azure_zones.go
  pkg/provider/azure_zones_test.go
  pkg/provider/doc.go
  pkg/provider/main_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L
