Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2021-09, with the labels that each got.

#786 feat: support creating account if not exists when account name is provided
  pkg/provider/azure_blobDiskController.go
  pkg/provider/azure_blobDiskController_test.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#791 fix: ignore the case when comparing azure tags in service annotation
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#794 fix: consolidate logs for instance not found error
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_wrap.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#795 Automated cherry pick of #794: consolidate logs for instance not found error
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_wrap.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, size/M

#796 Automated cherry pick of #794: consolidate logs for instance not found error
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_wrap.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, size/M

#797 Automated cherry pick of #794: consolidate logs for instance not found error
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/loadbalancerclient/interface.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_wrap.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, size/L

#799 chore: rename tag key for CSI drivers
  pkg/consts/consts.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_storageaccount.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XS

#803 feat: reduce vmss cache refresh in parallel disk attach/detach
  pkg/provider/azure_vmss.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/S

#805 cherry-pick of #718: avoid wrapping RawError twice
  pkg/retry/azure_retry.go
  pkg/retry/azure_retry_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#804 cherry-pick of #718: avoid wrapping RawError twice
  pkg/retry/azure_retry.go
  pkg/retry/azure_retry_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#810 doc: add one comment for node labeling rules
  pkg/provider/azure_standard.go
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#811 Cherry pick of #791 to release 1.0: fix: ignore the case when comparing azure tags in service annotation
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#812 Cherry pick of #791 to release 1.1: fix: ignore the case when comparing azure tags in service annotation
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#815 feat: add prefix 'k8s-azure-' for cloud provider managed tags
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_utils.go
  tests/e2e/network/service_annotations.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#816 fix: skip not found nodes when reconciling LB backend address pools
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#818 cherry-pick of #816: skip not found nodes when reconciling LB backend address pools
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#817 cherry-pick of #816: skip not found nodes when reconciling LB backend address pools
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#819 fix: report an error when route table name is not configured
  pkg/provider/azure_routes_test.go
  pkg/provider/azure_wrap.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup

#821 feat: Adds windows server 2022
  Makefile
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#823 Add Windows Service initialisation support for Cloud Node Manager
  cmd/cloud-node-manager/app/config/config.go
  cmd/cloud-node-manager/app/init_others.go
  cmd/cloud-node-manager/app/init_windows.go
  cmd/cloud-node-manager/app/nodemanager.go
  cmd/cloud-node-manager/app/options/init_others.go
  cmd/cloud-node-manager/app/options/init_windows.go
  cmd/cloud-node-manager/app/options/options.go
  go.mod
  hack/boilerplate/boilerplate.py
  pkg/windows/service/service.go
  vendor/golang.org/x/sys/windows/svc/event.go
  vendor/golang.org/x/sys/windows/svc/go12.c
  vendor/golang.org/x/sys/windows/svc/go12.go
  vendor/golang.org/x/sys/windows/svc/go13.go
  vendor/golang.org/x/sys/windows/svc/security.go
  vendor/golang.org/x/sys/windows/svc/service.go
  vendor/golang.org/x/sys/windows/svc/sys_windows_386.s
  vendor/golang.org/x/sys/windows/svc/sys_windows_amd64.s
  vendor/golang.org/x/sys/windows/svc/sys_windows_arm.s
  vendor/golang.org/x/sys/windows/svc/sys_windows_arm64.s
  vendor/modules.txt
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm
