Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2022-07, with the labels that each got.

#1972 [release-1.23]fix: invalidate vmssVMCache when rg is not found
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none

#1983 Add a testing Azure Pipeline
  .pipelines/azure-pipeline.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#1980 [release-1.1] Add servie annotation to disable lb floating ip
  go.mod
  go.sum
  pkg/consts/consts.go
  pkg/consts/helpers.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/strings/slices/slices.go
  vendor/modules.txt
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#1987 docs: update document for cross resource group nodes
  site/content/en/topics/cross-resource-group-nodes.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#1979 [release-1.24] Add servie annotation to disable lb floating ip
  pkg/consts/consts.go
  pkg/consts/helpers.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#1981 [release-1.0] Add servie annotation to disable lb floating ip
  go.mod
  go.sum
  pkg/consts/consts.go
  pkg/consts/helpers.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/strings/slices/slices.go
  vendor/modules.txt
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#1978 [release-1.23] Add servie annotation to disable lb floating ip
  go.mod
  go.sum
  pkg/consts/consts.go
  pkg/consts/helpers.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  vendor/k8s.io/utils/clock/clock.go
  vendor/k8s.io/utils/clock/testing/fake_clock.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/strings/slices/slices.go
  vendor/modules.txt
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#1984 doc: update load balancer doc
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none, ok-to-test

#1991 fix: Ignore privateIPAllocationMethod when comparing frontend config
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1998 fix: make sure there is no duplicated rules before updating the netwo…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup

#1995 Check lb type before pip-prefix-id test
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none

#1989 Add detailed error reuslt_code in ObserveOperationWithResult func
  go.mod
  pkg/metrics/azure_metrics.go
  pkg/metrics/azure_metrics_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#2009 docs: update cloud provider permissions
  site/content/en/topics/azure-permissions.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#2008 chore: skip slb outbound e2e test for capz clusters
  tests/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, kind/flake

#2023 doc: bump image versions in readme and exapmels
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
Labels: cncf-cla: yes, kind/documentation, release-note-none

#2015 helm: publish 1.24.3 with latest releases
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.24.3.tgz
  helm/repo/index.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#2025 [release 1.1] Add detailed error reuslt_code in ObserveOperationWithR…
  pkg/metrics/azure_metrics.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#2024 [release 1.0] Add detailed error reuslt_code in ObserveOperationWithR…
  pkg/metrics/azure_metrics.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#1985 Update: adjust customized CAPZ templates to solve multiple control-plane issue and more
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test

#2029 fix: decouple the LB from the VMSS before VMSS VMs
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#1996 Add a toggle for AKS Cluster
  hack/test-ccm-e2e.sh
  tests/e2e/auth/cred.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/consts.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#2051 chore: Strictly check LB CreateOrUpdate times during UT
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2053 update e2e-test to support windows
  tests/e2e/auth/cred.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, release-note-none, kind/cleanup, ok-to-test

#2062 Fix azure pipeline variables
  .pipelines/docker-login.yml
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
  .pipelines/run-basic-lb-e2e.yml
Labels: approved, cncf-cla: yes, size/S, release-note-none, kind/testing

#2063 update azp
  .pipelines/docker-login.yml
  .pipelines/run-basic-lb-e2e.yml
Labels: approved, cncf-cla: yes, size/XS, release-note-none, kind/testing

#2064 Fix env var in Azure pipelines
  .pipelines/ccm-image.yml
  .pipelines/cnm-image.yml
  .pipelines/daily-gc.yml
  .pipelines/docker-login.yml
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
  .pipelines/run-basic-lb-e2e.yml
  .pipelines/scripts/run-e2e.sh
Labels: approved, cncf-cla: yes, size/L, release-note-none, kind/testing

#2070 Fix azp gc job
  .pipelines/daily-gc.yml
  .pipelines/scripts/daily-gc.sh
  .pipelines/scripts/run-e2e.sh
Labels: approved, cncf-cla: yes, size/S, release-note-none, kind/testing

#2060 fix: don't set vm entry as nil in cache when vm is in Deleting state to avoid VMSSList throttling
  pkg/provider/azure_vmss_cache.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#2058 VMSS Flex support: Add GetResourceWithQueries function in azure_armclient.go
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test

#2073 Allow external service with floating ip disabled to use PLS
  go.sum
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#2076 Use correct subnet name in reconcileFrontendIPConfigs()
  pkg/provider/azure_loadbalancer.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#2077 [release-1.23] Allow external service with floating ip disabled to use PLS
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#2072 docs: update limitations of PLS
  site/content/en/topics/pls-integration.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#2085 docs: Update pls doc to support ELB+disabling floating ip
  site/content/en/development/design-docs/pls-integration.md
  site/content/en/topics/pls-integration.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, release-note-none

#2079 [release-1.0] Allow external service with floating ip disabled to use PLS
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#2026 fix: update osversion in Makefile manifest-node-manager-image-window
  Makefile
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#2080 Vmss flex support: Add two functions in azure_vmclient.go to support batch querying VMSS Flex VMs and their InstanceView
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmclient/azure_vmclient_test.go
  pkg/azureclients/vmclient/interface.go
  pkg/azureclients/vmclient/mockvmclient/interface.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#2078 [release-1.1] Allow external service with floating ip disabled to use PLS
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#2099 Less mem usage for golangci-lint by less concurrency
  .golangci.yml
  cmd/cloud-controller-manager/app/core.go
  cmd/cloud-controller-manager/app/testing/testserver.go
  hack/verify-golint.sh
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/nodeipam/ipam/doc.go
  pkg/nodemanager/nodemanager.go
  pkg/provider/azure_instances.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_routes.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_wrap.go
  pkg/retry/azure_retry.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2102 [release-1.23] Less mem usage for golangci-lint by less concurrency
  .golangci.yml
  cmd/cloud-controller-manager/app/core.go
  cmd/cloud-controller-manager/app/testing/testserver.go
  hack/verify-golint.sh
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/nodeipam/ipam/doc.go
  pkg/nodemanager/nodemanager.go
  pkg/provider/azure_instances.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_routes.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_wrap.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2086 Fix aks pipeline to test e2e
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
  .pipelines/run-basic-lb-e2e.yml
  .pipelines/scripts/run-e2e.sh
  .pipelines/templates/autoscaling-multipool.json
  .pipelines/templates/autoscaling.json
  hack/test-ccm-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, ok-to-test
