Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2022-04, with the labels that each got.

#1383 Refactor azure_armclient tests
  pkg/azureclients/armclient/azure_armclient_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none

#1395 [release-1.1]fix: fallback to tcp if appprotocol is not supported
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, kind/regression

#1397 [release-0.7]Fix: fallback to tcp if appprotocol is not supported
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, kind/regression

#1394 [release-1.23]fix: fallback to tcp if appprotocol is not supported
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, kind/regression

#1396 [release-1.0]fix: fallback to tcp if appprotocol is not supported
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, kind/regression

#1391 Reduce build time for cloudbuild
  Makefile
  cloudbuild.yaml
  variants.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none

#1398 [release 1.0]Tests: e2e add multiport service test and backport #627
  site/content/en/topics/tagging-resources.md
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/testing

#1402 Rollback pr #1300 Refactor store and use sync.map as data store
  pkg/cache/azure_cache.go
  pkg/provider/azure_vmss_cache.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none

#1401 Add List() to pls client interface
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go
  pkg/azureclients/privatelinkserviceclient/interface.go
  pkg/azureclients/privatelinkserviceclient/mockprivatelinkserviceclient/interface.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#1420 chore: add subsID parameter in storage account client
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient_test.go
  pkg/azureclients/storageaccountclient/interface.go
  pkg/azureclients/storageaccountclient/mockstorageaccountclient/interface.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_managedDiskController_test.go
  pkg/provider/azure_storage_test.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#1426 Docs: health probe works only on out of tree provider
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#1427 [cherrypick][release-1.0] Refactor azure_armclient tests
  pkg/azureclients/armclient/azure_armclient_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none

#1425 [cherrypick][release-1.1] Refactor azure_armclient tests
  pkg/azureclients/armclient/azure_armclient_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none

#1430 [cherrypick][release-0.7] Refactor azure_armclient tests
  pkg/azureclients/armclient/azure_armclient_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none

#1451 [helm] Update helm doc
  helm/cloud-provider-azure/README.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#1456 [helm] Update helm repo
  Makefile
  hack/verify-helm-repo.sh
  helm/cloud-provider-azure/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none

#1450 [release-1.1] Backport Private link service client to release 1.1
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/azure_client_config.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/azureclients/deploymentclient/azure_deploymentclient.go
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go
  pkg/azureclients/privatelinkserviceclient/doc.go
  pkg/azureclients/privatelinkserviceclient/interface.go
  pkg/azureclients/privatelinkserviceclient/mockprivatelinkserviceclient/doc.go
  pkg/azureclients/privatelinkserviceclient/mockprivatelinkserviceclient/interface.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/routeclient/azure_routeclient.go
  pkg/azureclients/routetableclient/azure_routetableclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/subnetclient/azure_subnetclient.go
  pkg/azureclients/vmasclient/azure_vmasclient.go
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmsizeclient/azure_vmsizeclient.go
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/zoneclient/azure_zoneclient.go
Labels: size/XXL, kind/feature, approved, cncf-cla: yes, lgtm, release-note-none

#1452 Fix possibly incorrect last char of frontend PIP config name
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1469 [release-1.0]backport #1084 #1235
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#1489 fix: account tags matching issue in account search
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#1491 Add DeletePEConnection to plsClient
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go
  pkg/azureclients/privatelinkserviceclient/interface.go
  pkg/azureclients/privatelinkserviceclient/mockprivatelinkserviceclient/interface.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#1492 fix: disable match tags by default in account search when creating file share
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#1501 Chores:Update dependencies to trigger dependabot job
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1502 [release-1.23]update deps to trigger dependabot job
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1506 [release-0.7]chores:update dependency to trigger dependabot job
  Dockerfile
  Makefile
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/cloud.google.com/go/compute/metadata/retry.go
  vendor/cloud.google.com/go/compute/metadata/retry_linux.go
  vendor/k8s.io/utils/internal/third_party/forked/golang/LICENSE
  vendor/k8s.io/utils/internal/third_party/forked/golang/PATENTS
  vendor/k8s.io/utils/internal/third_party/forked/golang/net/ip.go
  vendor/k8s.io/utils/internal/third_party/forked/golang/net/parse.go
  vendor/k8s.io/utils/net/ipnet.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/parse.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#1503 [release-1.1]update deps to trigger dependabot job
  Dockerfile
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#1500 Reduce listPIP calls
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#1507 fix(instance-v2): use false<bool> representing ErrInstanceNotFound<errror>
  pkg/provider/azure_instances.go
  pkg/provider/azure_instances_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, ok-to-test

#1509 chore: fail earlier if creating virutal link failed before account creation
  pkg/provider/azure_storageaccount.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/S, kind/cleanup

#1532 chore(helm): publish cloud-provider-azure chart 1.23.10
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.23.10.tgz
  helm/repo/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none

#1551 Reduce listPIP calls
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#1549 test: add e2e test for deletion of VMSS instance
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/e2e_test.go
  tests/e2e/network/node.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/log.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, needs-kind, ok-to-test

#1565 chores: Add kind label for dependency update pr
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#1572 [release-0.7] Add cache for public IP
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_ratelimit_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_test.go
  pkg/provider/azure_wrap.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#1571 [release-1.0] Add cache for public IP
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_ratelimit_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_test.go
  pkg/provider/azure_wrap.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#1578 Fix possible nil VMSS VM in VMSS cache
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1595 chores:Retire release-0.7 and disable dependabot
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#1589 fix: fix a nil pointer issue in e2e
  tests/e2e/utils/service_utils.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#1586 chore: add a log for deleting routes that doesn't exist
  pkg/provider/azure_routes.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup

#1587 Refactor:rename GetResource to GetResourceWithExpandQuery and rename GetResourceWithDecorators to GetResource
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go
  pkg/azureclients/deploymentclient/azure_deploymentclient.go
  pkg/azureclients/deploymentclient/azure_deploymentclient_test.go
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/diskclient/azure_diskclient_test.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient_test.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/publicipclient/azure_publicipclient_test.go
  pkg/azureclients/routetableclient/azure_routetableclient.go
  pkg/azureclients/routetableclient/azure_routetableclient_test.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient_test.go
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient_test.go
  pkg/azureclients/subnetclient/azure_subnetclient.go
  pkg/azureclients/subnetclient/azure_subnetclient_test.go
  pkg/azureclients/vmasclient/azure_vmasclient.go
  pkg/azureclients/vmasclient/azure_vmasclient_test.go
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmclient/azure_vmclient_test.go
  pkg/azureclients/vmsizeclient/azure_vmsizeclient.go
  pkg/azureclients/vmsizeclient/azure_vmsizeclient_test.go
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssclient/azure_vmssclient_test.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
  pkg/azureclients/zoneclient/azure_zoneclient.go
  pkg/azureclients/zoneclient/azure_zoneclient_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#1577 [pick #1053 to release-1.23] build: build binaries for acr-credential-provider when release
  .github/workflows/release.yaml
  Makefile
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test

#1594 [e2e] Fix flaky vmss tests
  tests/e2e/node/vmss.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/flake, kind/testing

#1607 Fix "expand" is not used in getNetworkInterface()
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#1615 Update design doc for pls integration
  site/content/en/development/design-docs/pls-integration.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, release-note-none, ok-to-test

#1596 [release-1.0]Auto-generate and verify mock clients
  .github/workflows/test-updates.yml
  Makefile
  hack/boilerplate/boilerplate.gomock.txt
  hack/boilerplate/boilerplate.py
  hack/update-mock-clients.sh
  hack/verify-updates.sh
  pkg/azureclients/privatelinkserviceclient/mockprivatelinkserviceclient/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1588 fix: always get LB after updating it
  pkg/provider/azure_backoff.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_vmss_cache.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1621 [release-1.1]backport #1567 #826 #1587 #1607
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go
  pkg/azureclients/deploymentclient/azure_deploymentclient.go
  pkg/azureclients/deploymentclient/azure_deploymentclient_test.go
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/diskclient/azure_diskclient_test.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient_test.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/publicipclient/azure_publicipclient_test.go
  pkg/azureclients/routetableclient/azure_routetableclient.go
  pkg/azureclients/routetableclient/azure_routetableclient_test.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient_test.go
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient_test.go
  pkg/azureclients/subnetclient/azure_subnetclient.go
  pkg/azureclients/subnetclient/azure_subnetclient_test.go
  pkg/azureclients/vmasclient/azure_vmasclient.go
  pkg/azureclients/vmasclient/azure_vmasclient_test.go
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmclient/azure_vmclient_test.go
  pkg/azureclients/vmsizeclient/azure_vmsizeclient.go
  pkg/azureclients/vmsizeclient/azure_vmsizeclient_test.go
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssclient/azure_vmssclient_test.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
  pkg/azureclients/zoneclient/azure_zoneclient.go
  pkg/azureclients/zoneclient/azure_zoneclient_test.go
  pkg/retry/azure_retry.go
  pkg/retry/azure_retry_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#1623 fix: update probe when protocol or request path change
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1629 fix: update probe when protocol or request path change
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1628 fix: ensure TCP probe is used by default for backward compatibility
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1632 fix-0.7: update probe when protocol or request path change
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1631 fix-1.1: update probe when protocol or request path change
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1630 fix-1.0: update probe when protocol or request path change
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1627 fix-1.0: ensure TCP probe is used by default for backward compatibility
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1626 fix-1.23: ensure TCP probe is used by default for backward compatibility
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1625 fix-1.1: ensure TCP probe is used by default for backward compatibility
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M
