Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2022-11, with the labels that each got.

#2672 fix: change the curl command options when getting pod outbound IP
  tests/e2e/utils/pod_utils.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none

#2445 Deepcopy results of cache Get()
  pkg/cache/azure_cache.go
  pkg/cache/azure_cache_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_routes_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex_cache.go
  pkg/util/deepcopy/deepcopy.go
  pkg/util/deepcopy/deepcopy_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL

#2635 Use VM name instead of Node name for disk operations with Flex VMSS
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_controller_vmssflex_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#2686 publish chart v1.25.4
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.25.4.tgz
  helm/repo/index.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#2665 fix: should update dns label if target pip already have one and it needs update
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, kind/regression

#2698 Fix Bug: NetworkApiVersionMustBeSpecifiedWithNetworkInterfaceConfigurations for VMSS Flex Network Profile operation
  pkg/provider/azure_vmssflex.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#2692 [release-1.25] Deepcopy results of cache Get()
  pkg/cache/azure_cache.go
  pkg/cache/azure_cache_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_routes_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex_cache.go
  pkg/util/deepcopy/deepcopy.go
  pkg/util/deepcopy/deepcopy_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL

#2699 [release-1.24] Deepcopy results of cache Get()
  pkg/cache/azure_cache.go
  pkg/cache/azure_cache_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_routes_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmss_test.go
  pkg/util/deepcopy/deepcopy.go
  pkg/util/deepcopy/deepcopy_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL

#2702 [release-1.23] fix: should update dns label if target pip already have one and it needs update
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, kind/regression

#2653 Removed Deprecated labels from cloud-node-manager
  pkg/nodemanager/nodemanager.go
  pkg/nodemanager/nodemanager_test.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/L, kind/cleanup, ok-to-test

#2700 [release-1.25] fix: should update dns label if target pip already have one and it needs update
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, kind/regression

#2701 [release-1.24] fix: should update dns label if target pip already have one and it needs update
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, kind/regression

#2691 Fix issue: CCM fails to delete LB because updating VMSS Flex network profile fails
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_cache_test.go
  pkg/provider/azure_vmssflex_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, kind/failing-test, size/L, release-note-none, ok-to-test

#2703 [release-1.1] fix: should update dns label if target pip already have one and it needs update
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, kind/regression

#2608 Fix: Updating vmssvmcache instead of invalidating vm entry on UpdateVM operation
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
  pkg/azureclients/vmssvmclient/interface.go
  pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go
  pkg/cache/azure_cache.go
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmss_test.go
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss_cache.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#2704 [release-1.23] Deepcopy results of cache Get()
  pkg/cache/azure_cache.go
  pkg/cache/azure_cache_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_routes_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/util/deepcopy/deepcopy.go
  pkg/util/deepcopy/deepcopy_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL

#2723 fix: check private dns zone before creation
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#2735 [e2e] Skip azure-load-balancer-resource-group test for testgrid
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#2705 [release-1.1] Deepcopy results of cache Get()
  pkg/cache/azure_cache.go
  pkg/cache/azure_cache_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_routes_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/util/deepcopy/deepcopy.go
  pkg/util/deepcopy/deepcopy_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL

#2709 Fix kubetest2-aks pipeline for release branches
  .pipelines/ccm-image.yml
  .pipelines/cnm-image.yml
  .pipelines/scripts/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#2452 Add support for specifying probe protocol / probe port via annotation per service port
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  site/content/en/topics/loadbalancer.md
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#2708 Larger timeout for aks cluster creation
  kubetest2-aks/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#2733 [E2E][VMSS Flex] Modify E2E tests for VMSS Flex cluster
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/network/node.go
  tests/e2e/network/standard_lb.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/vmss_utils.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, kind/failing-test, size/M, release-note-none, ok-to-test

#2741 [VMSS Flex] refresh vmssflex cache after updating vmss flex backendpool
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, kind/failing-test, size/L, release-note-none, ok-to-test

#2776 Bound variables in run-e2e.sh
  .pipelines/scripts/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#2732 [E2E][VMSS Flex] Add a customized cloud provider config
  tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-default.json
Labels: kind/feature, cncf-cla: yes, size/XS, release-note-none, ok-to-test

#2771 fix: panic in vmss cache conversion
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmssflex_cache.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#2721 fix: remove lb from vmss when the backend pool is empty
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_vmss.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2789 [aks pipeline] CLUSTER_CONFIG_PATH can be set by users
  .pipelines/scripts/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#2707 fix public ip list call reduction
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2793 fix: remove lb from vmss when the backend pool is empty
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2794 fix: remove lb from vmss when the backend pool is empty
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2809 [release-1.1] fix public ip list call reduce
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2806 [release-1.23] fix public ip list call reduce
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2807 [release-1.24] fix public ip list call reduce
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2808 [release-1.25] fix public ip list call reduce
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2805 fix: add disk lun check in AttachDisk to avoid race condition
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_standard_test.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2810 Bound CLUSTER_CONFIG_PATH in run-e2e.sh
  .pipelines/scripts/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#2817 fix: resource group issue in disk attach
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_vmsets.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2816 fix: reduce VMSS cache refresh in CSI driver
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  pkg/provider/azure_vmss_cache.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2820 Refactor: move retry status code settings to armclient package
  pkg/azureclients/armclient/azure_armclient.go
  pkg/provider/azure.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#2827 [release-1.23]Refactor: move retry status code settings to armclient package
  go.mod
  pkg/azureclients/armclient/azure_armclient.go
  pkg/provider/azure.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#2829 Refine ip-based backend pool logic
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_test.go
  pkg/provider/azure_wrap.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, kind/cleanup

#2831 [release-1.23] fix: decouple vmss from the lb if the backend pool is empty when usin…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_wrap.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, kind/cleanup

#2832 [release-1.24] fix: decouple vmss from the lb if the backend pool is empty when usin…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_wrap.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, kind/cleanup

#2833 [release-1.25] fix: decouple vmss from the lb if the backend pool is empty when usin…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_test.go
  pkg/provider/azure_wrap.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, kind/cleanup

#2819 Cleanup: Change the struct of vmssVMCache to use only a timedCache instead of sync.Map
  go.mod
  pkg/provider/azure_controller_vmss_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmss_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test

#2835 fix: race condition in a unit test
  pkg/provider/azure_vmss_test.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none
