Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2022-06, with the labels that each got.

#1716 Cherrypick armclients 1.24
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/azureclients/deploymentclient/azure_deploymentclient.go
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/privatednsclient/azure_privatednsclient.go
  pkg/azureclients/privatednsclient/azure_privatednsclient_test.go
  pkg/azureclients/privatednsclient/interface.go
  pkg/azureclients/privatednsclient/mockprivatednsclient/interface.go
  pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
  pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient_test.go
  pkg/azureclients/privatednszonegroupclient/interface.go
  pkg/azureclients/privatednszonegroupclient/mockprivatednszonegroupclient/interface.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/routeclient/azure_routeclient.go
  pkg/azureclients/routetableclient/azure_routetableclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/subnetclient/azure_subnetclient.go
  pkg/azureclients/vmasclient/azure_vmasclient.go
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/zoneclient/azure_zoneclient.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#1790 CCM deployment uses topologySpreadConstraints
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.24.0+20220601.tgz
  helm/repo/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#1342 Add jwtty to owners list
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none, ok-to-test

#1809 Support ci-version templates for CAPZ jobs
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#1810 fix: panic when create private endpoint using azurefile NFS
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#1823 chore: Move pls doc to topics
  site/content/en/topics/pls-integration.md
Labels: approved, cncf-cla: yes, kind/documentation, size/M, release-note-none

#1824 chore: Fix doc reference
  site/content/en/topics/pls-integration.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#1821 helm: publish 1.24.1 chart with new releases
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.24.1.tgz
  helm/repo/index.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#1826 [e2e] Improve a slb testcase compatiblity
  tests/e2e/network/standard_lb.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#1827 [e2e] Skip if master VM
  tests/e2e/network/standard_lb.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#1830 Fix unexpected pls deletion issue
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#1687 Chores: refactor armclient and add request decorator to CRUD functions
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/armclient/util.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go
  pkg/azureclients/deploymentclient/azure_deploymentclient.go
  pkg/azureclients/deploymentclient/azure_deploymentclient_test.go
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/diskclient/azure_diskclient_test.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient_test.go
  pkg/azureclients/privatednsclient/azure_privatednsclient.go
  pkg/azureclients/privatednsclient/azure_privatednsclient_test.go
  pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
  pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient_test.go
  pkg/azureclients/privateendpointclient/azure_privateendpointclient.go
  pkg/azureclients/privateendpointclient/azure_privateendpointclient_test.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/publicipclient/azure_publicipclient_test.go
  pkg/azureclients/routeclient/azure_routeclient.go
  pkg/azureclients/routeclient/azure_routeclient_test.go
  pkg/azureclients/routetableclient/azure_routetableclient.go
  pkg/azureclients/routetableclient/azure_routetableclient_test.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient_test.go
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient_test.go
  pkg/azureclients/subnetclient/azure_subnetclient.go
  pkg/azureclients/subnetclient/azure_subnetclient_test.go
  pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient.go
  pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient_test.go
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmclient/azure_vmclient_test.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#1844 [e2e] Allow ListVMSSVMs returns empty list
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#1828 feat(load-balancer): support specifying Public IP address prefix to produce IP of Load Balancer
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_standard.go
  site/content/en/topics/loadbalancer.md
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_utils.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#1840 Add netlify config for cloud provider azure
  .github/workflows/gh-pages.yaml
  .gitignore
  netlify.toml
  site/config.toml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, release-note-none

#1854 [release-1.1] fix: avoid unnessary NSG updating on service reconciling
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1855 [release-1.0] fix: avoid unnessary NSG updating on service reconciling
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1853 [release-1.23] fix: avoid unnessary NSG updating on service reconciling
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#1862 chore: Update ccm/cnm versions in README
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, size/S, release-note-none

#1864 test: Recycle pip-prefix after test
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/network_utils.go
Labels: cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test

#1861 Fix empty $expand value in GetResourceWithExpandAPIVersionQuery()
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#1865 [e2e] Fix PIP prefix e2e
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#1858 [release-1.0] feat(load-balancer): support specifying Public IP address prefix to produce IP of Load Balancer
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_standard.go
  site/content/en/topics/loadbalancer.md
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, ok-to-test

#1863 fix: remove auto approval restriction
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#1866 [e2e] Clean up pip after test for azure-pip-name
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#1857 [release-1.1] feat(load-balancer): support specifying Public IP address prefix to produce IP of Load Balancer
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_standard.go
  site/content/en/topics/loadbalancer.md
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, ok-to-test

#1875 [release-1.24] Cherrypick 1864 1865
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1876 [release-1.0] Cherrypick 1864 1865
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1877 [release-1.1] Cherry-pick 1864 1865
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1856 [release-1.23] feat(load-balancer): support specifying Public IP address prefix to produce IP of Load Balancer
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_standard.go
  site/content/en/topics/loadbalancer.md
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, ok-to-test

#1878 [release-1.23] Cherrypick 1864 1865
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1895 [release-1.1] Cherrypick 1826 1827 1844 1608 1861
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/publicipclient/azure_publicipclient_test.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1896 [release-1.0] Cherrypick 1826 1827 1844 1608 1861
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/publicipclient/azure_publicipclient_test.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1893 [release-1.24] Cherrypick 1826 1827 1844 1608 1861
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/publicipclient/azure_publicipclient_test.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1894 [release-1.23] Cherrypick 1826 1827 1844 1608 1861
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/publicipclient/azure_publicipclient_test.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1847 [e2e] Dump Pod describe info
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#1901 capz: use latest windows image in test templates
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none

#1922 [e2e] ListXX can return empty list instead of error
  tests/e2e/network/node.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/network_interface_utils.go
  tests/e2e/utils/route_table_utils.go
  tests/e2e/utils/utils.go
  tests/e2e/utils/vm_utils.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1566 Refactor: refactor retry package and split validator and error parser
  pkg/retry/azure_error.go
  pkg/retry/azure_retry.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#1908 Show correct CCM/CNM version in apiserver
  hack/pkg-config.sh
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#1936 fix: Ignore errors dumping logs after listing
  hack/log-dump/log-dump.sh
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none

#1900 helm: publish 1.24.2 chart with new releases
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.24.2.tgz
  helm/repo/index.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#1950 chore: rename the LB_SKU to AZURE_LOADBALANCER_SKU to keep aligned wi…
  hack/deploy-cluster-capz.sh
  site/content/en/development/deploy-cluster.md
  tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-default.json
Labels: approved, cncf-cla: yes, size/XS, release-note-none, kind/cleanup

#1846 [e2e][Windows] Adjust Service validation for Windows cluster
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/kubectl.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/pod_utils.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#1954 fix: Invalidate vmssVMCache when rg is not found
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none

#1956 [release-1.1] Improve the error handling for ARM APIs
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#1729 Add service annotation to disable floating IP in load balancer rule
  pkg/consts/consts.go
  pkg/consts/helpers.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#1970 [release-1.0]fix: invalidate vmssVMCache when rg is not found
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none

#1955 [release-1.23] Improve the error handling for ARM APIs
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#1957 [release-1.0] Improve the error handling for ARM APIs
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L
