Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2022-09, with the labels that each got.

#2246 [release-1.0] fix: NSG destination IP version same as LB IP for floating ip disabled services
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2237 support cross subscrition for azurefile csi driver
  pkg/azureclients/fileclient/azure_fileclient.go
  pkg/azureclients/fileclient/interface.go
  pkg/azureclients/fileclient/mockfileclient/interface.go
  pkg/provider/azure_file.go
  pkg/provider/azure_storage.go
  pkg/provider/azure_storage_test.go
  pkg/provider/azure_storageaccount.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test

#2247 [release-1.1] fix: NSG destination IP version same as LB IP for floating ip disabled services
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2240 Improve flaky e2e tests
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2208 Update doc to replace aks-engine with capz
  hack/deploy-cluster-capz.sh
  site/content/en/development/deploy-cluster.md
  site/content/en/development/e2e/e2e-tests-azure.md
  site/content/en/development/e2e/e2e-tests.md
  site/content/en/example/in-tree.md
  site/content/en/example/out-of-tree.md
  site/content/en/install/azure-ccm.md
  site/content/en/install/configs.md
  site/content/en/topics/ipam.md
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool-in-tree.yaml
Labels: release-note, approved, cncf-cla: yes, lgtm, kind/documentation, size/L

#2253 Improve flaky e2e test
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#2248 feat: add support for network resource in a different subscription when using MSI
  pkg/auth/azure_auth.go
  pkg/auth/azure_auth_test.go
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_routes.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#2236 Bump gcb-docker-gcloud to v20220830-45cbff55bc
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#2245 VMSS Flex Support: Part 7 of VMSet implementation: removing LB backend pool from VMSS Flex VM related functions
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note-none, ok-to-test

#2264 Upload kubetest2-aks with correct path for releases
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#2265 [dependabot] Add 1.25 and remove 1.0
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#2177 [release-1.0] cherrypick 1846, 1996
  tests/e2e/auth/cred.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/consts.go
  tests/e2e/utils/kubectl.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/pod_utils.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/testing

#2269 feat: add Location field in DiskOptions
  pkg/provider/azure_managedDiskController.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XS

#2270 [release-1.23] Fix release kubetest2-aks
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#2268 Update readme for release 1.25
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#2275 Invoke VMSS parallel update API when vmss tag exists
  pkg/consts/consts.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#2276 fix: autoscaling-multipool tests need specify sub
  .pipelines/scripts/run-e2e.sh
  tests/e2e/autoscaling/autoscaler.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test

#2289 [release-1.1] Invoke VMSS parallel update API when vmss tag exists
  pkg/consts/consts.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#2293 [release-1.23] fix: switch all ado tests location to eastus
  .pipelines/README.md
  .pipelines/scripts/run-e2e.sh
  tests/e2e/autoscaling/autoscaler.go
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#2292 [release-1.1] fix: switch all ado tests location to eastus
  .pipelines/scripts/run-e2e.sh
  tests/e2e/autoscaling/autoscaler.go
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#2294 [release-1.24] fix: switch all ado tests location to eastus
  .pipelines/README.md
  .pipelines/scripts/run-e2e.sh
  tests/e2e/autoscaling/autoscaler.go
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#2299 Add trivy Github Action
  .github/workflows/trivy.yaml
  go.mod
  go.sum
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2295 [release-1.25] fix: switch all ado tests location to eastus
  .pipelines/README.md
  .pipelines/scripts/run-e2e.sh
  tests/e2e/autoscaling/autoscaler.go
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#2301 Pass the context for AzureFile
  pkg/azureclients/fileclient/azure_fileclient.go
  pkg/azureclients/fileclient/interface.go
  pkg/azureclients/fileclient/mockfileclient/interface.go
  pkg/provider/azure_file.go
  pkg/provider/azure_storage.go
  pkg/provider/azure_storage_test.go
  pkg/provider/azure_storageaccount.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#2298 Retry if response StatusCode 200 and ContentLength -1
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/util.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2318 [release-1.1] Retry if response StatusCode 200 and ContentLength -1
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2317 [release-1.23] Retry if response StatusCode 200 and ContentLength -1
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2316 [release-1.24] Retry if response StatusCode 200 and ContentLength -1
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/util.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2314 [release-1.1] Add trivy Github Action
  .github/workflows/trivy.yaml
  .trivyignore
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2312 [release-1.24] Add trivy Github Action
  .github/workflows/trivy.yaml
  .trivyignore
  go.mod
  go.sum
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2313 [release-1.23] Add trivy Github Action
  .github/workflows/trivy.yaml
  .trivyignore
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2323 [release-1.23] chore: update go-restful version
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/.gitignore
  vendor/github.com/emicklei/go-restful/.travis.yml
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/Makefile
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/custom_verb.go
  vendor/github.com/emicklei/go-restful/jsr311.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/route_reader.go
  vendor/github.com/emicklei/go-restful/service_error.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/modules.txt
Labels: release-note, approved, cncf-cla: yes, lgtm, size/XL, kind/cleanup

#2324 [release-1.1] chore: update go-restful version
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/.gitignore
  vendor/github.com/emicklei/go-restful/.travis.yml
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/Makefile
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/custom_verb.go
  vendor/github.com/emicklei/go-restful/jsr311.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/route_reader.go
  vendor/github.com/emicklei/go-restful/service_error.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/modules.txt
Labels: release-note, approved, cncf-cla: yes, lgtm, size/XL, kind/cleanup

#2325 [release-1.24] chore: update go-restful version
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/.gitignore
  vendor/github.com/emicklei/go-restful/.travis.yml
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/Makefile
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/custom_verb.go
  vendor/github.com/emicklei/go-restful/jsr311.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/route_reader.go
  vendor/github.com/emicklei/go-restful/service_error.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/modules.txt
Labels: release-note, approved, cncf-cla: yes, lgtm, size/XL, kind/cleanup

#2327 [release-1.23] Trivy should run for all
  .github/workflows/trivy.yaml
  .trivyignore
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#2331 [release-1.1] Trivy should run for all
  .github/workflows/trivy.yaml
  .trivyignore
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#2326 [release-1.24] Trivy should run for all
  .github/workflows/trivy.yaml
  .trivyignore
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#2354 Auto-approve dependency update
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#2363 fix: Do not retry regional when request is not GET
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/util.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2392 [release-1.23] fix: Do not retry regional when request is not GET
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2393 chore: add debug logs for http response ContentLength, StatusCode and responseBody length
  pkg/azureclients/armclient/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#2396 [release-1.23] chore: add debug logs for http response ContentLength, StatusCode and responseBody length
  pkg/azureclients/armclient/azure_armclient.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#2391 [release-1.1] fix: Do not retry regional when request is not GET
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2386 fix: Skip VMSS VM update operations if the VMs are not in good state
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
  pkg/consts/consts.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2403 fix typo and use consts in azure_loadbalancer_test.go
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, ok-to-test

#2402 chore: remove node from VMSS VM cache when it is deleted
  pkg/provider/azure.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmss_test.go
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex_cache.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#2406 Get latest service before UpdateLoadBalancer and serialize LB reconcile
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2404 add e2e tests for service annotations
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test, kind/testing

#2416 [release-1.1] chore: remove node from VMSS VM cache when it is deleted
  pkg/provider/azure.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmss_test.go
  pkg/provider/azure_mock_vmsets_test.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmss_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#2417 [release-1.23] chore: remove node from VMSS VM cache when it is deleted
  pkg/provider/azure.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmss_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmss_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#2418 [release-1.24] chore: remove node from VMSS VM cache when it is deleted
  pkg/provider/azure.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmss_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmss_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#2427 [release-1.1] Get latest service from serviceLister before UpdateLoadBalancer and s…
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2430 chore: get node private IPs from cache but NIC
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup

#2419 update k8s version in aks pipeline
  .pipelines/var-e2e.yml
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#2420 GetLoadBalancer and EnsureLoadBalancerDeleted should check both ELB and ILB
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2436 [release-1.23] Check flipped service in GetLoadBalancer
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2435 [release-1.1] Check flipped service in GetLoadBalancer
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2438 [release-1.25] Check flipped service in GetLoadBalancer
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2437 [release-1.24] Check flipped service in GetLoadBalancer
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2288 VMSS Flex Support: Embed FlexScaleSet logic into existing CCM execution flow
  pkg/consts/consts.go
  pkg/nodeipam/ipam/cloud_cidr_allocator_test.go
  pkg/provider/azure.go
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_ratelimit_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex_cache.go
Labels: size/XXL, kind/feature, approved, cncf-cla: yes, lgtm, release-note-none, ok-to-test

#2413 VMSS Flex Support: Cloud Node Manager should query resourceId field of IMDS endpoint to retrieve providerID
  pkg/provider/azure_instance_metadata.go
  pkg/provider/azure_instances.go
  pkg/provider/azure_instances_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test
