Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2022-10, with the labels that each got.

#2444 update helm chart to v1.25.2 with latest releases
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.25.2.tgz
  helm/repo/index.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#2175 [release-1.23] cherrypick 1846, 1996
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/kubectl.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/pod_utils.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/testing

#2176 [release-1.1] cherrypick 1846, 1996
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/kubectl.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/pod_utils.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/testing

#2174 [release-1.24] cherry-pick 1846, 1996
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/kubectl.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/pod_utils.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/testing

#2457 [release-1.23] Add e2e tests to avoid redundant reconciliation
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/private_link_service.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2455 [release-1.24] Add e2e tests to avoid redundant reconciliation
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/private_link_service.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2456 [release-1.1] Add e2e tests to avoid redundant reconciliation
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/private_link_service.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2428 Deprecate LoadBalancerIP with Servie LB IP annotation
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_test.go
  site/content/en/topics/pls-integration.md
  site/content/en/topics/shared-ip.md
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/kubectl.go
  tests/e2e/utils/network_utils.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/L, kind/cleanup

#2464 feat: add AccessTier and SMB MultiChannel support in storage account creation
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/S

#2470 [release-1.1] Deprecate LoadBalancerIP with Servie LB IP annotation
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_test.go
  site/content/en/topics/pls-integration.md
  site/content/en/topics/shared-ip.md
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/kubectl.go
  tests/e2e/utils/network_utils.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL, kind/cleanup, kind/deprecation

#2484 Pin gingko version to v2.2.0
  hack/ensure-ginkgo-v2.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#2490 chore: only set accessTier when it's specified
  pkg/provider/azure_storageaccount.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none

#2513 chore: refactor SetServiceProperties logic in storage account creation
  pkg/provider/azure_storageaccount.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#2524 fix: check internal lb ip in subnet before keeping it
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2489 fix: decouple vmss with 0 instance from lb when deleting the service
  hack/deploy-cluster-capz.sh
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex_test.go
  site/content/en/development/deploy-cluster.md
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2528 [release-1.25] fix: decouple vmss with 0 instance from lb when deleting the service
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2527 [release-1.24] fix: decouple vmss with 0 instance from lb when deleting the service
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2551 [e2e] Should clean up pip in azure-load-balancer-ip annotation test
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#2570 Adjust e2e tests
  tests/e2e/utils/kubectl.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#2577 Update go version params of github action
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yaml
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, size/M, release-note-none, kind/cleanup

#2584 [release-1.23]do not use netip package
  pkg/provider/azure_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#2585 do not use netip package
  pkg/provider/azure_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#2581 [release-1.23]update go version params of github action
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yaml
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#2588 add label for release notes pr
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#2523 VMSS Flex Support: Add a new vmType for pure VMSS Flex cluster to bypass the node type check
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_controller_common.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test

#2600 Fix e2e code compatibility for aks-engine clusters
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/node_utils.go
  tests/e2e/utils/pod_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#2589 fix: avoid recreate vmss cache in race condition
  go.mod
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#2525 [release-1.1] fix: decouple vmss with 0 instance from lb when deleting the service
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2458 feat: support snapshot with management api
  pkg/azureclients/fileclient/azure_fileclient.go
  pkg/azureclients/fileclient/interface.go
  pkg/azureclients/fileclient/mockfileclient/interface.go
  pkg/provider/azure_file.go
  pkg/provider/azure_storage_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#2614 chore: describe and get pod log when it is failed
  tests/e2e/utils/pod_utils.go
Labels: approved, cncf-cla: yes, kind/failing-test, size/S, release-note-none

#2615 fix: add bin/sh -s to the e2e pod command
  tests/e2e/network/standard_lb.go
Labels: approved, cncf-cla: yes, kind/failing-test, size/XS, release-note-none

#2616 Refactor e2e and print more Pod info if unexpected error
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/pod_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#2602 update helm chart to 1.25.3
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/_image.tpl
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.25.3.tgz
  helm/repo/index.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#2634 Fix ci-build in release branch: failed to deploy chart
  helm/cloud-provider-azure/Chart.yaml
  helm/repo/cloud-provider-azure-1.25.3.tgz
  helm/repo/index.yaml
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none

#2625 [release-1.24] Refactor e2e and print more Pod info if unexpected error
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/pod_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#2627 [release-1.23] Refactor e2e and print more Pod info if unexpected error
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/pod_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#2631 [release-1.1] Dump Pod describe if WaitPodTo() fails
  tests/e2e/network/network_security_group.go
  tests/e2e/utils/pod_utils.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, release-note-none

#2636 add extra release process for kubetest2-aks
  .github/dependabot.yml
  .github/workflows/kubetest2-release.yml
  .github/workflows/release.yaml
  kubetest2-aks/deployer/up.go
  kubetest2-aks/go.mod
  kubetest2-aks/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#2629 [release-1.24] Dump Pod describe if WaitPodTo() fails
  tests/e2e/network/network_security_group.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none

#2630 [release-1.23] Dump Pod describe if WaitPodTo() fails
  tests/e2e/network/network_security_group.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none

#2647 bump snapshot client to 2022-03-02
  pkg/azureclients/snapshotclient/interface.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/XS, kind/api-change

#2628 [release-1.1] Refactor e2e and print more Pod info if unexpected error
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/pod_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#2651 [release-1.23]pack latest kubetest2-aks into release package and remove kubetst2 code
  .github/workflows/release.yaml
  kubetest2-aks/Makefile
  kubetest2-aks/README.md
  kubetest2-aks/cluster-templates/autoscaling-multipool.json
  kubetest2-aks/cluster-templates/autoscaling.json
  kubetest2-aks/cluster-templates/basic-lb.json
  kubetest2-aks/cluster-templates/customconfiguration.json
  kubetest2-aks/deployer/build.go
  kubetest2-aks/deployer/deployer.go
  kubetest2-aks/deployer/down.go
  kubetest2-aks/deployer/up.go
  kubetest2-aks/go.mod
  kubetest2-aks/go.sum
  kubetest2-aks/main.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#2652 [release-1.1]pack latest kubetest2-aks into release package and remove kubetst2 code
  .github/workflows/release.yaml
  go.mod
  kubetest2-aks/Makefile
  kubetest2-aks/README.md
  kubetest2-aks/cluster-templates/autoscaling-multipool.json
  kubetest2-aks/cluster-templates/autoscaling.json
  kubetest2-aks/cluster-templates/basic-lb.json
  kubetest2-aks/cluster-templates/customconfiguration.json
  kubetest2-aks/deployer/build.go
  kubetest2-aks/deployer/deployer.go
  kubetest2-aks/deployer/down.go
  kubetest2-aks/deployer/up.go
  kubetest2-aks/go.mod
  kubetest2-aks/go.sum
  kubetest2-aks/main.go
  vendor/modules.txt
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#2650 [release-1.24]pack latest kubetest2-aks into release package and remove kubetst2 code
  .github/workflows/release.yaml
  kubetest2-aks/Makefile
  kubetest2-aks/README.md
  kubetest2-aks/cluster-templates/autoscaling-multipool.json
  kubetest2-aks/cluster-templates/autoscaling.json
  kubetest2-aks/cluster-templates/basic-lb.json
  kubetest2-aks/cluster-templates/customconfiguration.json
  kubetest2-aks/deployer/build.go
  kubetest2-aks/deployer/deployer.go
  kubetest2-aks/deployer/down.go
  kubetest2-aks/deployer/up.go
  kubetest2-aks/go.mod
  kubetest2-aks/go.sum
  kubetest2-aks/main.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#2649 [release-1.25]pack latest kubetest2-aks into release package and remove kubetst2 code
  .github/workflows/release.yaml
  kubetest2-aks/Makefile
  kubetest2-aks/README.md
  kubetest2-aks/cluster-templates/autoscaling-multipool.json
  kubetest2-aks/cluster-templates/autoscaling.json
  kubetest2-aks/cluster-templates/basic-lb.json
  kubetest2-aks/cluster-templates/customconfiguration.json
  kubetest2-aks/deployer/build.go
  kubetest2-aks/deployer/deployer.go
  kubetest2-aks/deployer/down.go
  kubetest2-aks/deployer/up.go
  kubetest2-aks/go.mod
  kubetest2-aks/go.sum
  kubetest2-aks/main.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#2654 chore: log pod info in WaitPodsToBeReady
  tests/e2e/utils/pod_utils.go
Labels: approved, cncf-cla: yes, size/M, release-note-none, kind/cleanup
