Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2022-01, with the labels that each got.

#961 chore: enrich docs for putVMSSVMBatchSize
  site/content/en/install/configs.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#957 chore: add a capz template for multi-vmss cluster with out-of-tree ccm
  tests/k8s-azure/manifest/cluster-api/multi-slb-config.json
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#939 cherry-pick from #921 to release-0.7 (build: cross-compile under linux/amd64 platform)
  cloud-node-manager.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#965 chore: use containerd for dual-stack and ipv6
  tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json
  tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json
  tests/k8s-azure/manifest/linux-ipv6.json
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none, kind/cleanup

#967 test: fix test failures on capz clusters
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none

#966 feat: support sending sync requests concurrently in batches when putt…
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
  pkg/azureclients/vmssvmclient/interface.go
  pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go
  pkg/provider/azure.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#959 feat: support sending sync requests concurrently in batches when putting vmss vm
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
  pkg/azureclients/vmssvmclient/interface.go
  pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go
  pkg/provider/azure.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#964 feat: support sending sync requests concurrently in batches when putt…
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
  pkg/azureclients/vmssvmclient/interface.go
  pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go
  pkg/provider/azure.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#973 fix: return all LBs in the resource group in ListManagedLBs when dele…
  pkg/provider/azure_backoff.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#972 fix: return all LBs in the resource group in ListManagedLBs when dele…
  pkg/provider/azure_backoff.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#971 fix: return all LBs in the resource group in ListManagedLBs when dele…
  pkg/provider/azure_backoff.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#975 fix: install breaking change autoprefixer@10.4.1
  site/package-lock.json
  site/package.json
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XL, release-note-none, ok-to-test

#978 build: fix building multi-arch ccm image
  Dockerfile
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#981 cherry-pick #926 #936 #978 to release-1.0
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test

#977 chore: use azurecni for dual-stack
  tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json
  tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none, kind/cleanup, ok-to-test

#980 cherry-pick #926 #936 #978 to release-0.7
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test

#979 cherry-pick #926 #936 #978 to release-1.1
  Dockerfile
  Makefile
  site/package-lock.json
  site/package.json
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, ok-to-test

#970 doc: release v1.23.1, v1.1.4, v1.0.8 and v0.7.11
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
  site/content/en/blog/releases/v0.7.11.md
  site/content/en/blog/releases/v1.0.8.md
  site/content/en/blog/releases/v1.1.4.md
  site/content/en/blog/releases/v1.23.1.md
Labels: approved, cncf-cla: yes, kind/documentation, size/L, release-note-none

#982 Cherry-pick #607, #627 and #841 to branch release-0.7
  pkg/consts/consts.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmss.go
  site/content/en/topics/tagging-resources.md
  tests/e2e/e2e_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/node_utils.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/utils.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/XL, ok-to-test

#989 doc: update contents for release doc v0.7.11, v1.0.8 and v1.1.4
  site/content/en/blog/releases/v0.7.11.md
  site/content/en/blog/releases/v1.0.8.md
  site/content/en/blog/releases/v1.1.4.md
Labels: approved, cncf-cla: yes, kind/documentation, size/M, release-note-none

#985 Upgrade aks-engine used in build-kubemark.sh to v0.66.1
  tests/kubemark/build-kubemark.sh
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS, ok-to-test

#974 chore: Polish node manager image building
  Makefile
  README.md
  cloud-node-manager-windows.Dockerfile
  cloudbuild.yaml
  site/content/en/development/custom-images.md
  site/content/en/development/e2e/e2e-tests.md
  site/content/en/development/future.md
  site/content/en/development/image-building.md
Labels: release-note, approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#990 Upgrade docker/dockerfile image
  Dockerfile
  Makefile
  cloud-node-manager.Dockerfile
  hack/boilerplate/boilerplate.Dockerfile.txt
Labels: release-note, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#986 chore: reduce node LIST APIs in cloud-node-manager
  cmd/cloud-node-manager/app/options/options.go
  pkg/nodemanager/nodemanager.go
  pkg/nodemanager/nodemanager_test.go
  pkg/provider/azure.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/L, kind/cleanup

#998 cherry-pick of #986 to release-1.1: reduce node LIST APIs in cloud-node-manager
  cmd/cloud-node-manager/app/options/options.go
  pkg/nodemanager/nodemanager.go
  pkg/nodemanager/nodemanager_test.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/L, kind/cleanup

#996 cherry-pick of #986 to release-1.23: reduce node LIST APIs in cloud-node-manager
  cmd/cloud-node-manager/app/options/options.go
  pkg/nodemanager/nodemanager.go
  pkg/nodemanager/nodemanager_test.go
  pkg/provider/azure.go
  site/package-lock.json
  site/package.json
Labels: release-note, approved, cncf-cla: yes, lgtm, size/XL, kind/cleanup

#997 cherry-pick of #986 to release-1.0: reduce node LIST APIs in cloud-node-manager
  cmd/cloud-node-manager/app/options/options.go
  pkg/nodemanager/nodemanager.go
  pkg/nodemanager/nodemanager_test.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/L, kind/cleanup

#994 cherry-pick of #974 to release-1.1: chore: Polish node manager image building
  Makefile
  README.md
  cloud-node-manager-windows.Dockerfile
  cloudbuild.yaml
  site/content/en/development/custom-images.md
  site/content/en/development/e2e/e2e-tests.md
  site/content/en/development/future.md
  site/content/en/development/image-building.md
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#993 cherry-pick of #974 to release-0.7: chore: Polish node manager image building
  Makefile
  README.md
  cloud-node-manager-windows.Dockerfile
  cloudbuild.yaml
  site/content/en/development/custom-images.md
  site/content/en/development/e2e/e2e-tests.md
  site/content/en/development/future.md
  site/content/en/development/image-building.md
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test

#995 cherry-pick of #974 to release-1.0: chore: Polish node manager image building
  Makefile
  README.md
  cloud-node-manager-windows.Dockerfile
  cloudbuild.yaml
  site/content/en/development/custom-images.md
  site/content/en/development/e2e/e2e-tests.md
  site/content/en/development/future.md
  site/content/en/development/image-building.md
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#988 chore: support deploy capz clusters by make target
  Makefile
  hack/deploy-cluster-capz.sh
  hack/ensure-clusterctl.sh
  hack/ensure-kind.sh
  site/content/en/development/deploy-cluster.md
  tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-default.json
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
Labels: release-note, approved, cncf-cla: yes, lgtm, size/L, kind/cleanup

#1001 chore: add more customizations to the capz cloud config template
  hack/deploy-cluster-capz.sh
  tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-default.json
Labels: cncf-cla: yes, release-note-none, kind/cleanup

#1000 linux-vmss-multi-zone template: enable TopologyAwareHints
  tests/k8s-azure/manifest/linux-vmss-multi-zones.json
Labels: release-note, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test

#1003 chore: add ssh public key customization for capz cluster deployment
  hack/deploy-cluster-capz.sh
  site/content/en/development/deploy-cluster.md
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
Labels: cncf-cla: yes, release-note-none, kind/cleanup

#1004 fix: do not update tags on load balancer, security group and route ta…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_routes.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#1005 Override subscription and tenant configs when network resources is in different tenant or subscriptions
  pkg/auth/azure_auth.go
  pkg/provider/azure.go
  pkg/provider/azure_standard.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#1008 fix: do not update tags on load balancer, security group and route ta…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_routes.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#1007 fix: do not update tags on load balancer, security group and route ta…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_routes.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#1006 fix: do not update tags on load balancer, security group and route ta…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_routes.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#1012 cherry-pick of #1005to release-0.7:Override subscription and tenant configs when network resources is in…
  pkg/auth/azure_auth.go
  pkg/provider/azure.go
  pkg/provider/azure_standard.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#1013 chores: MartinForReal join maintainer team of cloud-provider-azure
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#1011 Backport 1.0:Override subscription and tenant configs when network resources is in different tenant or subscription
  pkg/auth/azure_auth.go
  pkg/provider/azure.go
  pkg/provider/azure_standard.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#1009 Backport 1.1:Override subscription and tenant configs when network resources is in different tenant or subscription
  pkg/auth/azure_auth.go
  pkg/provider/azure.go
  pkg/provider/azure_standard.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#1014 build: add Github action workflow for publishing release
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#1010 Backport 1.23:Override subscription and tenant configs when network resources is in different tenant or subscription
  pkg/auth/azure_auth.go
  pkg/provider/azure.go
  pkg/provider/azure_standard.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#1017 [cherry pick #1014 for 1.1] build: add Github action workflow for publishing release
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#1016 [cherry pick #1014 for 1.0] build: add Github action workflow for publishing release
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#1019 build(release): fix the branch to scrape while originating from master
  .github/workflows/release.yaml
Labels: needs-ok-to-test, cncf-cla: yes, size/XS, release-note-none

#1020 [cherry pick #1019 for 1.0] build(release): fix the branch to scrape while originating from master
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#1015 [cherry pick #1014 for 0.7] build: add Github action workflow for publishing release
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#1021 [cherry pick #1019 for 1.1] build(release): fix the branch to scrape while originating from master
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#1022 [cherry pick #1019 for 0.7] build(release): fix the branch to scrape while originating from master #1021
  .github/workflows/release.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, ok-to-test

#1023 [cherry pick #1014 / #1019 for 1.23] build: add Github action workflow for publishing release
  .github/workflows/release.yaml
Labels: needs-ok-to-test, cncf-cla: yes, size/L, release-note-none

#1024 [cherry-pick #974 to 1.23] Polish node manager image building
  Makefile
  README.md
  cloud-node-manager-windows.Dockerfile
  cloudbuild.yaml
  site/content/en/development/custom-images.md
  site/content/en/development/e2e/e2e-tests.md
  site/content/en/development/future.md
  site/content/en/development/image-building.md
Labels: cncf-cla: yes, size/L, release-note-none, ok-to-test

#1030 Chores: add release-* to monitored branches of Dependabot
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#1035 chore: Add actions to scan code
  .github/workflows/codeql-analysis.yml
  pkg/azureclients/armclient/azure_armclient.go
  pkg/retry/azure_retry.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#992 remove docker login
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, ok-to-test

#1053 build: build binaries for acr-credential-provider when release
  .github/workflows/release.yaml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test

#1062 chores: ignore update in build images
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, size/S, release-note-none, kind/cleanup

#1061 feat: support platformSubFaultDomain node label
  pkg/consts/consts.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/nodemanager/mock/mock_node_provider.go
  pkg/nodemanager/nodemanager.go
  pkg/nodemanager/nodemanager_test.go
  pkg/provider/azure_instance_metadata.go
  pkg/provider/azure_zones.go
  pkg/provider/azure_zones_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#1081 [release-0.7] feat: support platformSubFaultDomain node label
  pkg/consts/consts.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/nodemanager/mock/mock_node_provider.go
  pkg/nodemanager/nodemanager.go
  pkg/nodemanager/nodemanager_test.go
  pkg/provider/azure_instance_metadata.go
  pkg/provider/azure_zones.go
  pkg/provider/azure_zones_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#1083 [release-1.1] feat: support platformSubFaultDomain node label
  pkg/consts/consts.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/nodemanager/mock/mock_node_provider.go
  pkg/nodemanager/nodemanager.go
  pkg/nodemanager/nodemanager_test.go
  pkg/provider/azure_instance_metadata.go
  pkg/provider/azure_zones.go
  pkg/provider/azure_zones_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#1082 [release-0.7] feat: support platformSubFaultDomain node label
  pkg/consts/consts.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/nodemanager/mock/mock_node_provider.go
  pkg/nodemanager/nodemanager.go
  pkg/nodemanager/nodemanager_test.go
  pkg/provider/azure_instance_metadata.go
  pkg/provider/azure_zones.go
  pkg/provider/azure_zones_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#1070 fix: use zones in the pre-existing frontend IP configurations for int…
  pkg/azureclients/interfaceclient/interface.go
  pkg/azureclients/loadbalancerclient/interface.go
  pkg/azureclients/publicipclient/interface.go
  pkg/azureclients/routeclient/interface.go
  pkg/azureclients/routetableclient/interface.go
  pkg/azureclients/securitygroupclient/interface.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_interface_utils.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/route_table_utils.go
  tests/e2e/utils/service_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#1088 build: fix generating release note
  .github/workflows/release.yaml
Labels: needs-ok-to-test, cncf-cla: yes, size/S, release-note-none

#1094 build: fix generating release note
  .github/workflows/release.yaml
Labels: needs-ok-to-test, cncf-cla: yes, size/S, release-note-none

#1095 [release-1.0] fix: use zones in the pre-existing frontend IP configurations for int…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#1096 [release-1.1] Cherry pick of #1070 to release-1.1
  pkg/azureclients/interfaceclient/interface.go
  pkg/azureclients/loadbalancerclient/interface.go
  pkg/azureclients/publicipclient/interface.go
  pkg/azureclients/routeclient/interface.go
  pkg/azureclients/routetableclient/interface.go
  pkg/azureclients/securitygroupclient/interface.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_interface_utils.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/route_table_utils.go
  tests/e2e/utils/service_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#1091 build: fix generating release note
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test

#1086 Simplify update-dependencies.sh
  hack/update-dependencies.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test

#1092 build: fix generating release note
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test

#1093 build: fix generating release note
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test

#1097 [release-1.23] Cherry pick of #1070 to release-1.23
  pkg/azureclients/interfaceclient/interface.go
  pkg/azureclients/loadbalancerclient/interface.go
  pkg/azureclients/publicipclient/interface.go
  pkg/azureclients/routeclient/interface.go
  pkg/azureclients/routetableclient/interface.go
  pkg/azureclients/securitygroupclient/interface.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_interface_utils.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/route_table_utils.go
  tests/e2e/utils/service_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#1089 [release-0.7] fix: use zones in the pre-existing frontend IP configurations for int…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L
