Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2022-08, with the labels that each got.

#2104 [release-1.0] Less mem usage for golangci-lint by less concurrency
  .golangci.yml
  cmd/cloud-controller-manager/app/core.go
  cmd/cloud-controller-manager/app/testing/testserver.go
  hack/verify-golint.sh
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/nodeipam/ipam/doc.go
  pkg/nodemanager/nodemanager.go
  pkg/provider/azure_blobDiskController.go
  pkg/provider/azure_instances.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_routes.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_wrap.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2108 fix aks pipeline gc job typo and job scheduling typo
  .pipelines/daily-gc.yml
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test

#2103 [release-1.1] Less mem usage for golangci-lint by less concurrency
  .golangci.yml
  cmd/cloud-controller-manager/app/core.go
  cmd/cloud-controller-manager/app/testing/testserver.go
  hack/verify-golint.sh
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/nodeipam/ipam/doc.go
  pkg/nodemanager/nodemanager.go
  pkg/provider/azure_blobDiskController.go
  pkg/provider/azure_instances.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_routes.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_wrap.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2118 chore: update cloud-provider modules to v0.23.9
  go.mod
  go.sum
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/apiserver/pkg/audit/union.go
  vendor/k8s.io/apiserver/pkg/authentication/group/authenticated_group_adder.go
  vendor/k8s.io/apiserver/pkg/authentication/group/group_adder.go
  vendor/k8s.io/apiserver/pkg/authentication/group/token_group_adder.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/filters/timeout.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/request/list_work_estimator.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/cloud-provider/controllers/node/node_controller.go
  vendor/k8s.io/cloud-provider/controllers/route/route_controller.go
  vendor/k8s.io/cloud-provider/controllers/service/controller.go
  vendor/k8s.io/component-base/metrics/prometheus/restclient/metrics.go
  vendor/k8s.io/component-base/version/.gitattributes
  vendor/modules.txt
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2123 lower verbosity in ci template due to the limitation of logging space
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test

#2133 Typos fixed in pls-integration.md
  site/content/en/topics/pls-integration.md
Labels: needs-ok-to-test, release-note, approved, cncf-cla: yes, lgtm, kind/documentation, size/XS

#2124 Modify aks pipeline to separate k8s version env var and make code more concise
  .pipelines/README.md
  .pipelines/daily-gc.yml
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
  .pipelines/run-basic-lb-e2e.yml
  .pipelines/run-e2e.yml
  .pipelines/scripts/run-e2e.sh
  .pipelines/var-e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test

#2119 chore: update cloud-provider modules to v0.22.12
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/audit/union.go
  vendor/k8s.io/apiserver/pkg/authentication/group/authenticated_group_adder.go
  vendor/k8s.io/apiserver/pkg/authentication/group/group_adder.go
  vendor/k8s.io/apiserver/pkg/authentication/group/token_group_adder.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/filters/timeout.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/cloud-provider/controllers/node/node_controller.go
  vendor/k8s.io/cloud-provider/controllers/route/route_controller.go
  vendor/k8s.io/cloud-provider/controllers/service/controller.go
  vendor/k8s.io/component-base/metrics/prometheus/restclient/metrics.go
  vendor/k8s.io/component-base/version/.gitattributes
  vendor/modules.txt
Labels: release-note, approved, kind/bug, cncf-cla: yes, size/L

#2100 VMSS Flex Support: Add vmssflex_cache.go and unit tests
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_cache.go
  pkg/provider/azure_vmssflex_cache_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note-none, ok-to-test

#2106 Fix e2e tests to support aks cluster
  Makefile
  hack/test-ccm-e2e.sh
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/node_utils.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/L, release-note-none, kind/cleanup, ok-to-test

#2138 [e2e] Retry when getting security group list
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#2141 fix: public ip version check
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#2148 [release-1.0] fix: pip UT issue
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#2142 add encryption setting in storage account creation
  pkg/provider/azure_backoff.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#2120 helm: publish 1.24.4 with new versions
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.24.4.tgz
  helm/repo/index.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#2144 feat: change blobclient from management api to rest api
  pkg/azureclients/blobclient/azure_blobclient.go
  pkg/azureclients/blobclient/azure_blobclient_test.go
  pkg/azureclients/blobclient/interface.go
  pkg/azureclients/blobclient/mockblobclient/interface.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/L, ok-to-test, do-not-merge/needs-kind

#2161 Revert "fix: don't set vm entry as nil in cache when vm is in Deleting state to avoid VMSSList throttling"
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#2162 add flake attempts in aks pipeline tests
  .pipelines/scripts/run-e2e.sh
  hack/test-ccm-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test

#2153 test: Add e2e tests to avoid redundant reconciliation
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/private_link_service.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2170 cleanup: don't print error logging for user assigned client id
  pkg/auth/azure_auth.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#2169 chore: hard-code -flake-attempts instead of using CCM_E2E_ARGS
  .pipelines/scripts/run-e2e.sh
  hack/test-ccm-e2e.sh
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, size/S, release-note-none, kind/cleanup

#2155 VMSS Flex Support: Computer hostName rather than VMName should be used as nodeName
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_cache.go
  pkg/provider/azure_vmssflex_cache_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#2173 Introduce AllowSharedKeyAccess to the StorageAccount creation options
  pkg/provider/azure_storageaccount.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#2178 add log artifacts in aks pipeline
  .pipelines/run-e2e.yml
  .pipelines/scripts/collect-log.sh
  .pipelines/scripts/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, ok-to-test

#2172 make ConvertResourceGroupNameToLower exportable
  pkg/provider/azure_standard.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#2160 VMSS Flex Support: FlexScaleSet implementation of VMSet: part 1
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#2179 VMSS Flex Support: FlexScaleSet implementation of VMSet: part 2 -- Disk attach / detacch
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_controller_vmssflex_test.go
  pkg/provider/azure_vmssflex_cache.go
  pkg/provider/azure_vmssflex_cache_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note-none, ok-to-test

#2087 Skip "instance not found" error for LB backend address pools
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_vmss.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#2198 chore: increase log level in arm client to reduce logs
  pkg/azureclients/armclient/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#2200 chore: add more default setting in storage account encryption setting
  pkg/provider/azure_storageaccount.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note-none

#2164 [release-1.1] Add azure pipeline in release 1.1
  .github/workflows/release.yaml
  .pipelines/README.md
  .pipelines/ccm-image.yml
  .pipelines/cnm-image.yml
  .pipelines/daily-gc.yml
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
  .pipelines/run-basic-lb-e2e.yml
  .pipelines/run-e2e.yml
  .pipelines/scripts/collect-log.sh
  .pipelines/scripts/daily-gc.sh
  .pipelines/scripts/run-e2e.sh
  .pipelines/templates/autoscaling-multipool.json
  .pipelines/templates/autoscaling.json
  .pipelines/templates/basic-lb.json
  .pipelines/templates/customconfiguration.json
  .pipelines/var-e2e.yml
  hack/test-ccm-e2e.sh
  kubetest2-aks/Makefile
  kubetest2-aks/README.md
  kubetest2-aks/cluster-templates/autoscaling-multipool.json
  kubetest2-aks/cluster-templates/autoscaling.json
  kubetest2-aks/cluster-templates/basic-lb.json
  kubetest2-aks/cluster-templates/customconfiguration.json
  kubetest2-aks/deployer/build.go
  kubetest2-aks/deployer/deployer.go
  kubetest2-aks/deployer/down.go
  kubetest2-aks/deployer/up.go
  kubetest2-aks/go.mod
  kubetest2-aks/go.sum
  kubetest2-aks/main.go
  tests/e2e/auth/cred.go
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/consts.go
  tests/e2e/utils/node_utils.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/vmss_utils.go
Labels: needs-ok-to-test, size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/testing

#2199 modify aks pipelines for test security and success rate
  .pipelines/README.md
  .pipelines/run-basic-lb-e2e.yml
  .pipelines/scripts/collect-log.sh
  .pipelines/scripts/run-e2e.sh
  hack/test-ccm-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, ok-to-test

#2165 [release-1.23] Add azure pipeline in release 1.23
  .github/workflows/release.yaml
  .pipelines/README.md
  .pipelines/ccm-image.yml
  .pipelines/cnm-image.yml
  .pipelines/daily-gc.yml
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
  .pipelines/run-basic-lb-e2e.yml
  .pipelines/run-e2e.yml
  .pipelines/scripts/collect-log.sh
  .pipelines/scripts/daily-gc.sh
  .pipelines/scripts/run-e2e.sh
  .pipelines/templates/autoscaling-multipool.json
  .pipelines/templates/autoscaling.json
  .pipelines/templates/basic-lb.json
  .pipelines/templates/customconfiguration.json
  .pipelines/var-e2e.yml
  hack/test-ccm-e2e.sh
  kubetest2-aks/Makefile
  kubetest2-aks/README.md
  kubetest2-aks/cluster-templates/autoscaling-multipool.json
  kubetest2-aks/cluster-templates/autoscaling.json
  kubetest2-aks/cluster-templates/basic-lb.json
  kubetest2-aks/cluster-templates/customconfiguration.json
  kubetest2-aks/deployer/build.go
  kubetest2-aks/deployer/deployer.go
  kubetest2-aks/deployer/down.go
  kubetest2-aks/deployer/up.go
  kubetest2-aks/go.mod
  kubetest2-aks/go.sum
  kubetest2-aks/main.go
  tests/e2e/auth/cred.go
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/consts.go
  tests/e2e/utils/node_utils.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/vmss_utils.go
Labels: needs-ok-to-test, size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/testing

#2180 VMSS Flex Support: VMSet implementation part 3 for VM modelview related functions
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_cache.go
  pkg/provider/azure_vmssflex_cache_test.go
  pkg/provider/azure_vmssflex_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#2166 [release-1.24] Add azure pipeline in release 1.24
  .github/workflows/release.yaml
  .pipelines/README.md
  .pipelines/ccm-image.yml
  .pipelines/cnm-image.yml
  .pipelines/daily-gc.yml
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
  .pipelines/run-basic-lb-e2e.yml
  .pipelines/run-e2e.yml
  .pipelines/scripts/collect-log.sh
  .pipelines/scripts/daily-gc.sh
  .pipelines/scripts/run-e2e.sh
  .pipelines/templates/autoscaling-multipool.json
  .pipelines/templates/autoscaling.json
  .pipelines/templates/basic-lb.json
  .pipelines/templates/customconfiguration.json
  .pipelines/var-e2e.yml
  hack/test-ccm-e2e.sh
  kubetest2-aks/Makefile
  kubetest2-aks/README.md
  kubetest2-aks/cluster-templates/autoscaling-multipool.json
  kubetest2-aks/cluster-templates/autoscaling.json
  kubetest2-aks/cluster-templates/basic-lb.json
  kubetest2-aks/cluster-templates/customconfiguration.json
  kubetest2-aks/deployer/build.go
  kubetest2-aks/deployer/deployer.go
  kubetest2-aks/deployer/down.go
  kubetest2-aks/deployer/up.go
  kubetest2-aks/go.mod
  kubetest2-aks/go.sum
  kubetest2-aks/main.go
  tests/e2e/auth/cred.go
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/consts.go
  tests/e2e/utils/node_utils.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/vmss_utils.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, ok-to-test, kind/testing

#2183 VMSS Flex Support: part 5 of FlexScaleSet Implementation of VMSet interface mainly for network related functions
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_cache_test.go
  pkg/provider/azure_vmssflex_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note-none, ok-to-test

#2220 chore: update version matrix
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#2219 fix: correct condition message for NodeNetworkUnavailable
  pkg/nodemanager/nodemanager.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#2209 link helm chart in deploy instructions
  site/content/en/install/azure-ccm.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none, ok-to-test

#2210 add missing `patch` perm to cloud-node-manager SA
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.24.5.tgz
  helm/repo/index.yaml
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test

#2230 fix: NSG destination IP version same as LB IP for floating ip disabled services
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2202 VMSS Flex Support: Part 6 of FlexScaleSet implementation of VMSet interface for adding LB backend pool to vmss flex VMs related functions
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_cache_test.go
  pkg/provider/azure_vmssflex_test.go
Labels: size/XXL, kind/feature, approved, cncf-cla: yes, lgtm, release-note-none, ok-to-test
