Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2022-12, with the labels that each got.

#2830 fix: add disk lun check in VMSSFlex AttachDisk to avoid race condition
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_controller_vmssflex_test.go
  pkg/provider/azure_vmssflex_cache_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2841 fix: lock the entry when reading data
  pkg/provider/azure_utils.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none

#2834 chore: remove orphaned nic from lb backend pool if the corresponding …
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_vmss.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup

#2844 [release-1.23] chore: remove orphaned nic from lb backend pool if the corresponding …
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_vmss.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup

#2845 [release-1.24] chore: remove orphaned nic from lb backend pool if the corresponding …
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_vmss.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup

#2846 [release-1.25] chore: remove orphaned nic from lb backend pool if the corresponding …
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_vmss.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup

#2847 fix: fix race in VMSS cache update
  pkg/provider/azure_vmss_cache.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/regression

#2857 Enable CGO for kubetest2-aks make deployer
  kubetest2-aks/Makefile
Labels: approved, cncf-cla: yes, size/XS, release-note-none, kind/testing

#2842 [e2e] Support IPv6 single stack clusters
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/ip_utils.go
  tests/e2e/utils/ip_utils_test.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2811 Add single stack IPv6 and dualstack CAPZ templates
  tests/k8s-azure/manifest/cluster-api/linux-dualstack.yaml
  tests/k8s-azure/manifest/cluster-api/linux-ipv6.yaml
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/testing

#2840 docs(helm): document allocate node cidrs value
  helm/cloud-provider-azure/README.md
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#2863 [e2e] Support IPv6 single stack clusters
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/ip_utils.go
  tests/e2e/utils/ip_utils_test.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2864 [e2e] Support IPv6 single stack clusters
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/ip_utils.go
  tests/e2e/utils/ip_utils_test.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2865 [e2e] Support IPv6 single stack clusters
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/ip_utils.go
  tests/e2e/utils/ip_utils_test.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2868 build: upgrade golangci-lint and run lint in Github Action
  .github/workflows/lint.yaml
  .golangci.yml
  Makefile
  hack/verify-golint.sh
  pkg/provider/azure_standard.go
  tests/e2e/network/service_annotations.go
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#2828 Feat:Add annotation service.beta.kubernetes.io/port_%d_health-probe_only
  .golangci-test.yml
  pkg/consts/consts.go
  pkg/consts/helpers.go
  pkg/consts/helpers_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#2862 feat: add system assigned identity support for kubetest2-aks
  .gitignore
  kubetest2-aks/README.md
  kubetest2-aks/cluster-templates/autoscaling-multipool.json
  kubetest2-aks/cluster-templates/autoscaling.json
  kubetest2-aks/cluster-templates/basic-lb.json
  kubetest2-aks/deployer/up.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#2823 [release-1.25]Add support for specifying probe protocol / probe port via annotation per service port
  .golangci-test.yml
  pkg/consts/consts.go
  pkg/consts/helpers.go
  pkg/consts/helpers_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  site/content/en/topics/loadbalancer.md
  tests/e2e/network/service_annotations.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#2875 cleanup: set context as parameter in cloud provider functions
  cmd/cloud-controller-manager/app/controllermanager.go
  cmd/cloud-node-manager/app/nodemanager.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/node/nodeproviderfactory.go
  pkg/provider/azure.go
  pkg/provider/azure_config.go
  pkg/provider/azure_config_test.go
  pkg/provider/azure_controller_common_test.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_cache.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test

#2879 Fix kubetest2-aks managed cluster
  kubetest2-aks/cluster-templates/autoscaling-multipool.json
  kubetest2-aks/cluster-templates/autoscaling.json
  kubetest2-aks/cluster-templates/basic-lb.json
  kubetest2-aks/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2824 [release-1.24]Add support for specifying probe protocol / probe port via annotation per service port
  pkg/consts/consts.go
  pkg/consts/helpers.go
  pkg/consts/helpers_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  site/content/en/topics/loadbalancer.md
  tests/e2e/network/service_annotations.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#2878 Helm chart 1.25.5 with new releases
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.25.5.tgz
  helm/repo/index.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#2866 Fix k8s-azure-dns-label-service tag not deleted with Service
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/service_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2883 fix: CVE-2022-41717
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2926 [release-1.24]/fix CVE text
  go.mod
  go.sum
  vendor/modules.txt
Labels: release-note, approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup

#2927 fix: close WaitForUpdateResult response
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmclient/azure_vmclient_test.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none

#2931 chore: update helm chart to migrate from insecure to secure serving
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/README.md
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/cloud-provider-azure/values.yaml
  helm/repo/cloud-provider-azure-1.26.0.tgz
  helm/repo/index.yaml
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup

#2910 [release-1.25] Fix k8s-azure-dns-label-service tag not deleted with Service
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/service_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2923 build: enable errorlint and fix issues
  .golangci-test.yml
  .golangci.yml
  cmd/acr-credential-provider/main.go
  cmd/acr-credential-provider/plugin.go
  cmd/cloud-controller-manager/app/controllermanager.go
  cmd/cloud-controller-manager/app/options/options_test.go
  cmd/cloud-controller-manager/app/testing/testserver.go
  cmd/cloud-controller-manager/controller-manager.go
  cmd/cloud-node-manager/node-manager.go
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/util.go
  pkg/azureclients/blobclient/azure_blobclient_test.go
  pkg/azureclients/blobclient/interface.go
  pkg/azureclients/containerserviceclient/interface.go
  pkg/azureclients/privateendpointclient/azure_privateendpointclient_test.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go
  pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
  pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient.go
  pkg/azureclients/virtualnetworklinksclient/interface.go
  pkg/azureclients/vmasclient/interface.go
  pkg/azureclients/vmsizeclient/interface.go
  pkg/credentialprovider/azure_acr_helper.go
  pkg/credentialprovider/azure_credentials.go
  pkg/nodemanager/nodemanager.go
  pkg/provider/azure.go
  pkg/provider/azure_config_test.go
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_controller_vmssflex_test.go
  pkg/provider/azure_instance_metadata.go
  pkg/provider/azure_instances.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_cache.go
  pkg/provider/azure_vmssflex_test.go
  pkg/retry/azure_error.go
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/ip_utils.go
  tests/e2e/utils/kubectl.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/pod_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test

#2911 [release-1.24] Fix k8s-azure-dns-label-service tag not deleted with Service
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/service_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2933 [release-1.24]bump k8s.io components to 0.24.9
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#2912 [release-1.23] Fix k8s-azure-dns-label-service tag not deleted with Service
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/service_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2932 [release-1.25]bump k8s.io components to 0.25.5
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/delete.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/equality.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go
  vendor/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/request/list_work_estimator.go
  vendor/k8s.io/cloud-provider/controllers/service/controller.go
  vendor/k8s.io/cloud-provider/node/helpers/taints.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/conn.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none

#2942 Remove kubetest2-aks dir
  kubetest2-aks/Makefile
  kubetest2-aks/README.md
  kubetest2-aks/cluster-templates/autoscaling-multipool.json
  kubetest2-aks/cluster-templates/autoscaling.json
  kubetest2-aks/cluster-templates/basic-lb.json
  kubetest2-aks/cluster-templates/customconfiguration.json
  kubetest2-aks/deployer/build.go
  kubetest2-aks/deployer/deployer.go
  kubetest2-aks/deployer/down.go
  kubetest2-aks/deployer/up.go
  kubetest2-aks/go.mod
  kubetest2-aks/go.sum
  kubetest2-aks/main.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/testing

#2945 [release 1.23] build: run golangci-lint in Github Action and enable errorlint
  .github/workflows/lint.yaml
  .golangci.yml
  Makefile
  cmd/acr-credential-provider/main.go
  cmd/acr-credential-provider/plugin.go
  cmd/cloud-controller-manager/app/options/options_test.go
  cmd/cloud-controller-manager/app/testing/testserver.go
  cmd/cloud-controller-manager/controller-manager.go
  cmd/cloud-node-manager/node-manager.go
  hack/verify-golint.sh
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/containerserviceclient/interface.go
  pkg/azureclients/privateendpointclient/azure_privateendpointclient_test.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go
  pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
  pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient.go
  pkg/azureclients/virtualnetworklinksclient/interface.go
  pkg/azureclients/vmasclient/interface.go
  pkg/azureclients/vmsizeclient/interface.go
  pkg/credentialprovider/azure_acr_helper.go
  pkg/credentialprovider/azure_credentials.go
  pkg/nodemanager/nodemanager.go
  pkg/provider/azure.go
  pkg/provider/azure_config_test.go
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_instance_metadata.go
  pkg/provider/azure_instances.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/retry/azure_error.go
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/ip_utils.go
  tests/e2e/utils/kubectl.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/pod_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test

#2946 [release 1.24] build: run golangci-lint in Github Action and enable errorlint
  .github/workflows/lint.yaml
  .golangci-test.yml
  .golangci.yml
  Makefile
  cmd/acr-credential-provider/main.go
  cmd/acr-credential-provider/plugin.go
  cmd/cloud-controller-manager/app/options/options_test.go
  cmd/cloud-controller-manager/app/testing/testserver.go
  cmd/cloud-controller-manager/controller-manager.go
  cmd/cloud-node-manager/node-manager.go
  hack/verify-golint.sh
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/util.go
  pkg/azureclients/containerserviceclient/interface.go
  pkg/azureclients/privateendpointclient/azure_privateendpointclient_test.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go
  pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
  pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient.go
  pkg/azureclients/virtualnetworklinksclient/interface.go
  pkg/azureclients/vmasclient/interface.go
  pkg/azureclients/vmsizeclient/interface.go
  pkg/credentialprovider/azure_acr_helper.go
  pkg/credentialprovider/azure_credentials.go
  pkg/nodemanager/nodemanager.go
  pkg/provider/azure.go
  pkg/provider/azure_config_test.go
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_instance_metadata.go
  pkg/provider/azure_instances.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/retry/azure_error.go
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/ip_utils.go
  tests/e2e/utils/kubectl.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/pod_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test

#2947 [release 1.25] build: run golangci-lint in Github Action and enable errorlint
  .github/workflows/lint.yaml
  .golangci-test.yml
  .golangci.yml
  Makefile
  cmd/acr-credential-provider/main.go
  cmd/acr-credential-provider/plugin.go
  cmd/cloud-controller-manager/app/controllermanager.go
  cmd/cloud-controller-manager/app/options/options_test.go
  cmd/cloud-controller-manager/app/testing/testserver.go
  cmd/cloud-controller-manager/controller-manager.go
  cmd/cloud-node-manager/node-manager.go
  hack/verify-golint.sh
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/util.go
  pkg/azureclients/blobclient/azure_blobclient_test.go
  pkg/azureclients/blobclient/interface.go
  pkg/azureclients/containerserviceclient/interface.go
  pkg/azureclients/privateendpointclient/azure_privateendpointclient_test.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go
  pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
  pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient.go
  pkg/azureclients/virtualnetworklinksclient/interface.go
  pkg/azureclients/vmasclient/interface.go
  pkg/azureclients/vmsizeclient/interface.go
  pkg/credentialprovider/azure_acr_helper.go
  pkg/credentialprovider/azure_credentials.go
  pkg/nodemanager/nodemanager.go
  pkg/provider/azure.go
  pkg/provider/azure_config_test.go
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_controller_vmssflex_test.go
  pkg/provider/azure_instance_metadata.go
  pkg/provider/azure_instances.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_cache.go
  pkg/provider/azure_vmssflex_test.go
  pkg/retry/azure_error.go
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/ip_utils.go
  tests/e2e/utils/kubectl.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/pod_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test

#2949 Use TimedCache.Get() for read-only resources
  pkg/cache/azure_cache.go
  pkg/cache/azure_cache_test.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_wrap.go
  tests/e2e/network/node.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/consts.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none

#2948 [release-1.23]fix go1.17 mod selection issue
  go.sum
  hack/update-dependencies.sh
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#2944 build(release): generate release note from last minor version when release a new minor version
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test

#2963 chore: upgrade ubuntu to 22.04 for github actions
  .github/workflows/test-docs.yaml
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, release-note-none

#2965 Add dependabot config for release-1.26
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#2964 fix: create PrivateDNSZone error in sovereign cloud
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2975 Get latest K8s ver with branch name in aks pipeline
  .pipelines/run-e2e.yml
  .pipelines/scripts/run-e2e.sh
  .pipelines/var-e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#2978 Add docs for no_lb_rule and no_probe_rule annotations
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#2979 [kubetest2-aks] Support more components
  .pipelines/scripts/run-e2e.sh
  kubetest2-aks/cluster-templates/customconfiguration-azuredisk.json
  kubetest2-aks/cluster-templates/customconfiguration-azurefile.json
  kubetest2-aks/cluster-templates/customconfiguration-ccm.json
  kubetest2-aks/cluster-templates/customconfiguration-k8s.json
  kubetest2-aks/cluster-templates/slb.json
  kubetest2-aks/deployer/deployer.go
  kubetest2-aks/deployer/up.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#2976 cleanup: remove unused controllerCommon fields
  pkg/provider/azure.go
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_common_test.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_managedDiskController_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_storage.go
  pkg/provider/azure_storage_test.go
  pkg/provider/azure_vmssflex.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#2950 feat: update cache support for starndard and vmss flex
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmclient/azure_vmclient_test.go
  pkg/azureclients/vmclient/interface.go
  pkg/azureclients/vmclient/mockvmclient/interface.go
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_common_test.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_standard_test.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_controller_vmssflex_test.go
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmssflex_cache.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#2951 improvement: Flex - Reduce throttling on Attach/Detach disk operations
  pkg/provider/azure_vmssflex_cache.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test

#2985 fix: race condition in lockMap
  pkg/provider/azure_utils.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#2984 fix: get vmss name and resource group from vm ID if the provider ID o…
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2988 [release-1.26] fix: get vmss name and resource group from vm ID if the provider ID o…
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2989 [release-1.25] fix: get vmss name and resource group from vm ID if the provider ID o…
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2991 [release-1.23] fix: get vmss name and resource group from vm ID if the provider ID o…
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2990 [release-1.24] fix: get vmss name and resource group from vm ID if the provider ID o…
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#2993 feat: add DisableUpdateCache flag
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_controller_vmssflex_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#2987 fix: support custom storage endpoint suffix
  pkg/provider/azure_storage_test.go
  pkg/provider/azure_storageaccount.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test

#2992 feat: Support privateendpoint for blob-csi-driver
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/S, ok-to-test

#2996 Refactor azure_loadbalancer*.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#3002 [release-1.23] Refactor azure_loadbalancer*.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#2998 feat: support private endpoint for blob and file csi driver
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#2997 Update how IMAGE_TAG is set
  .pipelines/scripts/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#2994 Helm chart 1.26.1 with new release
  README.md
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.26.1.tgz
  helm/repo/index.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none
