Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2022-05, with the labels that each got.

#1638 chore: update documents and helm charts
  README.md
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/README.md
  helm/cloud-provider-azure/values.yaml
  helm/repo/cloud-provider-azure-1.23.11.tgz
  helm/repo/index.yaml
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, release-note-none

#1484 Private Link Service Integration for k8s service
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
  pkg/provider/azure_ratelimit_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_wrap.go
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm, ok-to-test

#1645 docs: language fixes to README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, release-note-none

#1640 chore(helm): publish cloud-provider-azure chart 1.23.11
  hack/update-helm-repo.sh
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/cloud-provider-azure/values.yaml
  helm/repo/cloud-provider-azure-1.23.11.tgz
  helm/repo/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#1646 feat: add DiskEncryptionType in CreateDisk
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_managedDiskController_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, size/S

#1550 Refactor: Use armclient functions
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/azureclients/deploymentclient/azure_deploymentclient.go
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/vmasclient/azure_vmasclient.go
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/zoneclient/azure_zoneclient.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1656 Fix verify helm script
  hack/verify-helm-repo.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#1612 Refactor: Use existing GetXXXError methods
  pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go
  pkg/azureclients/deploymentclient/azure_deploymentclient_test.go
  pkg/azureclients/publicipclient/azure_publicipclient_test.go
  pkg/azureclients/routeclient/azure_routeclient_test.go
  pkg/azureclients/routetableclient/azure_routetableclient_test.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient_test.go
  pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
  pkg/azureclients/subnetclient/azure_subnetclient_test.go
  pkg/azureclients/vmclient/azure_vmclient_test.go
  pkg/azureclients/vmssclient/azure_vmssclient_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1661 chore: update readme and examples
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/XS, release-note-none

#1660 chores: update CI configs for release branches
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/gh-pages.yaml
  .github/workflows/test-coverage.yml
  .github/workflows/test-docs.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/L, release-note-none

#1556 Refactor private dns zone and zone group clients
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/privatednsclient/azure_privatednsclient.go
  pkg/azureclients/privatednsclient/azure_privatednsclient_test.go
  pkg/azureclients/privatednsclient/interface.go
  pkg/azureclients/privatednsclient/mockprivatednsclient/interface.go
  pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
  pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient_test.go
  pkg/azureclients/privatednszonegroupclient/interface.go
  pkg/azureclients/privatednszonegroupclient/mockprivatednszonegroupclient/interface.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#1682 [Release 1.1]feat: Add pip cache
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_ratelimit_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_test.go
  pkg/provider/azure_wrap.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#1690 Update release notes for v1.24.0
  site/content/en/blog/releases/v1.24.0.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#1683 [Release-1.0]feat: Private Link Service Integration for k8s service
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go
  pkg/azureclients/privatelinkserviceclient/interface.go
  pkg/azureclients/privatelinkserviceclient/mockprivatelinkserviceclient/interface.go
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
  pkg/provider/azure_ratelimit_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_wrap.go
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm, ok-to-test

#1681 [Release-1.23]feat:Private Link Service Integration for k8s service
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
  pkg/provider/azure_ratelimit_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_wrap.go
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm, ok-to-test

#1691 [Release-1.1]feat: Private Link Service Integration for k8s service
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
  pkg/provider/azure_ratelimit_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_wrap.go
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm, ok-to-test

#1658 helm: update docs to clarify chart maintenance requirements
  helm/cloud-provider-azure/README.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, release-note-none

#1613 Refactor: Use variables for providers and types
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/azureclients/deploymentclient/azure_deploymentclient.go
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/routeclient/azure_routeclient.go
  pkg/azureclients/routetableclient/azure_routetableclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/subnetclient/azure_subnetclient.go
  pkg/azureclients/vmasclient/azure_vmasclient.go
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/zoneclient/azure_zoneclient.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1688 helm: add support for Kubernetes 1.24
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.24.0.tgz
  helm/repo/index.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note-none

#1702 Add missing rate limit configs for some clients
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/provider/azure.go
  pkg/provider/azure_ratelimit.go
  site/content/en/install/configs.md
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#1698 Disable floating IP on ILB IPv6 rule
  pkg/consts/helpers.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, ok-to-test

#1703 Improve ccm printing version and docker buildx logs
  Makefile
  cmd/cloud-controller-manager/app/controllermanager.go
  pkg/version/base.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#1692 test: Add e2e tests for private link service integration
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup, ok-to-test

#1701 chore: remove GA IPv6DualStack feature-gate
  cmd/cloud-controller-manager/app/core.go
  pkg/consts/consts.go
  pkg/provider/azure.go
  tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json
  tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet-1.23.json
  tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json
  tests/k8s-azure/manifest/windows-dual-stack.json
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup

#1715 [release-1.24]test: Add e2e tests for pls
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_utils.go
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#1712 [release-1.0]test: Add e2e tests for pls
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_utils.go
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#1705 Fix: do not block creating route operation for unmanaged node when du…
  pkg/provider/azure_routes.go
  pkg/provider/azure_routes_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#1714 [release-1.23]test: Add e2e tests for pls
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_utils.go
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#1713 [release-1.1]test: Add e2e tests for pls
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_utils.go
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#1718 Cherrypick armclients 1.23
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go
  pkg/azureclients/deploymentclient/azure_deploymentclient.go
  pkg/azureclients/deploymentclient/azure_deploymentclient_test.go
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/privatednsclient/azure_privatednsclient.go
  pkg/azureclients/privatednsclient/azure_privatednsclient_test.go
  pkg/azureclients/privatednsclient/interface.go
  pkg/azureclients/privatednsclient/mockprivatednsclient/interface.go
  pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
  pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient_test.go
  pkg/azureclients/privatednszonegroupclient/interface.go
  pkg/azureclients/privatednszonegroupclient/mockprivatednszonegroupclient/interface.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/publicipclient/azure_publicipclient_test.go
  pkg/azureclients/routeclient/azure_routeclient.go
  pkg/azureclients/routeclient/azure_routeclient_test.go
  pkg/azureclients/routetableclient/azure_routetableclient.go
  pkg/azureclients/routetableclient/azure_routetableclient_test.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient_test.go
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/subnetclient/azure_subnetclient.go
  pkg/azureclients/subnetclient/azure_subnetclient_test.go
  pkg/azureclients/vmasclient/azure_vmasclient.go
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmclient/azure_vmclient_test.go
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssclient/azure_vmssclient_test.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/zoneclient/azure_zoneclient.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#1719 Cherrypick armclients 1.1
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/armclient/interface.go
  pkg/azureclients/armclient/mockarmclient/interface.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go
  pkg/azureclients/deploymentclient/azure_deploymentclient.go
  pkg/azureclients/deploymentclient/azure_deploymentclient_test.go
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/privatednsclient/azure_privatednsclient.go
  pkg/azureclients/privatednsclient/azure_privatednsclient_test.go
  pkg/azureclients/privatednsclient/interface.go
  pkg/azureclients/privatednsclient/mockprivatednsclient/interface.go
  pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
  pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient_test.go
  pkg/azureclients/privatednszonegroupclient/interface.go
  pkg/azureclients/privatednszonegroupclient/mockprivatednszonegroupclient/interface.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/publicipclient/azure_publicipclient_test.go
  pkg/azureclients/routeclient/azure_routeclient.go
  pkg/azureclients/routeclient/azure_routeclient_test.go
  pkg/azureclients/routetableclient/azure_routetableclient.go
  pkg/azureclients/routetableclient/azure_routetableclient_test.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient_test.go
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/subnetclient/azure_subnetclient.go
  pkg/azureclients/subnetclient/azure_subnetclient_test.go
  pkg/azureclients/vmasclient/azure_vmasclient.go
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmclient/azure_vmclient_test.go
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssclient/azure_vmssclient_test.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/zoneclient/azure_zoneclient.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#1730 Cherry-pick armclients 1.0
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go
  pkg/azureclients/deploymentclient/azure_deploymentclient.go
  pkg/azureclients/deploymentclient/azure_deploymentclient_test.go
  pkg/azureclients/diskclient/azure_diskclient.go
  pkg/azureclients/interfaceclient/azure_interfaceclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/azureclients/publicipclient/azure_publicipclient.go
  pkg/azureclients/publicipclient/azure_publicipclient_test.go
  pkg/azureclients/routeclient/azure_routeclient.go
  pkg/azureclients/routeclient/azure_routeclient_test.go
  pkg/azureclients/routetableclient/azure_routetableclient.go
  pkg/azureclients/routetableclient/azure_routetableclient_test.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient_test.go
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/subnetclient/azure_subnetclient.go
  pkg/azureclients/subnetclient/azure_subnetclient_test.go
  pkg/azureclients/vmasclient/azure_vmasclient.go
  pkg/azureclients/vmclient/azure_vmclient.go
  pkg/azureclients/vmclient/azure_vmclient_test.go
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssclient/azure_vmssclient_test.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/zoneclient/azure_zoneclient.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1740 [release-1.0]Support Azure resource ID as userAssignedIdentityID
  pkg/auth/azure_auth.go
  pkg/auth/azure_auth_test.go
  pkg/auth/testdata/test.pfx
  pkg/provider/azure.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#1706 [e2e] Add LB tests about switching between public and internal ones
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/utils/pod_utils.go
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#1744 [CI] Add vmss template for CAPZ
  tests/k8s-azure/manifest/cluster-api/linux-vmss.yaml
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#1743 [e2e] Improve pls and azure-pip-tags tests
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#1745 helm: update tolerations and nodeSelectors
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.24.0+20220519.tgz
  helm/repo/index.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#1755 [helm] Fix template and add check
  hack/verify-helm-repo.sh
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.24.0+20220519.tgz
  helm/repo/cloud-provider-azure-1.24.0+20220523.tgz
  helm/repo/index.yaml
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#1753 [release-1.0][e2e] Improve pls and azure-pip-tags tests
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#1754 [release-1.1][e2e] Improve pls and azure-pip-tags tests
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#1767 chore: fix aks engine deploy script
  hack/deploy-cluster.sh
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#1644 Improve helm chart: Allow to enable or disable cloudControllerManager/cloudNodeManager, configure ca certificates directory and replicas
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/README.md
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/cloud-provider-azure/values.yaml
  helm/repo/cloud-provider-azure-1.24.0+20220523.tgz
  helm/repo/cloud-provider-azure-1.24.0+20220526.tgz
  helm/repo/index.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test

#1768 Bump gopkg.in/yaml.v3
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#1784 chore: Use containerd for aks-engine e2e test deployment
  examples/aks-engine.json
  tests/k8s-azure/manifest/linux-vmss.json
Labels: cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none, ok-to-test

#1783 feat: add blobclient for blob container operations
  pkg/azureclients/blobclient/azure_blobclient.go
  pkg/azureclients/blobclient/azure_blobclient_test.go
  pkg/azureclients/blobclient/doc.go
  pkg/azureclients/blobclient/interface.go
  pkg/azureclients/blobclient/mockblobclient/doc.go
  pkg/azureclients/blobclient/mockblobclient/interface.go
  pkg/provider/azure.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L
