Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2023-06, with the labels that each got.

#4030 chore: pin the site dependencies
  .github/workflows/hugo.yml
  site/package-lock.json
  site/package.json
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XL, release-note-none

#4031 Cleanup dependencies and fix cron job
  .github/dependabot.yml
  .github/workflows/hugo.yml
  .gitignore
  netlify.toml
  site/config/_default/config.toml
  site/config/githubpage/config.toml
  site/config/netlify/config.toml
  site/go.mod
  site/go.sum
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, release-note-none, kind/testing

#4034 fix: ensure POSTCSS is installed
  .github/workflows/hugo.yml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#3988 [e2e] Service annotation var should be deep copied
  pkg/provider/azure_loadbalancer.go
  tests/e2e/network/private_link_service.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, release-note-none

#3972 feat: support migrate from NIC-based to IP-based backend pool by migration API by setting `"enableMigrateToIPBasedBackendPoolAPI": true`
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient_test.go
  pkg/azureclients/loadbalancerclient/interface.go
  pkg/azureclients/loadbalancerclient/mockloadbalancerclient/interface.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_vmss.go
  site/content/en/install/configs.md
  site/content/en/topics/loadbalancer.md
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#4033 track2 sdk:add clientFactory and parse config from file
  pkg/azclient/auth.go
  pkg/azclient/client-gen/generator/codegenerator.go
  pkg/azclient/config.go
  pkg/azclient/default.go
  pkg/azclient/factory.go
  pkg/azclient/go.mod
  pkg/azclient/go.sum
  pkg/azclient/policy/ratelimit/flowcontrol/docs.go
  pkg/azclient/policy/ratelimit/flowcontrol/throttle.go
  pkg/azclient/policy/ratelimit/flowcontrol/throttle_test.go
  pkg/azclient/policy/ratelimit/ratelimit.go
  pkg/azclient/policy/retry.go
  pkg/azclient/policy/retryrepectthrottled/throttle.go
  pkg/azclient/utils/options.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note-none

#3914 [IPv6] Fix reconcileFrontendIPConfigs()
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/standard_lb.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL

#2677 Add CCM_E2E_TIMEOUT option for ginkgo running ccm e2e tests
  hack/test-ccm-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#4043 [Dual-Stack][CI] Add CAPZ templates
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-md.yaml
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/testing

#4042 [release-1.27] feat: support migrate from NIC-based to IP-based backend pool by migration API by setting `"enableMigrateToIPBasedBackendPoolAPI": true`
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient_test.go
  pkg/azureclients/loadbalancerclient/interface.go
  pkg/azureclients/loadbalancerclient/mockloadbalancerclient/interface.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_vmss.go
  site/content/en/install/configs.md
  site/content/en/topics/loadbalancer.md
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#4044 [release-1.26] feat: support migrate from NIC-based to IP-based backend pool by migration API by setting `"enableMigrateToIPBasedBackendPoolAPI": true`
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient_test.go
  pkg/azureclients/loadbalancerclient/interface.go
  pkg/azureclients/loadbalancerclient/mockloadbalancerclient/interface.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_vmss.go
  site/content/en/install/configs.md
  site/content/en/topics/loadbalancer.md
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#4046 [release-1.24] feat: support migrate from NIC-based to IP-based backend pool by migration API by setting `"enableMigrateToIPBasedBackendPoolAPI": true`
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient_test.go
  pkg/azureclients/loadbalancerclient/interface.go
  pkg/azureclients/loadbalancerclient/mockloadbalancerclient/interface.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_vmss.go
  site/content/en/install/configs.md
  site/content/en/topics/loadbalancer.md
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#4045 [release-1.25] feat: support migrate from NIC-based to IP-based backend pool by migration API by setting `"enableMigrateToIPBasedBackendPoolAPI": true`
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
  pkg/azureclients/loadbalancerclient/azure_loadbalancerclient_test.go
  pkg/azureclients/loadbalancerclient/interface.go
  pkg/azureclients/loadbalancerclient/mockloadbalancerclient/interface.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_vmss.go
  site/content/en/install/configs.md
  site/content/en/topics/loadbalancer.md
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#4053 doc: update image versions in the doc
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
Labels: cncf-cla: yes, kind/documentation, release-note-none

#4047 fix: replace deprecated labels with new labels in nodeCache update
  pkg/provider/azure.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#4055 Remove MachinePool in dualstack-md template
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-md.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#4069 track2 sdk: Apply dependency injection pattern to auth provider
  .github/workflows/codespell.yaml
  pkg/azclient/auth.go
  pkg/azclient/auth_test.go
  pkg/azclient/azclient_suite_test.go
  pkg/azclient/config.go
  pkg/azclient/testdata/auth.yaml
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none

#4067 feat: add GetLatestAccountKey in account key fetch
  go.mod
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#4077 track2 sdk: add config parser for track2 client
  pkg/azclient/arm_conf.go
  pkg/azclient/auth.go
  pkg/azclient/cloud.go
  pkg/azclient/cloud_test.go
  pkg/azclient/config.go
  pkg/azclient/default.go
  pkg/azclient/factory.go
  pkg/azclient/factory_conf.go
  pkg/azclient/utils/poller.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note-none

#4074 Fix vmssflex ensureBackendPoolDeletedFromNode
  pkg/provider/azure_standard.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#4076 chore: skip exclude node label e2e test on aks as it is only supporte…
  tests/e2e/network/ensureloadbalancer.go
Labels: release-note, approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, kind/cleanup

#4083 track2 sdk: reuse cred object in auth provider
  pkg/azclient/auth.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#4079 chore: bump docsy to 0.7.0
  netlify.toml
  site/content/en/_index.html
  site/go.mod
  site/go.sum
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#4084 update workflow config
  .codespellignore
  .github/workflows/codespell.yaml
  site/content/en/blog/releases/v1.1.25.md
  site/content/en/blog/releases/v1.23.22.md
  site/content/en/blog/releases/v1.24.12.md
  site/content/en/blog/releases/v1.24.18.md
  site/content/en/blog/releases/v1.24.19.md
  site/content/en/blog/releases/v1.24.9.md
  site/content/en/blog/releases/v1.25.12.md
  site/content/en/blog/releases/v1.25.3.md
  site/content/en/blog/releases/v1.25.6.md
  site/content/en/blog/releases/v1.26.0.md
  site/content/en/blog/releases/v1.26.8.md
  site/content/en/blog/releases/v1.27.0.md
  site/content/en/topics/loadbalancer.md
  site/content/en/topics/node-types.md
  site/content/en/topics/pls-integration.md
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#4097 track2 sdk: only set go-armbalancer for resource client
  pkg/azclient/factory_conf.go
  pkg/azclient/utils/options.go
  pkg/azclient/utils/transport.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#4075 feat: support load balancer choosing logic for multi-slb
  pkg/consts/consts.go
  pkg/consts/helpers.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_utils.go
  site/content/en/topics/loadbalancer.md
  site/content/en/topics/multislb.md
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm

#4066 update to debian bullseye, buster EOL soon
  Dockerfile
  Makefile
  cloud-node-manager.Dockerfile
  e2e.Dockerfile
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/S, kind/cleanup

#4111 helm: add logVerbosity to cloud-node-manager
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/README.md
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/cloud-provider-azure/values.yaml
  helm/repo/cloud-provider-azure-1.27.5.tgz
  helm/repo/index.yaml
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup

#4134 Update go.sum with go v1.20.5
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#4136 fix: remove deleted node IP address from IP-based LB backend pools
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#4144 track2 sdk:add GetVirtualMachineScaleSetNetworkInterface for interface client
  pkg/azclient/client-gen/cmd/typescaffold/type_scaffold.go
  pkg/azclient/interfaceclient/interface.go
  pkg/azclient/interfaceclient/mock_interfaceclient/interface.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#4145 track2 sdk:add mock for client factory
  pkg/azclient/arm_conf.go
  pkg/azclient/client-gen/generator/files.go
  pkg/azclient/client-gen/generator/genclientfactory_action.go
  pkg/azclient/cloud.go
  pkg/azclient/factory.go
  pkg/azclient/factory_gen.go
  pkg/azclient/factory_test.go
  pkg/azclient/mock_azclient/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/testing

#4152 Chroes: fix go build version in codeql job
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yaml
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#4154 [release-1.26]update go sum with go1.20.5
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#3898 [DualStack] Support NSG and clean LBs
  pkg/consts/consts.go
  pkg/consts/helpers.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/service_utils.go
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm

#4149 [release-1.25] fix: remove deleted node IP address from IP-based LB backend pools
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#4147 [release-1.27] fix: remove deleted node IP address from IP-based LB backend pools
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#4146 [release-1.26] fix: remove deleted node IP address from IP-based LB backend pools
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#4155 track2 sdk: move sub to config struct in client factory
  pkg/azclient/client-gen/generator/genclientfactory_action.go
  pkg/azclient/factory.go
  pkg/azclient/factory_conf.go
  pkg/azclient/factory_gen.go
  pkg/azclient/factory_test.go
  pkg/azclient/mock_azclient/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#4156 bump k8s.io to 0.27.3
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#4159 [Pipeline] Limit max node count to 100
  .pipelines/templates/autoscaling-multipool.json
  .pipelines/templates/autoscaling.json
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#4161 chore: pkg imported more than once
  pkg/nodeipam/ipam/cloud_cidr_allocator.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, ok-to-test

#4163 track2 sdk: downgrade otel library to 1.10.0 to resolve dependency conflict
  pkg/azclient/go.mod
  pkg/azclient/go.sum
  pkg/azclient/utils/tracing.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#4168 [release-1.27]chores:move docs to documentation branch
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#4169 [release-1.26]chores:move docs to documentation branch
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#4170 [release-1.25]chores: move docs to documentation branch
  .github/workflows/release.yaml
  .github/workflows/test-docs.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, release-note-none

#4171 [release-1.24]chores: move docs to documentation branch
  .github/workflows/release.yaml
  .github/workflows/test-docs.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, release-note-none

#4165 Revert "chore(deps): bump go.opentelemetry.io/otel/trace from 1.10.0 to 1.16.0 in /pkg/azclient"
  pkg/azclient/go.mod
  pkg/azclient/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#4172 chores: add vendor update job
  .github/workflows/codeql-analysis.yml
  .github/workflows/update-vendor-license.yml
Labels: approved, cncf-cla: yes, size/M, release-note-none, kind/testing

#4174 [release-1.25]chores: add vendor update job
  .github/workflows/codeql-analysis.yml
  .github/workflows/update-vendor-license.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#4175 [release-1.26]chores: add vendor update job
  .github/workflows/codeql-analysis.yml
  .github/workflows/update-vendor-license.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#4176 [release-1.27]chores: add vendor update job
  .github/workflows/codeql-analysis.yml
  .github/workflows/update-vendor-license.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#4135 [ARG] Add an option to disable API call cache
  pkg/cache/azure_cache.go
  pkg/cache/azure_cache_test.go
  pkg/provider/azure.go
  pkg/provider/azure_instance_metadata.go
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_cache.go
  pkg/provider/azure_wrap.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#4185 [Pipeline] Fix get_k8s_version failure
  .pipelines/scripts/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#4192 [Pipeline] Move aks-preview extension addition order
  .pipelines/scripts/run-e2e.sh
Labels: approved, cncf-cla: yes, size/XS, release-note-none, kind/testing

#4193 fix: PerformancePlus setting issue
  pkg/provider/azure_controller_common.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#4203 fix: storage account search default values
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S
