Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2023-01, with the labels that each got.

#3008 [aks pipeline] Set IMAGE_TAG before building ccm, cnm images
  .pipelines/ccm-image.yml
  .pipelines/cnm-image.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#3007 [kubetest2-aks] Print correct image tag
  kubetest2-aks/deployer/build.go
  kubetest2-aks/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#3006 fix: set ForceAttemptHTTP2 to increase ARM throttling limit
  pkg/azureclients/armclient/azure_armclient.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS, ok-to-test

#3010 Refactor: move ratelimit config to config package
  pkg/provider/azure.go
  pkg/provider/azure_ratelimit_test.go
  pkg/provider/config/azure_ratelimit.go
  pkg/provider/config/azure_ratelimit_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#3017 azureclient v2: add recorder for v2 client ut cases
  pkg/azureclients/v2/go.mod
  pkg/azureclients/v2/go.sum
  pkg/azureclients/v2/recording/counter.go
  pkg/azureclients/v2/recording/recorder.go
  pkg/azureclients/v2/recording/transport.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#3021 [aks pipeline] Upgrade Go version to 1.19
  .pipelines/ccm-image.yml
  .pipelines/cnm-image.yml
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
  .pipelines/run-basic-lb-e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#3023 fix: jq last returns null when no match
  .pipelines/scripts/run-e2e.sh
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#3016 Refactor: move auth config to config package
  pkg/credentialprovider/azure_acr_helper.go
  pkg/credentialprovider/azure_credentials.go
  pkg/provider/azure.go
  pkg/provider/azure_config_test.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_test.go
  pkg/provider/config/azure_auth.go
  pkg/provider/config/azure_auth_test.go
  pkg/provider/config/doc.go
  pkg/provider/config/testdata/test.pfx
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#3019 [Doc] Add Service Azure LB IPv4 & IPv6 to LB doc
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#3051 [release-1.23] Get latest K8s ver with branch name in aks pipeline
  .pipelines/run-e2e.yml
  .pipelines/scripts/run-e2e.sh
  .pipelines/var-e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#3069 doc: update image versions in readme
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
Labels: cncf-cla: yes, kind/documentation, release-note-none

#3070 Set --skip-nodes-with-system-pods to false when running autoscaling tests
  .pipelines/scripts/run-e2e.sh
  .pipelines/templates/customconfiguration-autoscaling.json
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#3072 [pipeline] Wait shorter when scale down node pool
  .pipelines/templates/customconfiguration-autoscaling.json
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#3071 chore: Add metrics for reconciling private link service
  pkg/provider/azure_privatelinkservice.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#3084 fix: update rather than replace existing cache entry
  go.mod
  go.sum
  pkg/cache/azure_cache.go
  pkg/cache/azure_cache_test.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#3104 doc: update pls doc
  site/content/en/topics/pls-integration.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#3105 [release-1.25] Use TimedCache.Get() for read-only resources
  pkg/cache/azure_cache.go
  pkg/cache/azure_cache_test.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_wrap.go
  tests/e2e/network/node.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/consts.go
  tests/e2e/utils/vmss_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#3107 Use TimedCache.Get() for read-only resources
  pkg/cache/azure_cache.go
  pkg/cache/azure_cache_test.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_wrap.go
  tests/e2e/network/node.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/consts.go
  tests/e2e/utils/vmss_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#3106 [release-1.24] Use TimedCache.Get() for read-only resources
  pkg/cache/azure_cache.go
  pkg/cache/azure_cache_test.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_wrap.go
  tests/e2e/network/node.go
  tests/e2e/node/vmss.go
  tests/e2e/utils/consts.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3085 fix: add more account search options
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL

#3114 doc: adding ipTags doc
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, release-note-none

#3108 Setting up Cluster Autoscaler E2E Pipeline to use kubetest2-aks
  .pipelines/scripts/run-e2e.sh
  hack/test-ccm-e2e.sh
  kubetest2-aks/cluster-templates/autoscaling-e2e.json
  kubetest2-aks/cluster-templates/customconfiguration-cas.json
  kubetest2-aks/deployer/up.go
  kubetest2-aks/go.mod
  kubetest2-aks/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test, kind/deprecation

#3117 Always use registry.k8s.io
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#3132 Update health probe docs
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#3130 Put K8s customconfig k8s file to .pipelines
  .pipelines/templates/customconfiguration-k8s.json
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#3131 [release-1.23] Put customconfig k8s file to .pipelines
  .pipelines/templates/customconfiguration-k8s.json
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#3136 Fix VMSS scale test in multipool clusters
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#3140 [release-1.26] use pip list in pip cache
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#3141 [release-1.25] use pip list in pip cache
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#3143 [release-1.23] use pip list in pip cache
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#3142 [release-1.24] use pip list in pip cache
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#3137 chore: add new metrics in ReconcileBackendPools when migrating backen…
  pkg/provider/azure_loadbalancer_backendpool.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#3144 fix: make account search backward compatible
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test

#3115 feat: support data protection for blob csi driver
  pkg/azureclients/blobclient/azure_blobclient.go
  pkg/azureclients/blobclient/interface.go
  pkg/azureclients/blobclient/mockblobclient/interface.go
  pkg/provider/azure_storage_test.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#2995 Remove Calico ClusterResourceSets from CAPZ templates
  tests/k8s-azure/manifest/cluster-api/linux-dualstack.yaml
  tests/k8s-azure/manifest/cluster-api/linux-ipv6.yaml
  tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss-multiple-zones.yaml
  tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss.yaml
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool-in-tree.yaml
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#3214 Remove etcd workaround in ipv6 test templates
  tests/k8s-azure/manifest/cluster-api/linux-dualstack.yaml
  tests/k8s-azure/manifest/cluster-api/linux-ipv6.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none

#3234 build: Fix downloading golangci-lint using master branch script
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, ok-to-test

#3212 fix: skip removing nics from lb if there will be no nics in the backe…
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  tests/e2e/network/ensureloadbalancer.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#3235 Bump to python3
  hack/boilerplate/boilerplate.py
  hack/boilerplate/boilerplate_test.py
  hack/boilerplate/test/fail.py
  hack/boilerplate/test/pass.py
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#3165 chore: refine logging for azure disk csi driver
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_managedDiskController_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#3260 cleanup: refine azure disk driver logging
  pkg/provider/azure_controller_common.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup
