Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2023-03, with the labels that each got.

#3410 azureclient track2:customize default transporter in track2 client
  pkg/azureclients/v2/go.mod
  pkg/azureclients/v2/go.sum
  pkg/azureclients/v2/utils/options.go
  pkg/azureclients/v2/utils/transport.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#3417 Fix a loop pointer bug in EnsureBackendPoolDeleted
  pkg/provider/azure_standard.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#3480 Limit dependbot open pr limit to 3
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#3481 Add lints for loop pointer
  .github/workflows/lint.yaml
  Makefile
  pkg/nodemanager/nodemanager.go
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmss_test.go
  tests/e2e/utils/network_interface_utils.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#3479 Update linux-ci-version.yaml to support using vmss flex
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#3498 [release-1.23] Add lints for loop pointer
  .github/workflows/lint.yaml
  Makefile
  pkg/nodemanager/nodemanager.go
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmss_test.go
  tests/e2e/utils/network_interface_utils.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#3482 fix: detach disk failure when there is throttling
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_common_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#3496 [release-1.25] Add lints for loop pointer
  .github/workflows/lint.yaml
  Makefile
  pkg/nodemanager/nodemanager.go
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmss_test.go
  tests/e2e/utils/network_interface_utils.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#3495 [release-1.26] Add lints for loop pointer
  .github/workflows/lint.yaml
  Makefile
  pkg/nodemanager/nodemanager.go
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmss_test.go
  tests/e2e/utils/network_interface_utils.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#3507 fix: remove single vm from the cache instead of removing all vms of a…
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#3509 fix: remove single vm from the cache instead of removing all vms of a…
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#3508 fix: remove single vm from the cache instead of removing all vms of a…
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#3517 Change MachinePool to use extenral cloud-provider
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test, do-not-merge/needs-kind

#3518 add OrchestrationMode for windows pool
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
Labels: needs-ok-to-test, approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none

#3504 CCM should not panic when losing leader election lease
  cmd/cloud-controller-manager/app/controllermanager.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#3520 [e2e] Fix azure-load-balancer-resource-group test
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#3527 fix: do not tag user-assigned public IP
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#3532 fix: change the expected tags in aks e2e test
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/L, release-note-none

#3541 [release-1.23] fix: change the expected tags in aks e2e test
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, kind/failing-test, size/L, release-note-none

#3543 [release-1.25] fix: change the expected tags in aks e2e test
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, kind/failing-test, size/L, release-note-none

#3542 [release-1.24] fix: change the expected tags in aks e2e test
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, kind/failing-test, size/L, release-note-none

#3544 [release-1.26] fix: change the expected tags in aks e2e test
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, kind/failing-test, size/L, release-note-none

#3549 Helm chart 1.26.6 with new patch releases
  README.md
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.26.6.tgz
  helm/repo/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#3521 [release-1.26] Enable azure-load-balancer-resource-group test
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#3574 Helm chart 1.26.7 with new patch releases
  README.md
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.26.7.tgz
  helm/repo/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#3576 chore: add a comment to address a potential bug that is introduced by orphaned ipconfigs on the lb
  pkg/provider/azure_vmss.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none

#3575 [e2e] Delete ns and client if not nil to avoid panic
  tests/e2e/auth/cred.go
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/node/vmss.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#3598 [Release 1.23] Disable provenance attestation to workaround docker buildx issue
  Makefile
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, release-note-none

#3602 [#3580] - Link to cloud provider config is broken on docs 'Deploy Cloud Controller Manager' page --fixed
  site/content/en/install/azure-ccm.md
Labels: needs-ok-to-test, approved, kind/bug, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#3586 Fix nodeAddressesChangeDetected() bug when dual-stack
  pkg/nodemanager/nodemanager.go
  pkg/nodemanager/nodemanager_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#3600 [release-1.23][e2e] Delete ns and client if not nil to avoid panic
  tests/e2e/auth/cred.go
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/node/vmss.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#3415 Prerequisite for dualstack public IP support
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  site/content/en/topics/loadbalancer.md
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#3642 [e2e] Longer timeout for WaitAutoScaleNodes()
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#3623 Deprecate numberOfProbes and adopt ProbeThreshold to address a probe issue in nrp
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#3659 [release-1.23] Deprecate numberOfProbes and adopt ProbeThreshold to address a probe issue in nrp
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#3663 Revert "[release-1.25] Removing Windows SAC images from container builds"
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#3660 [e2e] Print IP config IDs if subnet deletion fails
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing
