Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2023-10, with the labels that each got.

#4721 chore: fix typos
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssclient/interface.go
  pkg/provider/azure_vmss_test.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, size/S, release-note-none, kind/cleanup

#4714 Bump Helm chart to v1.28.1
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.28.1.tgz
  helm/repo/index.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#4722 [release-1.27]chore: fix typos
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssclient/interface.go
  pkg/provider/azure_vmss_test.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#4725 [release-1.25]chore: fix typos
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssclient/interface.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#4724 [release-1.26]chore: fix typos
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssclient/interface.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#4727 track2 sdk: Fix: nil policy in percallpolicy option
  pkg/azclient/client-gen/generator/genclientfactory_action.go
  pkg/azclient/factory_gen.go
  pkg/azclient/policy/retryonregionalendpoint/retry_endpoint_test.go
  pkg/azclient/policy/retryrepectthrottled/throttle_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#4723 [release-1.28]chore: fix typos
  pkg/azureclients/vmssclient/azure_vmssclient.go
  pkg/azureclients/vmssclient/interface.go
  pkg/provider/azure_vmss_test.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#4746 track2 sdk: update default timeout value and fix recursive panic in transport
  .github/dependabot.yml
  pkg/azclient/factory_conf.go
  pkg/azclient/go.mod
  pkg/azclient/go.sum
  pkg/azclient/utils/armbalancer/go.mod
  pkg/azclient/utils/armbalancer/go.sum
  pkg/azclient/utils/armbalancer/transport.go
  pkg/azclient/utils/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#4754 [release-1.27][CI] Test OOT credential provider
  examples/out-of-tree/credential-provider-config.yaml
  tests/e2e/auth/cred.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/consts.go
  tests/e2e/utils/container_registry_utils.go
  tests/e2e/utils/pod_utils.go
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/testing

#4779 Bumps golang.org/x/net to 0.17.0.
  go.mod
  go.sum
  pkg/azclient/configloader/go.mod
  pkg/azclient/configloader/go.sum
  pkg/azclient/go.mod
  pkg/azclient/go.sum
  vendor/golang.org/x/net/http2/Dockerfile
  vendor/golang.org/x/net/http2/Makefile
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#4777 Bumps golang.org/x/net from 0.10.0 to 0.17.0.
  go.mod
  go.sum
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/Dockerfile
  vendor/golang.org/x/net/http2/Makefile
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched.go
  vendor/golang.org/x/net/http2/writesched_roundrobin.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/tables13.0.0.go
  vendor/golang.org/x/net/idna/tables15.0.0.go
  vendor/golang.org/x/net/idna/trie.go
  vendor/golang.org/x/net/idna/trie12.0.0.go
  vendor/golang.org/x/net/idna/trie13.0.0.go
  vendor/modules.txt
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#4761 Enable Windows for credential provider pipeline
  cmd/acr-credential-provider/main.go
  examples/out-of-tree/credential-provider-config-win.yaml
  tests/e2e/auth/cred.go
  tests/e2e/e2e_test.go
  tests/e2e/utils/container_registry_utils.go
  tests/e2e/utils/pod_utils.go
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#4776 Bumps golang.org/x/net from 0.10.0 to 0.17.0.
  go.mod
  go.sum
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/Dockerfile
  vendor/golang.org/x/net/http2/Makefile
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched.go
  vendor/golang.org/x/net/http2/writesched_roundrobin.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/tables13.0.0.go
  vendor/golang.org/x/net/idna/tables15.0.0.go
  vendor/golang.org/x/net/idna/trie.go
  vendor/golang.org/x/net/idna/trie12.0.0.go
  vendor/golang.org/x/net/idna/trie13.0.0.go
  vendor/modules.txt
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#4715 fix: skip tagging route table that is not in the cluster resource group
  pkg/provider/azure_routes.go
  pkg/provider/azure_routes_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#4778 Bumps golang.org/x/net to 0.17.0.
  go.mod
  go.sum
  pkg/azureclients/v2/go.mod
  pkg/azureclients/v2/go.sum
  vendor/golang.org/x/net/http2/Dockerfile
  vendor/golang.org/x/net/http2/Makefile
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#4797 Track2 sdk: add acr client
  pkg/azclient/Makefile
  pkg/azclient/factory.go
  pkg/azclient/factory_gen.go
  pkg/azclient/factory_test.go
  pkg/azclient/go.mod
  pkg/azclient/go.sum
  pkg/azclient/mock_azclient/interface.go
  pkg/azclient/registryclient/custom.go
  pkg/azclient/registryclient/custom_test.go
  pkg/azclient/registryclient/interface.go
  pkg/azclient/registryclient/mock_registryclient/interface.go
  pkg/azclient/registryclient/registryclient_suite_test.go
  pkg/azclient/registryclient/registryclient_test.go
  pkg/azclient/registryclient/testdata/Registry.yaml
  pkg/azclient/registryclient/zz_generated_client.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note-none

#4798 report vmPowerStateUnknown when vmssVM intanceView is nil
  pkg/provider/azure.go
  pkg/provider/azure_instances.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#4803 [release-1.27]Remove stale config of dependabot in release branch.
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#4813 track2 sdk: add new fuctions for interface/virtualnetwork/vmss client
  pkg/azclient/Makefile
  pkg/azclient/interfaceclient/custom.go
  pkg/azclient/interfaceclient/interface.go
  pkg/azclient/interfaceclient/mock_interfaceclient/interface.go
  pkg/azclient/routetableclient/interface.go
  pkg/azclient/routetableclient/mock_routetableclient/interface.go
  pkg/azclient/routetableclient/routetableclient_test.go
  pkg/azclient/routetableclient/testdata/RouteTable.yaml
  pkg/azclient/routetableclient/zz_generated_client.go
  pkg/azclient/virtualmachinescalesetclient/custom.go
  pkg/azclient/virtualmachinescalesetclient/custom_test.go
  pkg/azclient/virtualmachinescalesetclient/interface.go
  pkg/azclient/virtualmachinescalesetclient/mock_virtualmachinescalesetclient/interface.go
  pkg/azclient/virtualmachinescalesetclient/testdata/VirtualMachineScaleSet.yaml
  pkg/azclient/virtualmachinescalesetclient/virtualmachinescalesetclient_test.go
  pkg/azclient/virtualmachinescalesetclient/zz_generated_client.go
  pkg/azclient/virtualnetworkclient/custom.go
  pkg/azclient/virtualnetworkclient/interface.go
  pkg/azclient/virtualnetworkclient/mock_virtualnetworkclient/interface.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note-none

#4812 Use CAAPH for credential-provider-capz template
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#4815 Replace docker commands with acr tasks
  tests/e2e/auth/cred.go
  tests/e2e/utils/container_registry_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#4822 Revert "Use CAAPH for credential-provider-capz template"
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
Labels: approved, cncf-cla: yes, do-not-merge/release-note-label-needed, size/S, do-not-merge/needs-kind

#4824 Login azure before update acr properties in e2e
  tests/e2e/auth/cred.go
  tests/e2e/utils/container_registry_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#4849 track2 sdk: add importimage function to registryclient
  pkg/azclient/registryclient/custom.go
  pkg/azclient/registryclient/custom_test.go
  pkg/azclient/registryclient/interface.go
  pkg/azclient/registryclient/testdata/Registry.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#4839 fix: refresh the load balancer object after updating backend pools to…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#4821 fix: pipName should be case-insensitive when querying pip cache
  pkg/provider/azure_publicip_repo.go
  pkg/provider/azure_publicip_repo_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#4850 track2 sdk: update test mc client test data
  pkg/azclient/managedclusterclient/testdata/ManagedCluster.yaml
  pkg/azclient/registryclient/mock_registryclient/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#4870 fix spellcheck errs
  content/en/blog/releases/v1.0.21.md
  content/en/blog/releases/v1.1.17.md
  content/en/blog/releases/v1.23.14.md
  content/en/blog/releases/v1.24.18.md
  content/en/blog/releases/v1.24.19.md
  content/en/blog/releases/v1.24.2.md
  content/en/blog/releases/v1.25.12.md
  content/en/blog/releases/v1.26.8.md
  content/en/blog/releases/v1.27.0.md
  content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#4848 fix: VM name should be obtained from NIC.VirtualMachine.ID instead of…
  pkg/provider/azure_utils.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#4862 Cherry pick #4839 and #4821 to release-1.27
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#4863 Cherry pick #4839 and #4821 to release-1.26
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#4869 docs: remove auto approval restriction
  content/en/topics/pls-integration.md
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#4864 Cherry pick #4839 and #4821 to release-1.25
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#4884 fix: VM name should be obtained from NIC.VirtualMachine.ID instead of…
  pkg/provider/azure_utils.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#4881 track2 sdk: add storage account client
  pkg/azclient/Makefile
  pkg/azclient/accountclient/accountclient_suite_test.go
  pkg/azclient/accountclient/accountclient_test.go
  pkg/azclient/accountclient/custom.go
  pkg/azclient/accountclient/custom_test.go
  pkg/azclient/accountclient/interface.go
  pkg/azclient/accountclient/mock_accountclient/interface.go
  pkg/azclient/accountclient/testdata/Account.yaml
  pkg/azclient/accountclient/zz_generated_client.go
  pkg/azclient/factory.go
  pkg/azclient/factory_gen.go
  pkg/azclient/factory_test.go
  pkg/azclient/go.mod
  pkg/azclient/go.sum
  pkg/azclient/mock_azclient/interface.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note-none

#4883 fix: VM name should be obtained from NIC.VirtualMachine.ID instead of…
  pkg/provider/azure_utils.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L
