Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2023-04, with the labels that each got.

#3720 Limit dependbot open pr limit to 1
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#3726 [IPv6] Fix CNM not properly handling IPv6 from imds LB
  pkg/provider/azure_instance_metadata.go
  pkg/provider/azure_instance_metadata_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#3737 [e2e] Add Node logs for autoscaling tests
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#3741 [release-1.24] chore: upgrade ubuntu to 22.04 for github actions
  .github/workflows/test-docs.yaml
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, release-note-none

#3742 [release-1.23] chore: upgrade ubuntu to 22.04 for github actions
  .github/workflows/test-docs.yaml
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, release-note-none

#3743 [Github action tests] Run on ubuntu-latest for trivy and doc
  .github/workflows/test-docs.yaml
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#3755 [e2e] Improve autoscaling e2e
  .pipelines/templates/autoscaling-multipool.json
  .pipelines/templates/autoscaling.json
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#3748 Add release label for prs raised by dependabot
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#3715 [IPv6] Choose correct primary IP config
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_cache_test.go
  pkg/provider/azure_vmssflex_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL

#3757 fix: update resources in batches asynchonously
  pkg/azureclients/armclient/azure_armclient.go
  pkg/azureclients/armclient/azure_armclient_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, kind/regression

#3756 chore: upgrade credentialprovider-api-version to v1
  cmd/acr-credential-provider/plugin.go
  cmd/acr-credential-provider/plugin_test.go
  pkg/credentialprovider/azure_credentials.go
  site/content/en/topics/credential-provider.md
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup

#3771 More Nodes for autoscaling tests
  .pipelines/templates/autoscaling-multipool.json
  .pipelines/templates/autoscaling.json
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#3768 chore: set default loadBalancerSKU to Standard
  pkg/provider/azure.go
  pkg/provider/azure_test.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/S, kind/cleanup

#3770 [release-1.26][IPv6] Choose correct primary IP config
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_cache_test.go
  pkg/provider/azure_vmssflex_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL

#3774 [release-1.24][IPv6] Choose correct primary IP config
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, lgtm, size/XL

#3772 [release-1.25][IPv6] Choose correct primary IP config
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_cache_test.go
  pkg/provider/azure_vmssflex_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL

#3778 bump k8s.io to 1.25.9 and golang.org/x/crypto to 0.8.0
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#3779 bump k8s.uo to 1.26.4 and golang.org/x/crypto to 0.8.0
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go
  vendor/k8s.io/apiserver/pkg/registry/rest/rest.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/ready.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/controller-manager/app/serve.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#3777 bump k8s.io dependencies to 1.24.13
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/ready.go
  vendor/k8s.io/cloud-provider/cloud.go
  vendor/k8s.io/cloud-provider/controllers/route/route_controller.go
  vendor/k8s.io/controller-manager/app/serve.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/conn.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup, release-1.24

#3791 [release-1.25]add label for release notes pr
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#3792 [release-1.24]add label for release notes pr
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#3793 [release-1.23]add label for release notes pr
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#3781 Run go lint using github actions
  .github/workflows/lint.yaml
  Makefile
  pkg/consts/helpers.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#3773 clean up old pip list optimization
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#3787 Remove shared nsg rule immediately when no destinations prefixes are left
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#3801 Add dependabot config for release-1.27
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#3808 [release-1.25] clean up old pip list optimization
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#3810 [release-1.26] clean up old pip list optimization
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#3807 [release-1.24] clean up old pip list optimization
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#3805 [e2e][Autoscaling] Use user node pool
  .pipelines/templates/autoscaling-multipool.json
  .pipelines/templates/autoscaling.json
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/utils/node_utils.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#3378 feat: support workload identity
  pkg/provider/azure.go
  pkg/provider/azure_test.go
  pkg/provider/config/azure_auth.go
  pkg/provider/config/azure_auth_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#3806 [release-1.27] rm kubetest2-aks dir
  .github/workflows/kubetest2-release.yml
  kubetest2-aks/Makefile
  kubetest2-aks/README.md
  kubetest2-aks/cluster-templates/autoscaling-e2e.json
  kubetest2-aks/cluster-templates/autoscaling-multipool.json
  kubetest2-aks/cluster-templates/autoscaling.json
  kubetest2-aks/cluster-templates/basic-lb.json
  kubetest2-aks/cluster-templates/customconfiguration-azuredisk.json
  kubetest2-aks/cluster-templates/customconfiguration-azurefile.json
  kubetest2-aks/cluster-templates/customconfiguration-cas.json
  kubetest2-aks/cluster-templates/customconfiguration-ccm.json
  kubetest2-aks/cluster-templates/customconfiguration-k8s.json
  kubetest2-aks/cluster-templates/customconfiguration.json
  kubetest2-aks/cluster-templates/slb.json
  kubetest2-aks/deployer/build.go
  kubetest2-aks/deployer/deployer.go
  kubetest2-aks/deployer/down.go
  kubetest2-aks/deployer/up.go
  kubetest2-aks/go.mod
  kubetest2-aks/go.sum
  kubetest2-aks/main.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/testing

#3811 feat: add PickRandomMatchingAccount in account search
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_managedDiskController_test.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#3815 [e2e] Fix bugs from introducing user node pool
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/node_utils.go
  tests/e2e/utils/vmss_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#3820 Remove kubetest2-release.yaml
  .github/workflows/kubetest2-release.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#3822 Use latest gcb-docker-gcloud
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing
