Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2023-05, with the labels that each got.

#3845 [release-1.25][e2e] Support dual-stack - utils
  pkg/consts/consts.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/network_utils_test.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/testing

#3846 [release-1.24][e2e] Support dual-stack - utils
  pkg/consts/consts.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/network_utils_test.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/testing

#3844 [release-1.26][e2e] Support dual-stack - utils
  pkg/consts/consts.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/node.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/azure_test_client.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/network_utils_test.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/testing

#3823 [DualStack] IPv6 PIP uses suffix only when DualStack
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/L, kind/cleanup

#3854 [Refactor] Drop RG param in getXXXID()
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#3824 Update README.md with v1.27 release branch
  README.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#3403 armclient v2: add test case for diskclient and refactor generator
  pkg/azureclients/v2/Makefile
  pkg/azureclients/v2/availabilitysetclient/interface.go
  pkg/azureclients/v2/client-gen/cmd/client-gen/main.go
  pkg/azureclients/v2/client-gen/cmd/typescaffold/type_scaffold.go
  pkg/azureclients/v2/client-gen/generator/client_gen.go
  pkg/azureclients/v2/client-gen/generator/codegenerator.go
  pkg/azureclients/v2/client-gen/generator/gencode_action.go
  pkg/azureclients/v2/client-gen/generator/genmock_action.go
  pkg/azureclients/v2/client-gen/generator/template.go
  pkg/azureclients/v2/deploymentclient/custom.go
  pkg/azureclients/v2/deploymentclient/interface.go
  pkg/azureclients/v2/diskclient/diskclient_suite_test.go
  pkg/azureclients/v2/diskclient/diskclient_test.go
  pkg/azureclients/v2/diskclient/interface.go
  pkg/azureclients/v2/diskclient/testdata/diskclient.yaml
  pkg/azureclients/v2/diskclient/zz_generated.client.go
  pkg/azureclients/v2/go.mod
  pkg/azureclients/v2/go.sum
  pkg/azureclients/v2/interfaceclient/interface.go
  pkg/azureclients/v2/interfaceclient/zz_generated.client.go
  pkg/azureclients/v2/loadbalancerclient/interface.go
  pkg/azureclients/v2/loadbalancerclient/zz_generated.client.go
  pkg/azureclients/v2/managedclusterclient/interface.go
  pkg/azureclients/v2/managedclusterclient/zz_generated.client.go
  pkg/azureclients/v2/policy/ratelimit.go
  pkg/azureclients/v2/policy/retry.go
  pkg/azureclients/v2/policy/throttle.go
  pkg/azureclients/v2/privateendpointclient/interface.go
  pkg/azureclients/v2/privateendpointclient/zz_generated.client.go
  pkg/azureclients/v2/privatelinkserviceclient/interface.go
  pkg/azureclients/v2/privatelinkserviceclient/zz_generated.client.go
  pkg/azureclients/v2/privatezoneclient/interface.go
  pkg/azureclients/v2/privatezoneclient/zz_generated.client.go
  pkg/azureclients/v2/publicipaddressclient/interface.go
  pkg/azureclients/v2/publicipaddressclient/zz_generated.client.go
  pkg/azureclients/v2/recording/counter.go
  pkg/azureclients/v2/recording/recorder.go
  pkg/azureclients/v2/recording/transport.go
  pkg/azureclients/v2/routetableclient/interface.go
  pkg/azureclients/v2/routetableclient/zz_generated.client.go
  pkg/azureclients/v2/securitygroupclient/interface.go
  pkg/azureclients/v2/securitygroupclient/zz_generated.client.go
  pkg/azureclients/v2/utils/interface.go
  pkg/azureclients/v2/utils/policy_wrapper.go
  pkg/azureclients/v2/utils/poller.go
  pkg/azureclients/v2/utils/transport.go
  pkg/azureclients/v2/virtualmachineclient/custom.go
  pkg/azureclients/v2/virtualmachineclient/interface.go
  pkg/azureclients/v2/virtualmachineclient/zz_generated.client.go
  pkg/azureclients/v2/virtualmachinescalesetclient/interface.go
  pkg/azureclients/v2/virtualmachinescalesetclient/zz_generated.client.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#3878 doc: use dl.k8s.io, not kubernetes-release bucket
  site/content/en/development/e2e/e2e-tests.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#3882 cleanup: remove PremiumV2LRS const
  pkg/consts/consts.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_managedDiskController_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#3879 [CI] Add IPv6 templates modified from release-1.9 CAPZ
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-md.yaml
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/testing

#3877 fix: the pip without tags should be user-assigned
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
  site/content/en/topics/shared-ip.md
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#3891 [release-1.25] fix: the pip without tags should be user-assigned
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
  site/content/en/topics/shared-ip.md
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#3889 [release-1.27] fix: the pip without tags should be user-assigned
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
  site/content/en/topics/shared-ip.md
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#3890 [release-1.26] fix: the pip without tags should be user-assigned
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
  site/content/en/topics/shared-ip.md
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#3892 [release-1.24] fix: the pip without tags should be user-assigned
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
  site/content/en/topics/shared-ip.md
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#3897 doc: update readme and examples for new image versions
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/S, release-note-none

#3886 track2 sdk: return error when client received 429 toomanyrequest error
  pkg/azclient/Makefile
  pkg/azclient/go.mod
  pkg/azclient/go.sum
  pkg/azclient/policy/retry.go
  pkg/azclient/recording/transport.go
  pkg/azclient/utils/options.go
  pkg/azclient/utils/tracing.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#3910 Set gcloud ver to 2023424
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#3916 track2 client: export mock interface in azclient
  pkg/azclient/availabilitysetclient/mock_availabilitysetclient/interface.go
  pkg/azclient/client-gen/generator/codegenerator.go
  pkg/azclient/client-gen/generator/genmock_action.go
  pkg/azclient/deploymentclient/mock_deploymentclient/interface.go
  pkg/azclient/diskclient/mock_diskclient/interface.go
  pkg/azclient/interfaceclient/mock_interfaceclient/interface.go
  pkg/azclient/loadbalancerclient/mock_loadbalancerclient/interface.go
  pkg/azclient/managedclusterclient/mock_managedclusterclient/interface.go
  pkg/azclient/privateendpointclient/mock_privateendpointclient/interface.go
  pkg/azclient/privatelinkserviceclient/mock_privatelinkserviceclient/interface.go
  pkg/azclient/privatezoneclient/mock_privatezoneclient/interface.go
  pkg/azclient/publicipaddressclient/mock_publicipaddressclient/interface.go
  pkg/azclient/routetableclient/mock_routetableclient/interface.go
  pkg/azclient/securitygroupclient/mock_securitygroupclient/interface.go
  pkg/azclient/virtualmachineclient/mock_virtualmachineclient/interface.go
  pkg/azclient/virtualmachinescalesetclient/mock_virtualmachinescalesetclient/interface.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#3928 chore: update docs for cross resource group nodes
  site/content/en/topics/cross-resource-group-nodes.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#3685 Allow deprecated beta topology labels to be applied for those not ready to migrate
  cmd/cloud-node-manager/app/config/config.go
  cmd/cloud-node-manager/app/nodemanager.go
  cmd/cloud-node-manager/app/options/options.go
  pkg/nodemanager/nodemanager.go
  pkg/nodemanager/nodemanager_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, kind/cleanup

#3933 doc: update pls doc
  site/content/en/topics/loadbalancer.md
  site/content/en/topics/pls-integration.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#3931 apply the custom probe configs when externalTrafficPolicy is local and PLSProxyProtocol is enabled.
  pkg/consts/helpers.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#3932 [IPv6] backend pool name should be case-insensitive
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#3940 [release-1.26] Adjust UT util functions for cherrypick without DualStack support
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#3939 [release-1.27] Adjust UT util functions for cherrypick without DualStack support
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#3948 Revert "chore: temporarily change the expected tags in aks pip tags e…
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none

#3947 track2 client: Remove unnecessary dependencies from azclient
  pkg/azclient/Makefile
  pkg/azclient/client-gen/go.mod
  pkg/azclient/client-gen/go.sum
  pkg/azclient/go.mod
  pkg/azclient/go.sum
  pkg/azclient/policy/ratelimit.go
  pkg/azclient/policy/retry.go
  pkg/azclient/utils/flowcontrol/docs.go
  pkg/azclient/utils/flowcontrol/throttle.go
  pkg/azclient/utils/flowcontrol/throttle_test.go
  pkg/azclient/utils/tracing.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#3957 [Log] Print Service name and resource basename in ReconcileService()
  pkg/provider/azure_loadbalancer.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup

#3971 chore: update docs for exclude nodes from SLB
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#3969 track2 sdk:remove apiVersion parameter
  pkg/azclient/Makefile
  pkg/azclient/availabilitysetclient/interface.go
  pkg/azclient/availabilitysetclient/zz_generated_client.go
  pkg/azclient/client-gen/cmd/typescaffold/type_scaffold.go
  pkg/azclient/client-gen/generator/template.go
  pkg/azclient/deploymentclient/interface.go
  pkg/azclient/deploymentclient/mock_deploymentclient/interface.go
  pkg/azclient/deploymentclient/zz_generated_client.go
  pkg/azclient/diskclient/interface.go
  pkg/azclient/diskclient/zz_generated_client.go
  pkg/azclient/interfaceclient/interface.go
  pkg/azclient/interfaceclient/zz_generated_client.go
  pkg/azclient/loadbalancerclient/interface.go
  pkg/azclient/loadbalancerclient/zz_generated_client.go
  pkg/azclient/managedclusterclient/interface.go
  pkg/azclient/managedclusterclient/zz_generated_client.go
  pkg/azclient/privateendpointclient/interface.go
  pkg/azclient/privateendpointclient/zz_generated_client.go
  pkg/azclient/privatelinkserviceclient/interface.go
  pkg/azclient/privatelinkserviceclient/zz_generated_client.go
  pkg/azclient/privatezoneclient/interface.go
  pkg/azclient/privatezoneclient/zz_generated_client.go
  pkg/azclient/publicipaddressclient/interface.go
  pkg/azclient/publicipaddressclient/zz_generated_client.go
  pkg/azclient/publicipprefixclient/interface.go
  pkg/azclient/publicipprefixclient/zz_generated_client.go
  pkg/azclient/readme.md
  pkg/azclient/routetableclient/interface.go
  pkg/azclient/routetableclient/zz_generated_client.go
  pkg/azclient/securitygroupclient/interface.go
  pkg/azclient/securitygroupclient/zz_generated_client.go
  pkg/azclient/snapshotclient/interface.go
  pkg/azclient/snapshotclient/mock_snapshotclient/interface.go
  pkg/azclient/snapshotclient/zz_generated_client.go
  pkg/azclient/utils/options.go
  pkg/azclient/virtualmachineclient/interface.go
  pkg/azclient/virtualmachineclient/mock_virtualmachineclient/interface.go
  pkg/azclient/virtualmachineclient/zz_generated_client.go
  pkg/azclient/virtualmachinescalesetclient/interface.go
  pkg/azclient/virtualmachinescalesetclient/zz_generated_client.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#3987 doc: update documents for allocateLoadBalancerNodePorts
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#3992 add manual dispatch for all github actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/kubetest2-release.yml
  .github/workflows/scorecards.yml
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, size/XS, release-note-none, kind/cleanup

#3995 chore: fix the typo for SLB docs
  site/content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, kind/documentation, size/XS, release-note-none

#3996 doc: deprecate --port and use --secure-port instead in readme and exa…
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#3999 track2 sdk:update mock interface for vmssvmclient
  pkg/azclient/virtualmachinescalesetvmclient/custom.go
  pkg/azclient/virtualmachinescalesetvmclient/interface.go
  pkg/azclient/virtualmachinescalesetvmclient/mock_virtualmachinescalesetvmclient/interface.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#4000 add daily fuzz test
  .github/dependabot.yml
  .github/workflows/cflite_cron.yaml
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#4009 track2 sdk: fix copyright template error in azclient package
  pkg/azclient/virtualmachinescalesetvmclient/custom.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none
