Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2023-07, with the labels that each got.

#4202 doc: fix a hyperlink error in the documentation
  content/en/install/azure-ccm.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#4184 fix: fixing kubetest autoscaling configs as well
  kubetest2-aks/cluster-templates/autoscaling-e2e.json
  kubetest2-aks/cluster-templates/autoscaling-multipool.json
  kubetest2-aks/cluster-templates/autoscaling.json
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none, kind/cleanup

#4199 [e2e] Delete Service if WaitServiceExposureAndValidateConnectivity() fails
  tests/e2e/utils/service_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#4213 docs: fix edit page url broken link
  config/_default/config.toml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#4215 doc: update docs for vmType
  content/en/install/configs.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#4216 doc: update README for document links
  README.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#4214 feat: make vmType optional
  pkg/provider/azure.go
Labels: kind/feature, release-note-action-required, approved, cncf-cla: yes, lgtm, size/XS

#4207 Support customization of numOfProbe and probeInterval when externaltrafficpolicy is local
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_healthprobe.go
  pkg/provider/azure_loadbalancer_healthprobe_test.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL

#4228 [AKS pipeline] Add a slb VMAS pipeline
  .pipelines/README.md
  .pipelines/run-vmas-e2e.yml
  .pipelines/scripts/run-e2e.sh
  .pipelines/templates/slb-vmas.json
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#4229 Use const vars to define isIPv6: false & true
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#4253 [AKS pipeline] Use new customconfig file for autoscaling-multipool
  .pipelines/scripts/run-e2e.sh
  .pipelines/templates/customconfiguration-autoscaling-multipool.json
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, kind/testing

#4252 [release-1.26] Use const vars to define isIPv6: false & true
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#4256 Update dual stack related LB doc
  content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#4217 Fix standalone VM EnsureBackendPoolDeleted
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_standard.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/consts.go
  tests/e2e/utils/node_utils.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/L, kind/testing

#4261 [e2e] Adjust exclude-from-lb test for basic-lb pipeline
  tests/e2e/network/ensureloadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#4257 feat: support sharing IP address acorss services by public IP name
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_publicip_repo.go
  pkg/provider/azure_publicip_repo_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_utils.go
  tests/e2e/network/ensureloadbalancer.go
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm

#4201 feat: support node selection for multiple standard load balancers
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm

#4277 doc: add docs for sharing pip by name
  content/en/topics/shared-ip.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#4279 [Release-1.24]fix vendor validation in ci job
  .github/workflows/codeql-analysis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#4234 Issue 4230: remove readiness check for cache exclusion
  pkg/provider/azure.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S, ok-to-test

#4282 [release-1.26] Issue 4230: remove readiness check for cache exclusion
  pkg/provider/azure.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#4283 [release-1.27] Issue 4230: remove readiness check for cache exclusion
  pkg/provider/azure.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#4284 [release-1.25] Issue 4230: remove readiness check for cache exclusion
  pkg/provider/azure.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#4267 [release-1.26][e2e] Support dual-stack - Service annotation
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/testing

#4275 [release-1.25] feat: support sharing IP address across services by public IP name
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_utils.go
  tests/e2e/network/ensureloadbalancer.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#4274 [release-1.26] feat: support sharing IP address across services by public IP name
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_utils.go
  tests/e2e/network/ensureloadbalancer.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#4271 [release-1.27] feat: support sharing IP address across services by public IP name
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_utils.go
  tests/e2e/network/ensureloadbalancer.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#4288 [release-1.25][e2e] Support dual-stack - Service annotation
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/testing

#4278 Add etag policy
  pkg/azclient/policy/etag/etag.go
  pkg/azclient/policy/etag/etag_suite_test.go
  pkg/azclient/policy/etag/etag_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#4281 [e2e] Fix updateServicePIPNames
  tests/e2e/network/ensureloadbalancer.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#4268 [aks pipeline] Refactor run-e2e.sh
  .pipelines/scripts/collect-log.sh
  .pipelines/scripts/run-e2e.sh
  tests/e2e/autoscaling/autoscaler.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#4290 [release-1.27]Support customization of numOfProbe and probeInterval when externaltr…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_healthprobe.go
  pkg/provider/azure_loadbalancer_healthprobe_test.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL

#4291 [release-1.26]Support customization of numOfProbe and probeInterval when externaltr…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_healthprobe.go
  pkg/provider/azure_loadbalancer_healthprobe_test.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL

#4292 [release-1.24] Issue 4230: remove readiness check for cache exclusion
  pkg/provider/azure.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#4293 [release-1.25] add missing e2e tests for service annotations
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#4295 [release-1.25]Support customization of numOfProbe and probeInterval when externaltr…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_healthprobe.go
  pkg/provider/azure_loadbalancer_healthprobe_test.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL

#4294 Skip unmanaged Nodes for instancesV2
  pkg/provider/azure_instances.go
  pkg/provider/azure_instances_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#4270 chore: add e2e for multiple standard load balancers
  tests/e2e/e2e_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/multiple_standard_lb.go
  tests/e2e/network/service_annotations.go
  tests/e2e/network/standard_lb.go
  tests/e2e/utils/consts.go
  tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-multi-slb.json
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#4297 Update cloud-config-vmss-multi-slb.json
  tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-multi-slb.json
Labels: approved, cncf-cla: yes, size/XS, release-note-none, kind/cleanup

#4300 [release-1.25]fix go build version in codeql job
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yaml
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#4298 [release-1.26] Skip unmanaged Nodes for instancesV2
  pkg/provider/azure_instances.go
  pkg/provider/azure_instances_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#4299 [release-1.25] Skip unmanaged Nodes for instancesV2
  pkg/provider/azure_instances.go
  pkg/provider/azure_instances_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#4304 chore: add a capz cluster template without windows node pool
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win.yaml
Labels: cncf-cla: yes, do-not-merge/release-note-label-needed, kind/cleanup

#4301 [release-1.27] Fix standalone VM EnsureBackendPoolDeleted
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_standard.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/consts.go
  tests/e2e/utils/node_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, kind/testing

#4302 [release-1.26] Fix standalone VM EnsureBackendPoolDeleted
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_standard.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/consts.go
  tests/e2e/utils/node_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, kind/testing

#4306 chore: add release script for documentation branch
  hack/generate-release-note.sh
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#4307 chore: switch to documentation branch for release notes
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#4316 Update cloud-config-vmss-multi-slb.json
  tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-multi-slb.json
Labels: approved, cncf-cla: yes, kind/failing-test, release-note-none

#4272 Fix IPv6/dual-stack EnsureBackendPoolDeleted() failure
  pkg/provider/azure_standard.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#4323 Fix typo
  content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none, ok-to-test

#4321 [release-1.26] Fix IPv6/dual-stack EnsureBackendPoolDeleted() failure
  pkg/provider/azure_standard.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, kind/testing

#4322 [release-1.27] Cherry-pick 4317 4272
  pkg/provider/azure_standard.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, kind/testing

#4320 [e2e] Use timeout for the route table test
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_routes.go
  tests/e2e/network/node.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#4332 [release-1.25] Cherry-pick 4217 4261 4272
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_standard.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/consts.go
  tests/e2e/utils/node_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, kind/testing

#4349 Use 2204 ubuntu image for linux-vmss-multiple-zones-ci-version.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#4289 fix: fix bugs regarding multiple slbs
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/multiple_standard_lb.go
  tests/e2e/utils/network_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#4376 chore: move getPrivateLinkService to pls file
  pkg/provider/azure_privatelinkservice_repo.go
  pkg/provider/azure_securitygroup_repo.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#4361 Increase service idle max timeout to 100 minutes
  pkg/provider/azure_loadbalancer.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#4381 Helm chart 1.27.6 with latest releases
  README.md
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.27.6.tgz
  helm/repo/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#4380 Support for custom health probe port(not in spec)
  pkg/provider/azure_loadbalancer_healthprobe.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#4389 Use correct quotation mark
  content/en/FAQ/known-issues/azuredisk.md
  content/en/blog/releases/v0.7.0.md
  content/en/install/azure-ccm.md
  content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#4390 Use correct quotation mark
  Dockerfile
  pkg/provider/azure.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup
