Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2023-12, with the labels that each got.

#5110 Track2: remove trytimeout in default settings and add custom options for clientFactory
  pkg/azclient/client-gen/generator/genclientfactory_action.go
  pkg/azclient/factory_gen.go
  pkg/azclient/managedclusterclient/testdata/ManagedCluster.yaml
  pkg/azclient/utils/options.go
  pkg/azclient/vaultclient/testdata/Vault.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#5078 test: update CAPZ test templates to include calico HelmChartProxy
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-md.yaml
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-md.yaml
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml
  tests/k8s-azure/manifest/cluster-api/linux-dualstack.yaml
  tests/k8s-azure/manifest/cluster-api/linux-ipv6.yaml
  tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss-multiple-zones.yaml
  tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-local.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-oot-credential-provider.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version-oot-credential-provider.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss.yaml
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool-in-tree.yaml
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#5072 Refactor: move CloudConfigType to configloader package
  go.mod
  go.sum
  pkg/provider/azure.go
  pkg/provider/azure_config.go
  pkg/provider/azure_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/configloader/config_loader.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/configloader/load.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/configloader/loader_empty.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/configloader/loader_file.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/configloader/loader_secret.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/configloader/loader_yaml.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#4975 [release-1.28] feat: Add annotation `service.beta.kubernetes.io/azure-allowed-ip-ranges`
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/loadbalancer/netip.go
  pkg/provider/loadbalancer/netip_test.go
  tests/e2e/network/network_security_group.go
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm, ok-to-test

#5123 [release-1.26] feat: Add annotation `service.beta.kubernetes.io/azure-allowed-ip-ranges`
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/loadbalancer/netip.go
  pkg/provider/loadbalancer/netip_test.go
  tests/e2e/network/network_security_group.go
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm, ok-to-test

#4974 [release-1.27] feat: Add annotation `service.beta.kubernetes.io/azure-allowed-ip-ranges`
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/loadbalancer/netip.go
  pkg/provider/loadbalancer/netip_test.go
  tests/e2e/network/network_security_group.go
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm, ok-to-test

#4996 feat: support workload identity setting in static PV mount on AKS
  go.mod
  go.sum
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#5149 cleanup: remove unused async attach functionality
  pkg/provider/azure.go
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_common_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#5042 fix: shared probe should not be removed if there are other services u…
  hack/deploy-cluster-capz.sh
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_healthprobe.go
  pkg/provider/azure_loadbalancer_healthprobe_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#5156 [e2e] Print string instead of string pointer
  tests/e2e/network/ensureloadbalancer.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/private_link_service.go
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/log.go
  tests/e2e/utils/network_utils.go
  tests/e2e/utils/service_utils.go
  tests/e2e/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#5162 track2 sdk: remove error in response in authprovider
  pkg/azclient/auth.go
  pkg/azclient/auth_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#5179 Use latest dualstack machinepool template
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#5158 chore: adding e2e test for shared health probe
  hack/deploy-cluster-capz.sh
  hack/ensure-clusterctl.sh
  tests/e2e/e2e_test.go
  tests/e2e/network/sharedhealthprobe.go
  tests/e2e/utils/consts.go
  tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-default.json
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#5193 chore: bump golang-ci version for release-1.28
  .github/workflows/lint.yaml
  .golangci.yml
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none

#5195 Refactor: expose fields of AttachDiskOptions
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_common_test.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_standard_test.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmss_test.go
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_controller_vmssflex_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#5196 Refactor: move getNodeVMSet to cloud struct
  pkg/provider/azure.go
  pkg/provider/azure_controller_common.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#5147 Refactor: initialize clientFactory
  go.sum
  pkg/provider/azure.go
  pkg/provider/azure_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/mock_azclient/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup
