Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2023-09, with the labels that each got.

#4542 Track2 sdk:Replace armbalancer with the custom one
  pkg/azclient/factory_conf.go
  pkg/azclient/go.mod
  pkg/azclient/go.sum
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note-none

#4553 [release-1.27] feat: add support for disable tcp reset
  pkg/consts/consts.go
  pkg/consts/helpers.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#4555 [release-1.25] feat: add support for disable tcp reset
  pkg/consts/consts.go
  pkg/consts/helpers.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#4554 [release-1.26] feat: add support for disable tcp reset
  pkg/consts/consts.go
  pkg/consts/helpers.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/M

#4574 track2 sdk: add retry on regional endpoint policy
  pkg/azclient/policy/retryonregionalendpoint/retry_endpoint.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#4575 fix: match account if PrivateEndpoint is not set in storage class
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none

#4568 fix: fix duplicate podCIDR allocation when node patch request fails
  pkg/nodeipam/ipam/range_allocator.go
  pkg/nodeipam/ipam/range_allocator_test.go
  pkg/util/controller/testutil/test_utils.go
  pkg/util/node/node.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#4586 Track2 sdk: enable x5c in track2 sdk
  pkg/azclient/auth.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#4596 [Doc] Replace availabilitySetNodesCacheTTLInSeconds with availabilitySetsCacheTTLInSeconds
  content/en/blog/releases/v1.28.0.md
  content/en/install/configs.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#4599 track2 sdk: Remove otel package from azclient's dependency
  .github/dependabot.yml
  pkg/azclient/go.mod
  pkg/azclient/go.sum
  pkg/azclient/trace/go.mod
  pkg/azclient/trace/go.sum
  pkg/azclient/trace/tracing.go
  pkg/azclient/utils/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#4610 [Doc] update pls doc to GA
  content/en/development/design-docs/pls-integration.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#4629 Support customizing probe config when ETP is local
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_healthprobe.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#4536 fix: check endpoint slice update after backend pool update for local service to prevent mismatch
  pkg/consts/consts.go
  pkg/nodemanager/nodemanager.go
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_healthprobe_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_local_services.go
  pkg/provider/azure_local_services_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_vmss_test.go
  tests/e2e/network/multiple_standard_lb.go
Labels: release-note, approved, cncf-cla: yes, lgtm, kind/failing-test, size/XL

#4628 [CI] AKS cluster creation longer wait
  kubetest2-aks/deployer/up.go
  tests/e2e/network/ensureloadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#4661 [release-1.27]support customizing probe config when ETP is local
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_healthprobe.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#4660 feat: add annotation to control pls creation rg
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_repo.go
  pkg/provider/azure_privatelinkservice_repo_test.go
  pkg/provider/azure_privatelinkservice_test.go
  tests/e2e/network/private_link_service.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#4673 [release-1.25]bump dependencies to k8s.io v1.25.14
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#4672 [release-1.26]support customizing probe config when ETP is local
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_healthprobe.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#4677 [release-1.26] feat: add annotation to control pls creation rg
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
  tests/e2e/network/private_link_service.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#4678 [release-1.27] feat: add annotation to control pls creation rg
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
  tests/e2e/network/private_link_service.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#4671 [release-1.25]support customizing probe config when ETP is local
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_healthprobe.go
  pkg/provider/azure_loadbalancer_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#4676 [release-1.25] feat: add annotation to control pls creation rg
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_backoff.go
  pkg/provider/azure_backoff_test.go
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/azure_wrap_test.go
  tests/e2e/network/private_link_service.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#4689 track2 sdk: rename factory interface functions
  pkg/azclient/auth_test.go
  pkg/azclient/availabilitysetclient/testdata/AvailabilitySet.yaml
  pkg/azclient/client-gen/generator/genclientfactory_action.go
  pkg/azclient/deploymentclient/testdata/Deployment.yaml
  pkg/azclient/diskclient/testdata/Disk.yaml
  pkg/azclient/factory.go
  pkg/azclient/factory_gen.go
  pkg/azclient/factory_test.go
  pkg/azclient/interfaceclient/testdata/Interface.yaml
  pkg/azclient/ipgroupclient/testdata/IPGroup.yaml
  pkg/azclient/loadbalancerclient/testdata/LoadBalancer.yaml
  pkg/azclient/managedclusterclient/testdata/ManagedCluster.yaml
  pkg/azclient/mock_azclient/interface.go
  pkg/azclient/policy/retryonregionalendpoint/retry_endpoint_test.go
  pkg/azclient/policy/retryrepectthrottled/throttle_test.go
  pkg/azclient/privateendpointclient/testdata/PrivateEndpoint.yaml
  pkg/azclient/privatelinkserviceclient/testdata/PrivateLinkService.yaml
  pkg/azclient/privatezoneclient/testdata/PrivateZone.yaml
  pkg/azclient/publicipaddressclient/testdata/PublicIPAddress.yaml
  pkg/azclient/publicipprefixclient/testdata/PublicIPPrefix.yaml
  pkg/azclient/recording/recorder.go
  pkg/azclient/routetableclient/testdata/RouteTable.yaml
  pkg/azclient/securitygroupclient/testdata/SecurityGroup.yaml
  pkg/azclient/snapshotclient/testdata/Snapshot.yaml
  pkg/azclient/subnetclient/testdata/Subnet.yaml
  pkg/azclient/testdata/auth.yaml
  pkg/azclient/virtualmachineclient/testdata/VirtualMachine.yaml
  pkg/azclient/virtualmachinescalesetclient/testdata/VirtualMachineScaleSet.yaml
  pkg/azclient/virtualmachinescalesetvmclient/testdata/VirtualMachineScaleSetVM.yaml
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#4694 doc: release v1.28.1, v1.27.9, v1.26.15 and v1.25.19
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none

#4695 Update pls-integration.md
  content/en/topics/pls-integration.md
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none
