Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2024-12, with the labels that each got.

#7705 Track2 sdk:add update function for account client
  pkg/azclient/accountclient/custom.go
  pkg/azclient/accountclient/custom_test.go
  pkg/azclient/accountclient/interface.go
  pkg/azclient/accountclient/testdata/Account.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#7714 Chores: move lockmap to util package
  pkg/provider/azure.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_storageaccount_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmssflex.go
  pkg/util/lockmap/lockmap.go
  pkg/util/lockmap/lockmap_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#7723 fix: cloud provider should only generate userAgent if it's not provided
  pkg/provider/azure.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#7750 fix: revert to go1.22 windows filesystem stdlib behavior building with go 1.23
  go.mod
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#7719 Chores: migrate storage package to track2 sdk
  LICENSES/vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/cache/LICENSE
  go.mod
  go.sum
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_utils.go
  pkg/provider/storage/azure_storageaccount.go
  pkg/provider/storage/azure_storageaccount_test.go
  pkg/provider/storage/consts.go
  pkg/provider/storage/fileservice/fileservice_repo.go
  pkg/provider/storage/fileservice/fileservice_repo_test.go
  pkg/provider/storage/fileservice/mock_fileservice/interface.go
  pkg/provider/subnet/subnet.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/cache/LICENSE
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/cache/azure_cache.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/cache/deepcopy.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/cache/doc.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#7665 Update vendor license for master
  go.sum
  pkg/provider/storage/azure_storageaccount.go
Labels: approved, cncf-cla: yes, size/M, release-note-none, kind/cleanup

#7766 Track2 sdk: add backendpool client
  pkg/azclient/Makefile
  pkg/azclient/backendaddresspoolclient/backendaddresspoolclient_suite_test.go
  pkg/azclient/backendaddresspoolclient/backendaddresspoolclient_test.go
  pkg/azclient/backendaddresspoolclient/custom_test.go
  pkg/azclient/backendaddresspoolclient/interface.go
  pkg/azclient/backendaddresspoolclient/interface_gomock.go
  pkg/azclient/backendaddresspoolclient/mock_backendaddresspoolclient/interface.go
  pkg/azclient/backendaddresspoolclient/testdata/BackendAddressPool.yaml
  pkg/azclient/backendaddresspoolclient/zz_generated_client.go
  pkg/azclient/factory.go
  pkg/azclient/factory_gen.go
  pkg/azclient/factory_test.go
  pkg/azclient/mock_azclient/interface.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#7768 Chores:remove unused storage client
  pkg/azureclients/blobclient/azure_blobclient.go
  pkg/azureclients/blobclient/azure_blobclient_test.go
  pkg/azureclients/blobclient/doc.go
  pkg/azureclients/blobclient/interface.go
  pkg/azureclients/blobclient/mockblobclient/doc.go
  pkg/azureclients/blobclient/mockblobclient/interface.go
  pkg/azureclients/fileclient/azure_fileclient.go
  pkg/azureclients/fileclient/doc.go
  pkg/azureclients/fileclient/interface.go
  pkg/azureclients/fileclient/mockfileclient/doc.go
  pkg/azureclients/fileclient/mockfileclient/interface.go
  pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
  pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient_test.go
  pkg/azureclients/privatednszonegroupclient/interface.go
  pkg/azureclients/privatednszonegroupclient/mockprivatednszonegroupclient/doc.go
  pkg/azureclients/privatednszonegroupclient/mockprivatednszonegroupclient/interface.go
  pkg/azureclients/privateendpointclient/azure_privateendpointclient.go
  pkg/azureclients/privateendpointclient/azure_privateendpointclient_test.go
  pkg/azureclients/privateendpointclient/doc.go
  pkg/azureclients/privateendpointclient/interface.go
  pkg/azureclients/privateendpointclient/mockprivateendpointclient/doc.go
  pkg/azureclients/privateendpointclient/mockprivateendpointclient/interface.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
  pkg/azureclients/storageaccountclient/azure_storageaccountclient_test.go
  pkg/azureclients/storageaccountclient/doc.go
  pkg/azureclients/storageaccountclient/interface.go
  pkg/azureclients/storageaccountclient/mockstorageaccountclient/doc.go
  pkg/azureclients/storageaccountclient/mockstorageaccountclient/interface.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/accounts.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/blobcontainers.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/blobinventorypolicies.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/blobservices.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/deletedaccounts.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/encryptionscopes.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/enums.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/fileservices.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/fileshares.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/localusers.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/managementpolicies.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/objectreplicationpolicies.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/privateendpointconnections.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/privatelinkresources.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/queue.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/queueservices.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/skus.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/table.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/tableservices.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/usages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2021-09-01/storage/version.go
  vendor/modules.txt
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#7769 Chores:remove track1 pls client from codebase
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
  pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go
  pkg/azureclients/privatelinkserviceclient/doc.go
  pkg/azureclients/privatelinkserviceclient/interface.go
  pkg/azureclients/privatelinkserviceclient/mockprivatelinkserviceclient/doc.go
  pkg/azureclients/privatelinkserviceclient/mockprivatelinkserviceclient/interface.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#7771 chore: drop use of winreadlinkvolume godebug option on Windows node
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#7767 Track2 sdk: add GetVirtualMachineScaleSetPublicIPAddress to pip client
  pkg/azclient/publicipaddressclient/interface.go
  pkg/azclient/publicipaddressclient/mock_publicipaddressclient/interface.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#7784 Track2 sdk: fetch acr login server and storage suffix from env/arm metadata service
  pkg/azclient/arm_conf.go
  pkg/azclient/backendaddresspoolclient/custom_test.go
  pkg/azclient/client-gen/generator/clientfactory.go
  pkg/azclient/cloud.go
  pkg/azclient/cloud_test.go
  pkg/azclient/factory_gen.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#7823 Track2 sdk: fetch and override env config from metadata service and env files
  pkg/azclient/arm_conf.go
  pkg/azclient/auth.go
  pkg/azclient/client-gen/generator/clientfactory.go
  pkg/azclient/cloud.go
  pkg/azclient/cloud_test.go
  pkg/azclient/factory_conf.go
  pkg/azclient/factory_gen.go
  pkg/azclient/factory_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none

#7835 Chores: init sub repo in storage account package
  pkg/provider/storage/azure_storageaccount.go
  pkg/provider/storage/azure_storageaccount_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#7855 Track2 sdk:add ListVmssFlexVMsWithOnlyInstanceView and ListVmssFlexVMsWithOnlyInstanceView and bump armnetwork
  pkg/azclient/accountclient/testdata/Account.yaml
  pkg/azclient/availabilitysetclient/testdata/AvailabilitySet.yaml
  pkg/azclient/backendaddresspoolclient/testdata/BackendAddressPool.yaml
  pkg/azclient/blobcontainerclient/testdata/BlobContainer.yaml
  pkg/azclient/blobservicepropertiesclient/testdata/BlobServiceProperties.yaml
  pkg/azclient/deploymentclient/testdata/Deployment.yaml
  pkg/azclient/diskclient/testdata/Disk.yaml
  pkg/azclient/fileservicepropertiesclient/testdata/FileServiceProperties.yaml
  pkg/azclient/fileshareclient/testdata/FileShare.yaml
  pkg/azclient/identityclient/testdata/Identity.yaml
  pkg/azclient/interfaceclient/testdata/Interface.yaml
  pkg/azclient/ipgroupclient/testdata/IPGroup.yaml
  pkg/azclient/loadbalancerclient/testdata/LoadBalancer.yaml
  pkg/azclient/managedclusterclient/testdata/ManagedCluster.yaml
  pkg/azclient/privatednszonegroupclient/testdata/PrivateDNSZoneGroup.yaml
  pkg/azclient/privateendpointclient/testdata/PrivateEndpoint.yaml
  pkg/azclient/privatelinkserviceclient/testdata/PrivateLinkService.yaml
  pkg/azclient/privatezoneclient/testdata/PrivateZone.yaml
  pkg/azclient/providerclient/testdata/Provider.yaml
  pkg/azclient/publicipaddressclient/testdata/PublicIPAddress.yaml
  pkg/azclient/publicipprefixclient/testdata/PublicIPPrefix.yaml
  pkg/azclient/registryclient/testdata/Registry.yaml
  pkg/azclient/resourcegroupclient/testdata/ResourceGroup.yaml
  pkg/azclient/roledefinitionclient/testdata/RoleDefinition.yaml
  pkg/azclient/routetableclient/testdata/RouteTable.yaml
  pkg/azclient/secretclient/testdata/Secret.yaml
  pkg/azclient/securitygroupclient/testdata/SecurityGroup.yaml
  pkg/azclient/snapshotclient/testdata/Snapshot.yaml
  pkg/azclient/sshpublickeyresourceclient/testdata/SSHPublicKeyResource.yaml
  pkg/azclient/subnetclient/testdata/Subnet.yaml
  pkg/azclient/vaultclient/testdata/Vault.yaml
  pkg/azclient/virtualmachineclient/custom.go
  pkg/azclient/virtualmachineclient/custom_test.go
  pkg/azclient/virtualmachineclient/interface.go
  pkg/azclient/virtualmachineclient/mock_virtualmachineclient/interface.go
  pkg/azclient/virtualmachineclient/testdata/VirtualMachine.yaml
  pkg/azclient/virtualmachinescalesetclient/testdata/VirtualMachineScaleSet.yaml
  pkg/azclient/virtualmachinescalesetvmclient/testdata/VirtualMachineScaleSetVM.yaml
  pkg/azclient/virtualnetworkclient/testdata/VirtualNetwork.yaml
  pkg/azclient/virtualnetworklinkclient/testdata/VirtualNetworkLink.yaml
Labels: size/XXL, kind/feature, approved, cncf-cla: yes, lgtm, release-note-none

#7880 Track2 sdk: add list function to fileshareclient
  pkg/azclient/fileshareclient/custom.go
  pkg/azclient/fileshareclient/custom_test.go
  pkg/azclient/fileshareclient/interface.go
  pkg/azclient/fileshareclient/mock_fileshareclient/interface.go
  pkg/azclient/fileshareclient/testdata/FileShare.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#7879 feat: add privateDNSZoneName option in AccountOptions
  pkg/provider/storage/azure_storageaccount.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note-none

#7867 cleanup: updateCache function
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_standard_test.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_vmss_cache.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#7888 Track2 sdk: add filter parameter in list function of fileshare client
  pkg/azclient/fileshareclient/custom.go
  pkg/azclient/fileshareclient/custom_test.go
  pkg/azclient/fileshareclient/interface.go
  pkg/azclient/fileshareclient/mock_fileshareclient/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#7694 Update vendor license for release-1.28
  go.sum
Labels: approved, cncf-cla: yes, size/L, release-note-none, kind/cleanup

#7905 chore: bump depdencies for kubetest2
  kubetest2-aks/go.mod
  kubetest2-aks/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#7904 chore: bump depdencies for health-probe-proxy
  health-probe-proxy/go.mod
  health-probe-proxy/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#7854 fix empty string NSG's DestinationAddressPrefix
  pkg/provider/securitygroup/securityrule.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS, ok-to-test

#7916 Track2 sdk:add expand param in get function of fileshare client
  pkg/azclient/fileshareclient/fileshareclient_test.go
  pkg/azclient/fileshareclient/interface.go
  pkg/azclient/fileshareclient/mock_fileshareclient/interface.go
  pkg/azclient/fileshareclient/zz_generated_client.go
Labels: kind/feature, approved, cncf-cla: yes, size/S, release-note-none
