Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2024-01, with the labels that each got.

#5198 Refactor: add mock for vmset
  pkg/provider/mock_provider/azure_vmsets.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#5201 [CI] Remove 2 unused Github action pipelines
  .github/workflows/cflite_cron.yaml
  .github/workflows/kubetest2-release.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#5200 Track2 sdk: support list/get instanceview in vm/vmssvm client
  pkg/azclient/recording/recorder.go
  pkg/azclient/virtualmachineclient/custom.go
  pkg/azclient/virtualmachineclient/custom_test.go
  pkg/azclient/virtualmachineclient/interface.go
  pkg/azclient/virtualmachineclient/testdata/VirtualMachine.yaml
  pkg/azclient/virtualmachinescalesetclient/testdata/VirtualMachineScaleSet.yaml
  pkg/azclient/virtualmachinescalesetvmclient/custom.go
  pkg/azclient/virtualmachinescalesetvmclient/custom_test.go
  pkg/azclient/virtualmachinescalesetvmclient/interface.go
  pkg/azclient/virtualmachinescalesetvmclient/testdata/VirtualMachineScaleSetVM.yaml
Labels: size/XXL, kind/feature, approved, cncf-cla: yes, lgtm, release-note-none

#5203 [CI] Use ACR for access-tokens image
  tests/kubemark/configs/access-tokens/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#5214 Track2 sdk: expose async update function in vm/vmssvm client
  pkg/azclient/virtualmachineclient/interface.go
  pkg/azclient/virtualmachinescalesetvmclient/custom.go
  pkg/azclient/virtualmachinescalesetvmclient/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#5164 Refine LoadBalancer service access control and consolidating security-rules
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_accesscontrol_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/loadbalancer/configuration.go
  pkg/provider/loadbalancer/configuration_test.go
  pkg/provider/loadbalancer/fnutil/map.go
  pkg/provider/loadbalancer/fnutil/slice.go
  pkg/provider/loadbalancer/iputil/addr.go
  pkg/provider/loadbalancer/iputil/addr_test.go
  pkg/provider/loadbalancer/iputil/family.go
  pkg/provider/loadbalancer/iputil/family_test.go
  pkg/provider/loadbalancer/iputil/prefix.go
  pkg/provider/loadbalancer/iputil/prefix_test.go
  pkg/provider/loadbalancer/netip_test.go
  pkg/provider/loadbalancer/securitygroup/securitygroup.go
  pkg/provider/loadbalancer/securitygroup/securitygroup_test.go
  pkg/provider/loadbalancer/testutil/assert.go
  pkg/provider/loadbalancer/testutil/clone.go
  pkg/provider/loadbalancer/testutil/fixture/azure.go
  pkg/provider/loadbalancer/testutil/fixture/azure_loadbalancer.go
  pkg/provider/loadbalancer/testutil/fixture/azure_securitygroup.go
  pkg/provider/loadbalancer/testutil/fixture/fixture.go
  pkg/provider/loadbalancer/testutil/fixture/kubernetes.go
  tests/e2e/network/network_security_group.go
  tests/e2e/network/service_annotations.go
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm, ok-to-test

#5221 Track2 sdk: switch to go.uber.org/mock and update mock impl
  pkg/azclient/Makefile
  pkg/azclient/accountclient/mock_accountclient/interface.go
  pkg/azclient/availabilitysetclient/mock_availabilitysetclient/interface.go
  pkg/azclient/blobcontainerclient/mock_blobcontainerclient/interface.go
  pkg/azclient/blobservicepropertiesclient/mock_blobservicepropertiesclient/interface.go
  pkg/azclient/client-gen/generator/codegenerator.go
  pkg/azclient/client-gen/generator/genmock_action.go
  pkg/azclient/deploymentclient/mock_deploymentclient/interface.go
  pkg/azclient/diskclient/mock_diskclient/interface.go
  pkg/azclient/fileshareclient/mock_fileshareclient/interface.go
  pkg/azclient/go.mod
  pkg/azclient/go.sum
  pkg/azclient/interfaceclient/mock_interfaceclient/interface.go
  pkg/azclient/ipgroupclient/mock_ipgroupclient/interface.go
  pkg/azclient/loadbalancerclient/mock_loadbalancerclient/interface.go
  pkg/azclient/managedclusterclient/mock_managedclusterclient/interface.go
  pkg/azclient/mock_azclient/interface.go
  pkg/azclient/privateendpointclient/mock_privateendpointclient/interface.go
  pkg/azclient/privatelinkserviceclient/mock_privatelinkserviceclient/interface.go
  pkg/azclient/privatezoneclient/mock_privatezoneclient/interface.go
  pkg/azclient/providerclient/mock_providerclient/interface.go
  pkg/azclient/publicipaddressclient/mock_publicipaddressclient/interface.go
  pkg/azclient/publicipprefixclient/mock_publicipprefixclient/interface.go
  pkg/azclient/registryclient/mock_registryclient/interface.go
  pkg/azclient/resourcegroupclient/mock_resourcegroupclient/interface.go
  pkg/azclient/routetableclient/mock_routetableclient/interface.go
  pkg/azclient/secretclient/mock_secretclient/interface.go
  pkg/azclient/securitygroupclient/mock_securitygroupclient/interface.go
  pkg/azclient/snapshotclient/mock_snapshotclient/interface.go
  pkg/azclient/sshpublickeyresourceclient/mock_sshpublickeyresourceclient/interface.go
  pkg/azclient/subnetclient/mock_subnetclient/interface.go
  pkg/azclient/utils/armbalancer/host_scoped_transport_test.go
  pkg/azclient/utils/armbalancer/mock/interface.go
  pkg/azclient/utils/armbalancer/transport_pool_test.go
  pkg/azclient/vaultclient/mock_vaultclient/interface.go
  pkg/azclient/virtualmachineclient/mock_virtualmachineclient/interface.go
  pkg/azclient/virtualmachinescalesetclient/mock_virtualmachinescalesetclient/interface.go
  pkg/azclient/virtualmachinescalesetvmclient/mock_virtualmachinescalesetvmclient/interface.go
  pkg/azclient/virtualnetworkclient/mock_virtualnetworkclient/interface.go
  pkg/azclient/virtualnetworklinkclient/mock_virtualnetworklinkclient/interface.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#5219 Truncate lengthy PIP name
  pkg/consts/consts.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#5220 Use MCR images for ones in kubemark
  tests/kubemark/configs/density/deployment.yaml
  tests/kubemark/configs/density/legacy/rc.yaml
  tests/kubemark/configs/experimental/storage/pod-startup/volume-types/configmap/deployment_with_configmap.yaml
  tests/kubemark/configs/experimental/storage/pod-startup/volume-types/downwardapi/deployment_with_downwardapi.yaml
  tests/kubemark/configs/experimental/storage/pod-startup/volume-types/emptydir/deployment_with_emptydir.yaml
  tests/kubemark/configs/experimental/storage/pod-startup/volume-types/persistentvolume/deployment_with_pvc.yaml
  tests/kubemark/configs/experimental/storage/pod-startup/volume-types/secret/deployment_with_secret.yaml
  tests/kubemark/configs/l4ilb/dep.yaml
  tests/kubemark/configs/load/config.yaml
  tests/kubemark/configs/load/daemonset.yaml
  tests/kubemark/configs/load/deployment.yaml
  tests/kubemark/configs/load/experimental-config.yaml
  tests/kubemark/configs/load/job.yaml
  tests/kubemark/configs/load/legacy/rc.yaml
  tests/kubemark/configs/load/simple-deployment.yaml
  tests/kubemark/configs/load/statefulset.yaml
  tests/kubemark/configs/node-throughput/config.yaml
  tests/kubemark/configs/node-throughput/windows_override.yaml
  tests/kubemark/templates/hollow-node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#5223 [CI] Remove identity in mp dualstack template
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#5232 [CI] Bump 1.27 golangci-lint
  .github/workflows/lint.yaml
  .golangci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#5225 fix: The case of load balancer name should be ignored when determing …
  kubetest2-aks/go.mod
  pkg/provider/azure_standard.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#5239 Bump kubetest2 pipeline GoTool Go version
  .pipelines/ccm-image.yml
  .pipelines/cnm-image.yml
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
  .pipelines/run-basic-lb-e2e.yml
  .pipelines/run-vmas-e2e.yml
  kubetest2-aks/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#5236 [CI] Bump 1.25 golangci-lint
  .github/workflows/lint.yaml
  .golangci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#5233 [CI] Bump 1.26 golangci-lint
  .github/workflows/lint.yaml
  .golangci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#5247 Bump kubetest2 pipeline GoTool Go version
  .pipelines/ccm-image.yml
  .pipelines/cnm-image.yml
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
  .pipelines/run-basic-lb-e2e.yml
  .pipelines/run-vmas-e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#5249 Bump kubetest2 pipeline GoTool Go version
  .pipelines/ccm-image.yml
  .pipelines/cnm-image.yml
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
  .pipelines/run-basic-lb-e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#5157 Cherry picks of #4891 and #5042 against release-1.28
  .github/workflows/trivy.yaml
  go.mod
  go.sum
  hack/deploy-cluster-capz.sh
  pkg/consts/consts.go
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_healthprobe.go
  pkg/provider/azure_loadbalancer_healthprobe_test.go
  pkg/provider/azure_loadbalancer_repo.go
  pkg/provider/azure_loadbalancer_repo_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_wrap.go
  vendor/modules.txt
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#5248 Bump kubetest2 pipeline GoTool Go version
  .pipelines/ccm-image.yml
  .pipelines/cnm-image.yml
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
  .pipelines/run-basic-lb-e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#5252 Bump kubetest2 pipeline GoTool Go version
  .pipelines/ccm-image.yml
  .pipelines/cnm-image.yml
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
  .pipelines/run-basic-lb-e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#5244 fix: The case of load balancer name should be ignored when determing …
  pkg/provider/azure_standard.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#5180 feat: Add a cloud-node-manager sidecar container called health-probe-proxy to transfer the traff…
  hack/deploy-cluster-capz.sh
  health-probe-proxy/Dockerfile
  health-probe-proxy/Makefile
  health-probe-proxy/README.md
  health-probe-proxy/example.yaml
  health-probe-proxy/go.mod
  health-probe-proxy/go.sum
  health-probe-proxy/main.go
  health-probe-proxy/windows.Dockerfile
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/README.md
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/cloud-provider-azure/values.yaml
  helm/repo/cloud-provider-azure-1.28.5.tgz
  helm/repo/index.yaml
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool-in-tree.yaml
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm

#5266 fix: azure_loadbalancer.go: don't use service.Name, when service is nil
  pkg/provider/azure_loadbalancer.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#5246 fix: The case of load balancer name should be ignored when determing …
  go.mod
  go.sum
  pkg/provider/azure_standard.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  vendor/modules.txt
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#5256 [release-1.26] Truncate lengthy PIP name
  pkg/consts/consts.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, size/M

#5257 [release-1.25] Truncate lengthy PIP name
  pkg/consts/consts.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, size/M

#5264 feat: Add a cloud-node-manager sidecar container called health-probe-proxy to transfer the traff…
  hack/deploy-cluster-capz.sh
  health-probe-proxy/Dockerfile
  health-probe-proxy/Makefile
  health-probe-proxy/README.md
  health-probe-proxy/example.yaml
  health-probe-proxy/go.mod
  health-probe-proxy/go.sum
  health-probe-proxy/main.go
  health-probe-proxy/windows.Dockerfile
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/README.md
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/cloud-provider-azure/values.yaml
  helm/repo/cloud-provider-azure-1.28.5.tgz
  helm/repo/index.yaml
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#5277 chore: upgrade credentialprovider-api-version to v1
  cmd/acr-credential-provider/plugin.go
  cmd/acr-credential-provider/plugin_test.go
  pkg/credentialprovider/azure_credentials.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#5272 Refactor:remove managed disk controller
  pkg/provider/azure.go
  pkg/provider/azure_controller_common.go
  pkg/provider/azure_controller_common_test.go
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmss_test.go
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_controller_vmssflex_test.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_managedDiskController.go
  pkg/provider/azure_managedDiskController_test.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmss_cache_test.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_cache_test.go
  pkg/provider/azure_vmssflex_test.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#5281 fix: [multi-slb] Put the service in the load balancer that has no lab…
  hack/deploy-cluster-capz.sh
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_repo.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_utils.go
  tests/e2e/network/multiple_standard_lb.go
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#5124 [release-1.25] feat: Add annotation `service.beta.kubernetes.io/azure-allowed-ip-ranges`
  pkg/consts/consts.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/loadbalancer/netip.go
  pkg/provider/loadbalancer/netip_test.go
  tests/e2e/network/network_security_group.go
Labels: size/XXL, release-note, kind/feature, cncf-cla: yes, ok-to-test

#5043 doc: enrich doc for shared slb probe
  content/en/topics/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#5291 doc: update documents for DisableAzureStackCloud
  content/en/install/configs.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#5289 fix: [multi-slb] Put the service in the load balancer that has no lab…
  hack/deploy-cluster-capz.sh
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_repo.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_utils.go
  tests/e2e/network/multiple_standard_lb.go
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#5290 chore: pin gcr.io/distroless/static to a hash value
  .github/workflows/trivy.yaml
  health-probe-proxy/Dockerfile
  pkg/azclient/client-gen/go.mod
  pkg/azclient/client-gen/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#5292 Refactor: migrate getdatadisk to track2 api
  pkg/provider/azure_controller_standard.go
  pkg/provider/azure_controller_standard_test.go
  pkg/provider/azure_controller_vmss.go
  pkg/provider/azure_controller_vmss_test.go
  pkg/provider/azure_controller_vmssflex.go
  pkg/provider/azure_controller_vmssflex_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  pkg/provider/azure_vmsets.go
  pkg/provider/mock_provider/azure_vmsets.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#5293 chore: pin gcr.io/distroless/static to a hash value
  .github/workflows/trivy.yaml
  health-probe-proxy/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#5299 Refactor: add patch to diskclient and add multi-sub support for snapshotclient
  pkg/azclient/diskclient/custom.go
  pkg/azclient/diskclient/custom_test.go
  pkg/azclient/diskclient/interface.go
  pkg/azclient/diskclient/mock_diskclient/interface.go
  pkg/azclient/diskclient/testdata/Disk.yaml
  pkg/azclient/factory.go
  pkg/azclient/factory_gen.go
  pkg/azclient/mock_azclient/interface.go
  pkg/azclient/snapshotclient/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#5333 fix(kubetest2-aks): customized flags should start with --
  .pipelines/templates/customconfiguration-autoscaling-multipool.json
  .pipelines/templates/customconfiguration-autoscaling.json
  .pipelines/templates/customconfiguration.json
  kubetest2-aks/cluster-templates/customconfiguration-ccm.json
  kubetest2-aks/cluster-templates/customconfiguration.json
  kubetest2-aks/deployer/up.go
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#5328 Remove feature gate MixedProtocolLBService
  tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss-multiple-zones.yaml
  tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss.yaml
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
  tests/k8s-azure/manifest/linux-vmss-basic-lb.json
  tests/k8s-azure/manifest/linux-vmss.json
  tests/k8s-azure/manifest/linux.json
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#5335 [release-1.29] Remove kubetest2 path
  kubetest2-aks/Makefile
  kubetest2-aks/README.md
  kubetest2-aks/cluster-templates/autoscaling-e2e.json
  kubetest2-aks/cluster-templates/autoscaling-multipool.json
  kubetest2-aks/cluster-templates/autoscaling.json
  kubetest2-aks/cluster-templates/basic-lb.json
  kubetest2-aks/cluster-templates/customconfiguration-azuredisk.json
  kubetest2-aks/cluster-templates/customconfiguration-azurefile.json
  kubetest2-aks/cluster-templates/customconfiguration-cas.json
  kubetest2-aks/cluster-templates/customconfiguration-ccm.json
  kubetest2-aks/cluster-templates/customconfiguration-k8s.json
  kubetest2-aks/cluster-templates/customconfiguration.json
  kubetest2-aks/cluster-templates/slb.json
  kubetest2-aks/deployer/build.go
  kubetest2-aks/deployer/deployer.go
  kubetest2-aks/deployer/down.go
  kubetest2-aks/deployer/up.go
  kubetest2-aks/go.mod
  kubetest2-aks/go.sum
  kubetest2-aks/main.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/testing

#5334 [release-1.27]fix(kubetest2-aks): customized flags should start with --
  .pipelines/templates/customconfiguration-autoscaling.json
  .pipelines/templates/customconfiguration-k8s.json
  .pipelines/templates/customconfiguration.json
Labels: needs-ok-to-test, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#5338 [release-1.29]fix(kubetest2-aks): customized flags should start with --
  .pipelines/templates/customconfiguration-autoscaling-multipool.json
  .pipelines/templates/customconfiguration-autoscaling.json
  .pipelines/templates/customconfiguration-k8s.json
  .pipelines/templates/customconfiguration.json
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#5337 [release-1.28]fix(kubetest2-aks): customized flags should start with --
  .pipelines/templates/customconfiguration-autoscaling-multipool.json
  .pipelines/templates/customconfiguration-autoscaling.json
  .pipelines/templates/customconfiguration-k8s.json
  .pipelines/templates/customconfiguration.json
Labels: needs-ok-to-test, cncf-cla: yes, size/M, release-note-none, kind/testing

#5336 [relase-1.26]fix(kubetest2-aks): customized flags should start with --
  .pipelines/templates/customconfiguration-k8s.json
  .pipelines/templates/customconfiguration.json
Labels: needs-ok-to-test, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#5342 chore(test): use differentiate component image tags
  .pipelines/scripts/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test, kind/testing

#5344 Remove --azure-container-registry-config in templates
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-oot-credential-provider.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version-oot-credential-provider.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#5325 fix: Minor bugs in deploy-cluster-capz.sh
  hack/deploy-cluster-capz.sh
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#5317 doc: Release v1.29.0.
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#5346 doc: update documents for availability zone
  content/en/blog/releases/v1.25.24.md
  content/en/blog/releases/v1.26.19.md
  content/en/blog/releases/v1.27.13.md
  content/en/blog/releases/v1.28.5.md
  content/en/blog/releases/v1.29.0.md
  content/en/topics/availability-zones.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#5345 chore: Refactor deploy-cluster-capz.sh and update heath-probe-proxy image
  .gitignore
  hack/deploy-cluster-capz.sh
  hack/ensure-clusterctl.sh
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/values.yaml
  helm/repo/cloud-provider-azure-1.29.0.tgz
  helm/repo/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup
