Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2024-07, with the labels that each got.

#6543 [release-1.28][e2e] Replace dockerhub with MCR for nginx image
  tests/e2e/utils/container_registry_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#6544 [release-1.27][e2e] Replace dockerhub with MCR for nginx image
  tests/e2e/utils/container_registry_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#6542 [release-1.29][e2e] Replace dockerhub with MCR for nginx image
  tests/e2e/utils/container_registry_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#6541 [release-1.30][e2e] Replace dockerhub with MCR for nginx image
  tests/e2e/utils/container_registry_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#6511 [release-1.28] fix: ignore Windows 2019 in ensureVMSSInPool for IPv6 backend pools only
  pkg/consts/consts.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, size/L

#6510 [release-1.27] fix: ignore Windows 2019 in ensureVMSSInPool for IPv6 backend pools only
  pkg/consts/consts.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#6552 chore: Migrate cluster deployment script to workload identity
  Makefile
  hack/delete-workload-cluster.sh
  hack/deploy-cluster.sh
  hack/deploy-workload-cluster.sh
  hack/ensure-clusterctl.sh
  tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
Labels: approved, cncf-cla: yes, size/L, release-note-none, kind/cleanup

#6553 doc: Enrich deploy-cluster.md
  content/en/development/deploy-cluster.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/M, release-note-none

#6564 fix: add getFileServicePropertiesCache to fix throttling issue
  pkg/provider/azure.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#6565 fix: not listing all accounts by default
  pkg/provider/azure_storageaccount.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#6563 doc: Update readme and example with latest images
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/L, release-note-none

#6578 fix: return error when GetServiceProperties fails in account search
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#6584 Add expire early credential wrapper
  pkg/azclient/armauth/expire_early_wrapper.go
  pkg/azclient/armauth/expire_early_wrapper_test.go
  pkg/azclient/armauth/token_credential_mock_test.go
  pkg/azclient/auth.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none

#6587 Update credential-provider.md
  content/en/topics/credential-provider.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none, kind/cleanup

#6601 chore: support PEM format cert for service principal + cert auth
  pkg/provider/config/azure_auth.go
  pkg/provider/config/azure_auth_test.go
  pkg/provider/config/testdata/testmultipublickey.pem
  pkg/provider/config/testdata/testnopublickey.pem
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#6558 Update Helm chart for v1.30.4 and other patch releases
  README.md
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.30.4.tgz
  helm/repo/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#6622 test: enable federated identity test profile
  tests/e2e/utils/azure_auth.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, release-note-none

#6644 chore: Support ginkgo failFast for e2e debugging
  tests/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note-none

#6654 [azclient] Add metrics
  pkg/azclient/accountclient/zz_generated_client.go
  pkg/azclient/armauth/token_credential_mock_test.go
  pkg/azclient/availabilitysetclient/zz_generated_client.go
  pkg/azclient/blobcontainerclient/zz_generated_client.go
  pkg/azclient/client-gen/generator/gencode_action.go
  pkg/azclient/client-gen/generator/template.go
  pkg/azclient/client-gen/go.mod
  pkg/azclient/deploymentclient/zz_generated_client.go
  pkg/azclient/diskclient/zz_generated_client.go
  pkg/azclient/fileshareclient/zz_generated_client.go
  pkg/azclient/go.mod
  pkg/azclient/go.sum
  pkg/azclient/interfaceclient/zz_generated_client.go
  pkg/azclient/ipgroupclient/zz_generated_client.go
  pkg/azclient/loadbalancerclient/zz_generated_client.go
  pkg/azclient/managedclusterclient/zz_generated_client.go
  pkg/azclient/metrics/metrics.go
  pkg/azclient/policy/ratelimit/ratelimit.go
  pkg/azclient/policy/retryrepectthrottled/throttle.go
  pkg/azclient/privateendpointclient/zz_generated_client.go
  pkg/azclient/privatelinkserviceclient/zz_generated_client.go
  pkg/azclient/privatezoneclient/zz_generated_client.go
  pkg/azclient/publicipaddressclient/zz_generated_client.go
  pkg/azclient/publicipprefixclient/zz_generated_client.go
  pkg/azclient/registryclient/zz_generated_client.go
  pkg/azclient/routetableclient/zz_generated_client.go
  pkg/azclient/secretclient/zz_generated_client.go
  pkg/azclient/securitygroupclient/zz_generated_client.go
  pkg/azclient/snapshotclient/zz_generated_client.go
  pkg/azclient/sshpublickeyresourceclient/zz_generated_client.go
  pkg/azclient/subnetclient/zz_generated_client.go
  pkg/azclient/vaultclient/zz_generated_client.go
  pkg/azclient/virtualmachineclient/zz_generated_client.go
  pkg/azclient/virtualmachinescalesetclient/zz_generated_client.go
  pkg/azclient/virtualmachinescalesetvmclient/zz_generated_client.go
  pkg/azclient/virtualnetworkclient/zz_generated_client.go
  pkg/azclient/virtualnetworklinkclient/zz_generated_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup, ok-to-test

#6675 test: login with federated token for ACR
  tests/e2e/utils/container_registry_utils.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, release-note-none, kind/cleanup

#6673 chore: Exclude unwanted tags in e2e
  tests/e2e/network/service_annotations.go
  tests/e2e/utils/network_utils.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, release-note-none

#6693 [release-1.27] Support workload identity in e2e test
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/container_registry_utils.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/M, release-note-none, kind/cleanup

#6694 [release-1.28] Support workload identity in e2e test
  tests/e2e/utils/azure_auth.go
  tests/e2e/utils/container_registry_utils.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/M, release-note-none, kind/cleanup

#6715 chore: Migrate all e2e templates to workload identity
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-md.yaml
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-md.yaml
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml
  tests/k8s-azure/manifest/cluster-api/linux-dualstack.yaml
  tests/k8s-azure/manifest/cluster-api/linux-ipv6.yaml
  tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss-multiple-zones.yaml
  tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-local.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-oot-credential-provider.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version-oot-credential-provider.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss.yaml
Labels: approved, cncf-cla: yes, size/L, release-note-none, do-not-merge/needs-kind
