Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2024-10, with the labels that each got.

#7167 Fix checking service references from `tags` when deleting PIP
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, ok-to-test

#7231 Introduce context.Context to vmset interface
  pkg/provider/azure_instances_test.go
  pkg/provider/azure_instances_v1.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_backendpool.go
  pkg/provider/azure_loadbalancer_backendpool_test.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_mock_loadbalancer_backendpool.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_routes.go
  pkg/provider/azure_routes_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmsets_repo.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_repo_test.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#7194 fix: k8s 1.31 condition
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.31.1.tgz
  helm/repo/index.yaml
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test

#7260 [release-1.28] Fix checking service references from `tags` when deleting PIP
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, ok-to-test

#7261 [release-1.29] Fix checking service references from `tags` when deleting PIP
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, ok-to-test

#7263 [release-1.31] Fix checking service references from `tags` when deleting PIP
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, ok-to-test

#7273 doc: explain credential provider registry mirror
  content/en/topics/credential-provider.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none, ok-to-test

#7266 Chores: remove nsg/privatedns/virtualnetworklink client from code base
  pkg/azureclients/privatednsclient/azure_privatednsclient.go
  pkg/azureclients/privatednsclient/azure_privatednsclient_test.go
  pkg/azureclients/privatednsclient/interface.go
  pkg/azureclients/privatednsclient/mockprivatednsclient/doc.go
  pkg/azureclients/privatednsclient/mockprivatednsclient/interface.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
  pkg/azureclients/securitygroupclient/azure_securitygroupclient_test.go
  pkg/azureclients/securitygroupclient/doc.go
  pkg/azureclients/securitygroupclient/interface.go
  pkg/azureclients/securitygroupclient/mocksecuritygroupclient/doc.go
  pkg/azureclients/securitygroupclient/mocksecuritygroupclient/interface.go
  pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient.go
  pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient_test.go
  pkg/azureclients/virtualnetworklinksclient/doc.go
  pkg/azureclients/virtualnetworklinksclient/interface.go
  pkg/azureclients/virtualnetworklinksclient/mockvirtualnetworklinksclient/doc.go
  pkg/azureclients/virtualnetworklinksclient/mockvirtualnetworklinksclient/interface.go
  pkg/provider/azure.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#7277 Revert "Fix cloudConfigSecretName behavior"
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.31.2.tgz
  helm/repo/index.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/M, release-note-none

#7274 [release-1.30]migrate nsg client to track2 one
  go.sum
  internal/testutil/assert.go
  internal/testutil/fixture/azure_securitygroup.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_accesscontrol.go
  pkg/provider/azure_loadbalancer_accesscontrol_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_securitygroup_repo.go
  pkg/provider/azure_securitygroup_repo_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_storageaccount_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/loadbalancer/securitygroup/securitygroup.go
  pkg/provider/loadbalancer/securitygroup/securitygroup_test.go
  pkg/provider/loadbalancer/securitygroup/securityrule.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/securitygroupclient/mock_securitygroupclient/interface.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#7272 [release-1.31]migrate nsg client to track2 one
  internal/testutil/assert.go
  internal/testutil/fixture/azure_securitygroup.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_accesscontrol.go
  pkg/provider/azure_loadbalancer_accesscontrol_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_securitygroup_repo.go
  pkg/provider/azure_securitygroup_repo_test.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_standard_test.go
  pkg/provider/azure_storageaccount_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  pkg/provider/azure_wrap.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/loadbalancer/securitygroup/securitygroup.go
  pkg/provider/loadbalancer/securitygroup/securitygroup_test.go
  pkg/provider/loadbalancer/securitygroup/securityrule.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/securitygroupclient/mock_securitygroupclient/interface.go
Labels: size/XXL, kind/feature, approved, cncf-cla: yes, lgtm, release-note-none

#7278 Remove unused track1 containerservice/route/snapshot client
  pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
  pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go
  pkg/azureclients/containerserviceclient/doc.go
  pkg/azureclients/containerserviceclient/interface.go
  pkg/azureclients/containerserviceclient/mockcontainerserviceclient/doc.go
  pkg/azureclients/containerserviceclient/mockcontainerserviceclient/interface.go
  pkg/azureclients/routeclient/azure_routeclient.go
  pkg/azureclients/routeclient/azure_routeclient_test.go
  pkg/azureclients/routeclient/doc.go
  pkg/azureclients/routeclient/interface.go
  pkg/azureclients/routeclient/mockrouteclient/doc.go
  pkg/azureclients/routeclient/mockrouteclient/interface.go
  pkg/azureclients/snapshotclient/azure_snapshotclient.go
  pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
  pkg/azureclients/snapshotclient/doc.go
  pkg/azureclients/snapshotclient/interface.go
  pkg/azureclients/snapshotclient/mocksnapshotclient/doc.go
  pkg/azureclients/snapshotclient/mocksnapshotclient/interface.go
  pkg/provider/azure.go
  pkg/provider/azure_fakes.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#7300 Chores: Add ut for user agent config
  pkg/azclient/arm_conf_test.go
  pkg/azclient/factory_conf_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#7302 Update release notes for v1.27.21
  content/en/blog/releases/v1.27.21.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#7178 Refactor nsg access control for k8s event testing
  pkg/provider/azure_loadbalancer.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/loadbalancer/configuration.go
  pkg/provider/loadbalancer/configuration_test.go
  pkg/provider/loadbalancer/k8sevent.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test

#7297 Update vendor license for master
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#7299 specify cross compiler when cgo is enabled
  Dockerfile
  Makefile
  cloud-node-manager.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test, kind/testing

#7193 feat: Lock updates on azure resources when other component is doing t…
  cmd/cloud-controller-manager/app/controllermanager.go
  go.sum
  pkg/consts/consts.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_lock.go
  pkg/provider/azure_lock_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmssflex.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#7344 [release-1.28] feat: Lock updates on azure resources when other component is doing t…
  cmd/cloud-controller-manager/app/controllermanager.go
  go.mod
  go.sum
  pkg/consts/consts.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_lock.go
  pkg/provider/azure_lock_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmssflex.go
  vendor/k8s.io/utils/integer/integer.go
  vendor/k8s.io/utils/net/multi_listen.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/ptr/OWNERS
  vendor/k8s.io/utils/ptr/README.md
  vendor/k8s.io/utils/ptr/ptr.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: size/XXL, release-note, kind/feature, approved, cncf-cla: yes, lgtm

#7342 [release-1.30] feat: Lock updates on azure resources when other component is doing t…
  cmd/cloud-controller-manager/app/controllermanager.go
  go.sum
  pkg/consts/consts.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_lock.go
  pkg/provider/azure_lock_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmssflex.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#7343 [release-1.29] feat: Lock updates on azure resources when other component is doing t…
  cmd/cloud-controller-manager/app/controllermanager.go
  go.sum
  pkg/consts/consts.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_lock.go
  pkg/provider/azure_lock_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmssflex.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#7341 [release-1.31] feat: Lock updates on azure resources when other component is doing t…
  cmd/cloud-controller-manager/app/controllermanager.go
  go.sum
  pkg/consts/consts.go
  pkg/node/node.go
  pkg/node/nodearm.go
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_lock.go
  pkg/provider/azure_lock_test.go
  pkg/provider/azure_mock_vmsets.go
  pkg/provider/azure_standard.go
  pkg/provider/azure_vmsets.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmssflex.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/XL

#7373 Track2 sdk: enable cross sub support for file/blob service client
  pkg/azclient/blobservicepropertiesclient/interface.go
  pkg/azclient/factory.go
  pkg/azclient/factory_gen.go
  pkg/azclient/fileservicepropertiesclient/interface.go
  pkg/azclient/managedclusterclient/testdata/ManagedCluster.yaml
  pkg/azclient/mock_azclient/interface.go
  pkg/azclient/privatezoneclient/testdata/PrivateZone.yaml
  pkg/azclient/virtualnetworklinkclient/custom_test.go
  pkg/azclient/virtualnetworklinkclient/testdata/VirtualNetworkLink.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note-none

#7301 Track2 sdk: override default UserAgent header in sdk
  pkg/azclient/arm_conf.go
  pkg/azclient/arm_conf_test.go
  pkg/azclient/factory_conf_test.go
  pkg/azclient/policy/useragent/user_agent.go
  pkg/azclient/policy/useragent/user_agent_test.go
  pkg/azclient/policy/useragent/useragent_suite_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#7298 [release-1.31]Update vendor license for release-1.31
  LICENSES/vendor/golang.org/x/oauth2/LICENSE
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#7400 chores: skip trivy db update
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, size/XS, release-note-none, kind/testing

#7401 Update codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: approved, cncf-cla: yes, size/S, release-note-none, kind/cleanup

#7425 Chores: trigger build only when needed
  .github/workflows/codespell.yaml
  .github/workflows/dependency-review.yml
  .github/workflows/lint.yaml
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, do-not-merge/release-note-label-needed, size/S, kind/cleanup, kind/testing

#7380 Update vendor license for master
  go.sum
Labels: approved, cncf-cla: yes, size/M, release-note-none, kind/cleanup

#7429 Chores: replace docker hub registry with mcr repo
  Dockerfile
  cloud-node-manager.Dockerfile
  e2e.Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#7382 Update vendor license for release-1.28
  LICENSES/vendor/golang.org/x/crypto/LICENSE
  LICENSES/vendor/golang.org/x/exp/LICENSE
  LICENSES/vendor/golang.org/x/net/LICENSE
  LICENSES/vendor/golang.org/x/sync/LICENSE
  LICENSES/vendor/golang.org/x/sys/LICENSE
  LICENSES/vendor/golang.org/x/term/LICENSE
  LICENSES/vendor/golang.org/x/text/LICENSE
  LICENSES/vendor/golang.org/x/tools/LICENSE
  go.sum
Labels: approved, cncf-cla: yes, size/L, release-note-none, kind/cleanup

#7443 [azclients] Add method for deleting PLS private endpoint connection
  pkg/azclient/accountclient/mock_accountclient/interface.go
  pkg/azclient/availabilitysetclient/mock_availabilitysetclient/interface.go
  pkg/azclient/blobcontainerclient/mock_blobcontainerclient/interface.go
  pkg/azclient/blobservicepropertiesclient/mock_blobservicepropertiesclient/interface.go
  pkg/azclient/deploymentclient/mock_deploymentclient/interface.go
  pkg/azclient/diskclient/mock_diskclient/interface.go
  pkg/azclient/fileservicepropertiesclient/mock_fileservicepropertiesclient/interface.go
  pkg/azclient/fileshareclient/mock_fileshareclient/interface.go
  pkg/azclient/identityclient/mock_identityclient/interface.go
  pkg/azclient/interfaceclient/mock_interfaceclient/interface.go
  pkg/azclient/ipgroupclient/mock_ipgroupclient/interface.go
  pkg/azclient/loadbalancerclient/mock_loadbalancerclient/interface.go
  pkg/azclient/managedclusterclient/mock_managedclusterclient/interface.go
  pkg/azclient/mock_azclient/interface.go
  pkg/azclient/privateendpointclient/mock_privateendpointclient/interface.go
  pkg/azclient/privatelinkserviceclient/custom.go
  pkg/azclient/privatelinkserviceclient/interface.go
  pkg/azclient/privatelinkserviceclient/mock_privatelinkserviceclient/interface.go
  pkg/azclient/privatezoneclient/mock_privatezoneclient/interface.go
  pkg/azclient/providerclient/mock_providerclient/interface.go
  pkg/azclient/publicipaddressclient/mock_publicipaddressclient/interface.go
  pkg/azclient/publicipprefixclient/mock_publicipprefixclient/interface.go
  pkg/azclient/registryclient/mock_registryclient/interface.go
  pkg/azclient/resourcegroupclient/mock_resourcegroupclient/interface.go
  pkg/azclient/roleassignmentclient/mock_roleassignmentclient/interface.go
  pkg/azclient/roledefinitionclient/mock_roledefinitionclient/interface.go
  pkg/azclient/routetableclient/mock_routetableclient/interface.go
  pkg/azclient/secretclient/mock_secretclient/interface.go
  pkg/azclient/securitygroupclient/mock_securitygroupclient/interface.go
  pkg/azclient/snapshotclient/mock_snapshotclient/interface.go
  pkg/azclient/sshpublickeyresourceclient/mock_sshpublickeyresourceclient/interface.go
  pkg/azclient/subnetclient/mock_subnetclient/interface.go
  pkg/azclient/vaultclient/mock_vaultclient/interface.go
  pkg/azclient/virtualmachineclient/mock_virtualmachineclient/interface.go
  pkg/azclient/virtualmachinescalesetclient/mock_virtualmachinescalesetclient/interface.go
  pkg/azclient/virtualmachinescalesetvmclient/mock_virtualmachinescalesetvmclient/interface.go
  pkg/azclient/virtualnetworkclient/mock_virtualnetworkclient/interface.go
  pkg/azclient/virtualnetworklinkclient/mock_virtualnetworklinkclient/interface.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#7442 Migrate ZoneClient to SDK track v2
  pkg/azureclients/zoneclient/azure_zoneclient.go
  pkg/azureclients/zoneclient/azure_zoneclient_test.go
  pkg/azureclients/zoneclient/doc.go
  pkg/azureclients/zoneclient/interface.go
  pkg/azureclients/zoneclient/mockzoneclient/doc.go
  pkg/azureclients/zoneclient/mockzoneclient/interface.go
  pkg/provider/azure.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
  pkg/provider/azure_zones.go
  pkg/provider/azure_zones_test.go
  pkg/provider/zone/mock_repo.go
  pkg/provider/zone/repo.go
  pkg/provider/zone/repo_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/providerclient/mock_providerclient/interface.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XL, release-note-none, tide/merge-method-squash, ok-to-test
