Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2024-03, with the labels that each got.

#5594 chore: support service principal with cert auth for multi tenant scenario
  pkg/provider/config/azure_auth.go
  pkg/provider/config/azure_auth_test.go
  pkg/provider/config/testdata/testnopassword.pfx
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L, ok-to-test

#5612 [doc] Upgrade Go version
  content/en/blog/releases/v1.26.20.md
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, ok-to-test

#5576 test: improve autoscaling E2E to prevent unexpected scale operations
  .pipelines/run-autoscaling-e2e.yml
  .pipelines/run-autoscaling-multipool-e2e.yml
  tests/e2e/autoscaling/autoscaler.go
  tests/e2e/utils/node_utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, kind/flake, ok-to-test

#5347 Updates Makefile to allow override of $(PKG_CONFIG)
  Makefile
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#5613 Track2 sdk: support cert auth in multitenant credential
  pkg/azclient/auth.go
  pkg/azclient/auth_test.go
  pkg/azclient/recording/recorder.go
  pkg/azclient/testdata/auth.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#5629 Add group update policy
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#5619 fix: nfs file share created in storage account that has smb file share
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, size/M

#5643 Handle endpoint not being rerturned in AzureCloudConfigFromURL
  pkg/azclient/cloud.go
  pkg/azclient/cloud_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/M, release-note-none, ok-to-test

#5672 Add dependabot config for health-probe-proxy
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#5651 Bumps azclient to latest version
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/auth.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/cloud.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachineclient/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, ok-to-test

#5675 Track2 sdk: remove AddError method in trace implementaiton
  pkg/azclient/trace/go.mod
  pkg/azclient/trace/go.sum
  pkg/azclient/trace/tracing.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#5722 Track2 sdk: add release pipeline for azclient
  .github/workflows/release-azclient-trace.yml
  .github/workflows/release-azclient.yml
  .github/workflows/release-configloader.yml
  .github/workflows/update-vendor-license.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#5726 Add dependabot job for kube-health-proxy
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#5735 Fix: fetch all tags in azclient update job
  .github/workflows/release-azclient-trace.yml
  .github/workflows/release-azclient.yml
  .github/workflows/release-configloader.yml
Labels: approved, cncf-cla: yes, size/XS, release-note-none, kind/testing

#5650 feat: skip invalid LoadBalancerSourceRanges network CIDRs when provisioning nsg rules
  pkg/provider/azure_loadbalancer.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/loadbalancer/configuration.go
  pkg/provider/loadbalancer/configuration_test.go
  pkg/provider/loadbalancer/iputil/prefix.go
  pkg/provider/loadbalancer/iputil/prefix_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#5718 Add a failureDomain for multiple zone templates
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#5746 Fix:ignore azclient tags when fetch git tags
  .pipelines/ccm-image.yml
  .pipelines/cnm-image.yml
  .pipelines/scripts/run-e2e.sh
  hack/pkg-config.sh
  hack/print-workspace-status.sh
  kubetest2-aks/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#5747 fix: handle comma-separated provided IPs
  pkg/nodemanager/nodemanager.go
  pkg/nodemanager/nodemanager_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#5752 [release-1.27] feat: skip invalid LoadBalancerSourceRanges network CIDRs when provisioning nsg rules
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/loadbalancer/netip.go
  pkg/provider/loadbalancer/netip_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#5753 [release-1.26] feat: skip invalid LoadBalancerSourceRanges network CIDRs when provisioning nsg rules
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/loadbalancer/netip.go
  pkg/provider/loadbalancer/netip_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#5751 [release-1.28] feat: skip invalid LoadBalancerSourceRanges network CIDRs when provisioning nsg rules
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/loadbalancer/netip.go
  pkg/provider/loadbalancer/netip_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#5765 [release-1.27] Reorder security rules to ensure 'DenyAll' rule appears after 'Allow' rule
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XL, ok-to-test

#5790 [release-1.26] Bump to go 1.20
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#5778 Create v1.26.22.md
  content/en/blog/releases/v1.26.22.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#5652 Add timeout setting for default transport
  pkg/azclient/utils/transport.go
  pkg/azureclients/armclient/azure_armclient.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#5797 Update lint.yaml
  .github/workflows/lint.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#5805 [release-1.27] Set lint go ver with go.mod
  .github/workflows/lint.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#5804 [release-1.28] Set lint go ver with go.mod
  .github/workflows/lint.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#5806 [release-1.26] Set lint go ver with go.mod
  .github/workflows/lint.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup
