Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2024-04, with the labels that each got.

#5821 fix: get zone panic
  pkg/provider/azure_zones.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#5831 Track2 sdk:enable InsecureAllowCredentialWithHTTP by default
  pkg/azclient/utils/options.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#5832 chores: update path trigger for azclient
  .github/workflows/release-azclient.yml
  .github/workflows/release-configloader.yml
Labels: approved, cncf-cla: yes, size/S, release-note-none, kind/testing

#5815 Introduce KeyVaultCredential for SDK v2
  pkg/azclient/arm_conf.go
  pkg/azclient/armauth/auxiliary_auth_policy.go
  pkg/azclient/armauth/keyvault_credential.go
  pkg/azclient/auth.go
  pkg/azclient/auth_conf.go
  pkg/azclient/go.mod
  pkg/azclient/go.sum
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none, ok-to-test

#5824 Update Azure Credentials Provider Regex to be non-greedy
  pkg/credentialprovider/azure_credentials.go
  pkg/credentialprovider/azure_credentials_test.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test

#5863 Skip license check test for dependabot
  Makefile
Labels: approved, cncf-cla: yes, size/XS, release-note-none, kind/testing

#5885 fix: allow space separated load balancer source ranges
  pkg/provider/loadbalancer/configuration.go
  pkg/provider/loadbalancer/configuration_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#5886 Fix cleaning up stale security rules
  pkg/provider/loadbalancer/securitygroup/securitygroup.go
  pkg/provider/loadbalancer/securitygroup/securitygroup_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S, ok-to-test

#5896 Surround CAAPH values strings in quotes
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-oot-credential-provider.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version-oot-credential-provider.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#5895 [release-1.26] fix: allow space separated load balancer source ranges
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#5893 [release-1.28] fix: allow space separated load balancer source ranges
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#5894 [release-1.27] fix: allow space separated load balancer source ranges
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#5920 fix: Retry put vmss vm on preempted error
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
  pkg/consts/consts.go
  pkg/retry/azure_error.go
  pkg/retry/azure_error_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#5924 Enable TrafficDistribution feature gates in multi-zones templates
  hack/test_k8s_e2e_capz.sh
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
  tests/k8s-azure/manifest/kube-proxy/config.conf
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/testing

#5927 Use quotes for linux-vmss-ci-version template
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#5928 chore: add ARM request method and URI to logs for troubleshooting
  pkg/azureclients/armclient/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#5929 chore: expose metrics log level
  pkg/metrics/azure_metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#5949 Chores: unblock trivy job if cve is found
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#5926 [release-1.26] fix: Retry put vmss vm on preempted error
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
  pkg/consts/consts.go
  pkg/retry/azure_error.go
  pkg/retry/azure_error_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#5939 [release-1.27] chore: add ARM request method and URI to logs for troubleshooting
  go.mod
  go.sum
  pkg/azureclients/armclient/util.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#5967 [release-1.29] chore: add ARM request method and URI to logs for troubleshooting
  go.mod
  go.sum
  health-probe-proxy/go.mod
  health-probe-proxy/go.sum
  pkg/azureclients/armclient/util.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#5966 [release-1.28] fix: Retry put vmss vm on preempted error
  pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
  pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
  pkg/consts/consts.go
  pkg/retry/azure_error.go
  pkg/retry/azure_error_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#5948 Fix getVMManagementTypeByIPConfigurationID()
  pkg/provider/azure_vmss_cache.go
  pkg/provider/azure_vmssflex.go
  pkg/provider/azure_vmssflex_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#5940 [release-1.28] chore: add ARM request method and URI to logs for troubleshooting
  go.mod
  go.sum
  health-probe-proxy/go.mod
  health-probe-proxy/go.sum
  pkg/azureclients/armclient/util.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup

#5997 Remove kubetest2
  kubetest2-aks/Makefile
  kubetest2-aks/README.md
  kubetest2-aks/cluster-templates/autoscaling-e2e.json
  kubetest2-aks/cluster-templates/autoscaling-multipool.json
  kubetest2-aks/cluster-templates/autoscaling.json
  kubetest2-aks/cluster-templates/basic-lb.json
  kubetest2-aks/cluster-templates/customconfiguration-azuredisk.json
  kubetest2-aks/cluster-templates/customconfiguration-azurefile.json
  kubetest2-aks/cluster-templates/customconfiguration-cas.json
  kubetest2-aks/cluster-templates/customconfiguration-ccm.json
  kubetest2-aks/cluster-templates/customconfiguration-k8s.json
  kubetest2-aks/cluster-templates/customconfiguration.json
  kubetest2-aks/cluster-templates/slb.json
  kubetest2-aks/deployer/build.go
  kubetest2-aks/deployer/deployer.go
  kubetest2-aks/deployer/down.go
  kubetest2-aks/deployer/up.go
  kubetest2-aks/go.mod
  kubetest2-aks/go.sum
  kubetest2-aks/main.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup

#5998 Update dependabot for 1.30 release
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#6010 Update kubetest2 go.mod
  kubetest2-aks/go.mod
Labels: approved, lgtm, size/XS, release-note-none, kind/testing

#6047 Add default timeout for lb client
  pkg/provider/azure_loadbalancer_repo.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none
