Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2025-06, with the labels that each got.

#9112 fix: Set default ipfamilies to ipv4 if the field is empty
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash

#9127 fix: Retry reconcileLoadBalancer after removing PLS
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash

#9156 chore: Dependabot do not bump go version
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/cleanup, tide/merge-method-squash

#9160 [release-1.30] fix: Retry reconcileLoadBalancer after removing PLS
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash

#9159 [release-1.31] fix: Retry reconcileLoadBalancer after removing PLS
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_privatelinkservice.go
  pkg/provider/azure_privatelinkservice_test.go
  pkg/provider/azure_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash

#9162 fix: CVE-2025-22871
  health-probe-proxy/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, tide/merge-method-squash

#9178 doc: Bump the image versions in readme and examples
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
Labels: approved, cncf-cla: yes, kind/documentation, size/S, release-note-none, tide/merge-method-squash

#9193 chore: fix release pipeline
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, tide/merge-method-squash

#9195 fix: Bump hugo version to 0.147.8
  netlify.toml
Labels: approved, cncf-cla: yes, kind/documentation, size/XS, release-note-none

#9208 Skip adding Internet service tag if IP ranges allow all
  pkg/provider/azure_loadbalancer_accesscontrol_test.go
  pkg/provider/loadbalancer/accesscontrol.go
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup, tide/merge-method-squash, ok-to-test
