Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2025-05, with the labels that each got.

#8995 [release-1.29] fix: Ignore cases when comparing load balancer names
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash

#8994 [release-1.30] fix: Ignore cases when comparing load balancer names
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash

#8996 chore: Bump go modules against k/k release-1.33
  go.mod
  go.sum
  vendor/k8s.io/utils/buffer/ring_growing.go
  vendor/modules.txt
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup, tide/merge-method-squash

#9013 Track2 sdk: add list function for virtualnetworklinkclient
  pkg/azclient/accountclient/accountclient_test.go
  pkg/azclient/availabilitysetclient/availabilitysetclient_test.go
  pkg/azclient/backendaddresspoolclient/backendaddresspoolclient_test.go
  pkg/azclient/client-gen/generator/gentest_action.go
  pkg/azclient/client-gen/generator/template.go
  pkg/azclient/configloader/go.mod
  pkg/azclient/diskclient/diskclient_test.go
  pkg/azclient/go.mod
  pkg/azclient/go.sum
  pkg/azclient/interfaceclient/interfaceclient_test.go
  pkg/azclient/ipgroupclient/ipgroupclient_test.go
  pkg/azclient/loadbalancerclient/loadbalancerclient_test.go
  pkg/azclient/managedclusterclient/managedclusterclient_test.go
  pkg/azclient/privatelinkserviceclient/privatelinkserviceclient_test.go
  pkg/azclient/publicipaddressclient/publicipaddressclient_test.go
  pkg/azclient/publicipprefixclient/publicipprefixclient_test.go
  pkg/azclient/registryclient/registryclient_test.go
  pkg/azclient/routetableclient/routetableclient_test.go
  pkg/azclient/secretclient/secretclient_test.go
  pkg/azclient/securitygroupclient/securitygroupclient_test.go
  pkg/azclient/sshpublickeyresourceclient/sshpublickeyresourceclient_test.go
  pkg/azclient/subnetclient/subnetclient_test.go
  pkg/azclient/vaultclient/vaultclient_test.go
  pkg/azclient/virtualmachineclient/virtualmachineclient_test.go
  pkg/azclient/virtualmachinescalesetclient/virtualmachinescalesetclient_test.go
  pkg/azclient/virtualmachinescalesetvmclient/custom_test.go
  pkg/azclient/virtualmachinescalesetvmclient/testdata/AZURECHINACLOUD.yaml
  pkg/azclient/virtualmachinescalesetvmclient/testdata/AZURECLOUD.yaml
  pkg/azclient/virtualnetworkclient/virtualnetworkclient_test.go
  pkg/azclient/virtualnetworklinkclient/interface.go
  pkg/azclient/virtualnetworklinkclient/mock_virtualnetworklinkclient/interface.go
  pkg/azclient/virtualnetworklinkclient/testdata/AZURECHINACLOUD.yaml
  pkg/azclient/virtualnetworklinkclient/testdata/AZURECLOUD.yaml
  pkg/azclient/virtualnetworklinkclient/virtualnetworklinkclient_test.go
  pkg/azclient/virtualnetworklinkclient/zz_generated_client.go
Labels: size/XXL, kind/feature, approved, cncf-cla: yes, lgtm, release-note-none, tide/merge-method-squash

#9027 Chore: install arm toolchain before build release artifacts
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, tide/merge-method-squash, kind/testing

#9028 [release-1.33]Chore: install arm toolchains before build release artifacts
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, tide/merge-method-squash, kind/testing

#9029 Chore: add dependabot job for release-1.33 branch
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, tide/merge-method-squash, kind/testing

#9026 feat: add option to override ARM retry-after if the value is lower than the configured minimum
  pkg/azclient/arm_conf.go
  pkg/azclient/go.mod
  pkg/azclient/go.sum
  pkg/azclient/policy/retryaftermin/retryaftermin.go
  pkg/azclient/policy/retryaftermin/retryaftermin_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash

#9043 doc: Add release notes for v1.33.0, v1.32.5, v1.31.6, v1.30.12 and v1…
  content/en/blog/releases/v1.29.15.md
  content/en/blog/releases/v1.30.12.md
  content/en/blog/releases/v1.31.6.md
  content/en/blog/releases/v1.32.5.md
  content/en/blog/releases/v1.33.0.md
Labels: approved, cncf-cla: yes, kind/documentation, size/L, release-note-none

#9045 doc: Update readme and examples to use the latest images
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none, tide/merge-method-squash

#9059 Track2 sdk: replace expand with deleteoption in delete func of fileshare client
  pkg/azclient/fileshareclient/custom.go
  pkg/azclient/fileshareclient/interface.go
  pkg/azclient/fileshareclient/mock_fileshareclient/interface.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none, tide/merge-method-squash

#9076 Update Helm chart for v1.33.0 and other branches
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.33.0.tgz
  helm/repo/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, tide/merge-method-squash
