Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2025-09, with the labels that each got.

#9417 Clean backend pool node destination while reconciling security group
  pkg/provider/azure.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_accesscontrol.go
  pkg/provider/azure_loadbalancer_accesscontrol_test.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/securitygroup/securitygroup.go
  pkg/provider/securitygroup/securitygroup_test.go
  pkg/provider/securitygroup/securityrule.go
  pkg/provider/securitygroup/securityrule_test.go
Labels: size/XXL, release-note, approved, kind/bug, cncf-cla: yes, lgtm, tide/merge-method-squash, ok-to-test

#9416 [release-1.31] chore: bump Go version to 1.24.6/1.23.12 for CVEs
  Dockerfile
  cloud-node-manager.Dockerfile
  e2e.Dockerfile
  go.mod
  health-probe-proxy/go.mod
Labels: release-note, approved, cncf-cla: yes, lgtm, size/S, kind/cleanup, tide/merge-method-squash

#9413 [release-1.33] chore: bump Go version to 1.24.6 for CVEs
  Dockerfile
  cloud-node-manager.Dockerfile
  e2e.Dockerfile
  go.mod
  health-probe-proxy/go.mod
  kubetest2-aks/go.mod
  tests/go.mod
Labels: release-note, approved, cncf-cla: yes, lgtm, size/S, kind/cleanup, tide/merge-method-squash

#9410 [release-1.32] chore: bump distroless base image for CVEs
  Dockerfile
  cloud-node-manager.Dockerfile
  health-probe-proxy/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, tide/merge-method-squash

#9418 fix: China cloud endpoints
  go.mod
  go.sum
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/local/server.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/ops/authority/authority.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/resolvers.go
  vendor/modules.txt
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash

#9423 [release-1.34] Clean backend pool node destination while reconciling security group
  pkg/provider/azure.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_accesscontrol.go
  pkg/provider/azure_loadbalancer_accesscontrol_test.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/securitygroup/securitygroup.go
  pkg/provider/securitygroup/securitygroup_test.go
  pkg/provider/securitygroup/securityrule.go
  pkg/provider/securitygroup/securityrule_test.go
Labels: size/XXL, release-note, approved, kind/bug, cncf-cla: yes, lgtm, tide/merge-method-squash, ok-to-test

#9426 [release-1.32] fix: China cloud endpoints
  go.mod
  go.sum
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/local/server.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/ops/authority/authority.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/resolvers.go
  vendor/modules.txt
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash

#9421 [release-1.32] Clean backend pool node destination while reconciling security group
  pkg/provider/azure.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_accesscontrol.go
  pkg/provider/azure_loadbalancer_accesscontrol_test.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/securitygroup/securitygroup.go
  pkg/provider/securitygroup/securitygroup_test.go
  pkg/provider/securitygroup/securityrule.go
  pkg/provider/securitygroup/securityrule_test.go
Labels: size/XXL, release-note, approved, kind/bug, cncf-cla: yes, lgtm, tide/merge-method-squash, ok-to-test

#9420 [release-1.31] Clean backend pool node destination while reconciling security group
  pkg/provider/azure.go
  pkg/provider/azure_fakes.go
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_accesscontrol.go
  pkg/provider/azure_loadbalancer_accesscontrol_test.go
  pkg/provider/loadbalancer/accesscontrol.go
  pkg/provider/loadbalancer/accesscontrol_test.go
  pkg/provider/securitygroup/securitygroup.go
  pkg/provider/securitygroup/securitygroup_test.go
  pkg/provider/securitygroup/securityrule.go
  pkg/provider/securitygroup/securityrule_test.go
Labels: size/XXL, release-note, approved, kind/bug, cncf-cla: yes, lgtm, tide/merge-method-squash, ok-to-test

#9450 chore: Update Helm chart for v1.34.0
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.34.1.tgz
  helm/repo/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup, tide/merge-method-squash

#9493 feat: add IsSmbOAuthEnabled parameter in storage account creation
  pkg/provider/storage/azure_storageaccount.go
  pkg/provider/storage/azure_storageaccount_test.go
Labels: kind/feature, approved, cncf-cla: yes, size/M, release-note-none, tide/merge-method-squash
