Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2025-03, with the labels that each got.

#8419 fix: Remove managed pip if switched to another pip in a different res…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_publicip_repo.go
  pkg/provider/azure_test.go
  tests/e2e/network/ensureloadbalancer.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#8500 [release-1.29] fix: Remove all routes that have the node name as prefix (#8427)
  pkg/provider/azure_routes.go
  pkg/provider/azure_routes_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#8504 fix: incorrect cloud provider setting in sovereign cloud
  pkg/provider/azure.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#8517 test: pin az cli to fix acr cache create issue
  Makefile
  hack/ensure-azcli.sh
Labels: approved, cncf-cla: yes, size/M, release-note-none, kind/testing

#8515 [release-1.32] fix: incorrect cloud provider setting in sovereign cloud
  pkg/provider/azure.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, size/XS

#8518 track2 sdk:add support for non-public cloud
  pkg/azclient/.golangci.yml
  pkg/azclient/Makefile
  pkg/azclient/accountclient/interface.go
  pkg/azclient/accountclient/zz_generated_client.go
  pkg/azclient/blobcontainerclient/interface.go
  pkg/azclient/blobcontainerclient/zz_generated_client.go
  pkg/azclient/blobservicepropertiesclient/interface.go
  pkg/azclient/blobservicepropertiesclient/zz_generated_client.go
  pkg/azclient/client-gen/generator/clientfactory.go
  pkg/azclient/client-gen/generator/gentest_action.go
  pkg/azclient/client-gen/generator/template.go
  pkg/azclient/cloud.go
  pkg/azclient/cloud_test.go
  pkg/azclient/factory_gen.go
  pkg/azclient/fileservicepropertiesclient/interface.go
  pkg/azclient/fileservicepropertiesclient/zz_generated_client.go
  pkg/azclient/fileshareclient/interface.go
  pkg/azclient/fileshareclient/zz_generated_client.go
  pkg/azclient/ipgroupclient/interface.go
  pkg/azclient/ipgroupclient/zz_generated_client.go
  pkg/azclient/registryclient/interface.go
  pkg/azclient/registryclient/zz_generated_client.go
  pkg/azclient/utils/cloud.go
  pkg/azclient/utils/cloud_test.go
  pkg/azclient/utils/utils_suite_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L

#8524 [release-1.30] fix: Remove managed pip if switched to another pip in a different res…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_publicip_repo.go
  pkg/provider/azure_test.go
  tests/e2e/network/ensureloadbalancer.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#8530 [release-1.30] fix: Remove managed pip if switched to another pip in a different res…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_publicip_repo.go
  pkg/provider/azure_test.go
  tests/e2e/network/ensureloadbalancer.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#8519 [release-1.31] fix: Remove managed pip if switched to another pip in a different res…
  pkg/provider/azure_loadbalancer.go
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_publicip_repo.go
  pkg/provider/azure_test.go
  tests/e2e/network/ensureloadbalancer.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#8534 Track2 sdk: add default cloud config
  pkg/azclient/cloud.go
  pkg/azclient/cloud_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#8499 [release-1.30] fix: Remove all routes that have the node name as prefix (#8427)
  pkg/provider/azure_routes.go
  pkg/provider/azure_routes_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#8560 fix: account match algorithm when source account name is provided
  pkg/provider/storage/azure_storageaccount.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, size/S

#8565 doc: Update image versions in readme and examples
  README.md
  examples/out-of-tree/cloud-controller-manager.yaml
  examples/out-of-tree/cloud-node-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#8564 doc: Add release notes for v1.29.13, v1.30.10, v1.31.4 and v1.32.3
  content/en/blog/releases/v1.29.13.md
  content/en/blog/releases/v1.30.10.md
  content/en/blog/releases/v1.31.4.md
  content/en/blog/releases/v1.32.3.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/L, release-note-none

#8570 doc: Enrich doc for reserved tag keys
  content/en/topics/tagging-resources.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/XS, release-note-none

#8531 chore: Fix linting issues
  tests/e2e/network/ensureloadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup

#8588 Potential fix for code scanning alert no. 195: Use of a weak cryptographic key
  pkg/azclient/managedclusterclient/custom_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#8587 [flaky test] Generate non-overlapping and non-mergable CIDRs with best effort
  internal/testutil/fixture/fixture.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test, kind/testing

#8623 fix: reduce get disk calls in disk attach/detach on VMSS
  pkg/provider/azure_controller_vmss.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, size/XS

#8624 [release-1.31] fix: reduce get disk calls in disk attach/detach on VMSS
  pkg/provider/azure_controller_vmss.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, size/XS

#8625 [release-1.30] fix: reduce get disk calls in disk attach/detach on VMSS
  pkg/provider/azure_controller_vmss.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, size/XS

#8594 Merge OTEL metrics with legacy registerer
  cmd/cloud-controller-manager/app/controllermanager.go
  pkg/trace/provider.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test

#8635 [release-1.32] Generate non-overlapping and non-mergable CIDRs with best effort (#8587)
  internal/testutil/fixture/fixture.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test, kind/testing

#8637 [release-1.30] Merge OTEL metrics with legacy registerer (#8594)
  cmd/cloud-controller-manager/app/controllermanager.go
  pkg/trace/provider.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test

#8643 cleanup: add csi related track2 metrics
  pkg/azclient/accountclient/custom.go
  pkg/azclient/blobcontainerclient/custom.go
  pkg/azclient/blobservicepropertiesclient/custom.go
  pkg/azclient/fileservicepropertiesclient/custom.go
  pkg/azclient/fileshareclient/custom.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L, release-note-none

#8638 [release-1.31] Merge OTEL metrics with legacy registerer (#8594)
  cmd/cloud-controller-manager/app/controllermanager.go
  pkg/trace/provider.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test

#8640 [release-1.29] fix empty string on DAP (#7854)
  pkg/provider/loadbalancer/securitygroup/securityrule.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS, ok-to-test

#8639 [release-1.32] Merge OTEL metrics with legacy registerer (#8594)
  cmd/cloud-controller-manager/app/controllermanager.go
  pkg/trace/provider.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test

#8647 fix(credential-provider): check empty mirror mapping and add debugging info
  cmd/acr-credential-provider/main.go
  pkg/credentialprovider/azure_acr_helper.go
  pkg/credentialprovider/azure_credentials.go
  pkg/credentialprovider/azure_credentials_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M

#8633 [release-1.30] Generate non-overlapping and non-mergable CIDRs with best effort (#8587)
  internal/testutil/fixture/fixture.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test, kind/testing

#8596 [azclient] Refactor AuthProvider multi-tenant token credential
  pkg/azclient/auth.go
  pkg/azclient/auth_fake_test.go
  pkg/azclient/auth_func.go
  pkg/azclient/auth_func_test.go
  pkg/azclient/auth_option.go
  pkg/azclient/auth_option_test.go
  pkg/azclient/auth_test.go
  pkg/azclient/go.mod
  pkg/azclient/go.sum
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note-none, kind/cleanup, ok-to-test

#8622 Bump Helm chart for latest patch versions
  helm/cloud-provider-azure/Chart.yaml
  helm/cloud-provider-azure/templates/cloud-provider-azure.yaml
  helm/repo/cloud-provider-azure-1.32.3.tgz
  helm/repo/index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#8715 cleanup: add authProvider in AccountRepo struct
  pkg/provider/storage/azure_storageaccount.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#8729 Revert "build(deps): bump the all group with 2 updates"
  .github/workflows/codeql-analysis.yml
  .github/workflows/codeql-azclient.yml
  .github/workflows/lint-azclient.yaml
  .github/workflows/lint.yaml
  .github/workflows/scorecards.yml
  .github/workflows/trivy.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, release-note-none

#8696 [release-1.32] fix(credential-provider): use acr audience token for ACR authentication
  go.mod
  go.sum
  pkg/credentialprovider/azure_credentials.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/LICENSE.txt
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/TROUBLESHOOTING.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/authentication_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/authentication_custom_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/authentication_policy.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/autorest.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/blob_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/blob_custom_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/build.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/cloud_config.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/custom_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/custom_constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/digest_helper.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/models.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/models_serde.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/options.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/response_types.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/test-resources-post.ps1
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/test-resources.bicep
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/time_rfc3339.go
  vendor/modules.txt
Labels: size/XXL, release-note, approved, kind/bug, cncf-cla: yes, lgtm

#8697 [release-1.30] fix(credential-provider): use acr audience token for ACR authentication
  go.mod
  go.sum
  pkg/credentialprovider/azure_credentials.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/LICENSE.txt
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/TROUBLESHOOTING.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/authentication_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/authentication_custom_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/authentication_policy.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/autorest.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/blob_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/blob_custom_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/build.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/cloud_config.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/custom_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/custom_constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/digest_helper.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/models.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/models_serde.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/options.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/response_types.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/test-resources-post.ps1
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/test-resources.bicep
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/time_rfc3339.go
  vendor/modules.txt
Labels: size/XXL, release-note, approved, kind/bug, cncf-cla: yes, lgtm

#8698 [release-1.31] fix(credential-provider): use acr audience token for ACR authentication
  go.mod
  go.sum
  pkg/credentialprovider/azure_credentials.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/LICENSE.txt
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/TROUBLESHOOTING.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/authentication_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/authentication_custom_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/authentication_policy.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/autorest.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/blob_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/blob_custom_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/build.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/cloud_config.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/custom_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/custom_constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/digest_helper.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/models.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/models_serde.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/options.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/response_types.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/test-resources-post.ps1
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/test-resources.bicep
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/time_rfc3339.go
  vendor/modules.txt
Labels: size/XXL, release-note, approved, kind/bug, cncf-cla: yes, lgtm

#8699 [release-1.29] fix(credential-provider): use acr audience token for ACR authentication
  go.mod
  go.sum
  pkg/credentialprovider/azure_credentials.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/LICENSE.txt
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/TROUBLESHOOTING.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/assets.json
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/authentication_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/authentication_custom_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/authentication_policy.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/autorest.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/blob_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/blob_custom_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/build.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/cloud_config.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/custom_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/custom_constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/digest_helper.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/models.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/models_serde.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/options.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/response_types.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/test-resources-post.ps1
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/test-resources.bicep
  vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/time_rfc3339.go
  vendor/modules.txt
Labels: size/XXL, release-note, approved, kind/bug, cncf-cla: yes, lgtm

#8733 Fix linter version
  .github/workflows/lint.yaml
Labels: cncf-cla: yes, size/XS, release-note-none, kind/cleanup, ok-to-test

#8728 Upgrade azclient and set compute and network ARM client
  go.mod
  go.sum
  pkg/provider/azure.go
  pkg/provider/azure_test.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared/constants.go
  vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/ops/accesstokens/accesstokens.go
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/cmp.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortanyfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/k8s.io/utils/buffer/ring_growing.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/Makefile
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/auth.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/auth_func.go
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/auth_option.go
Labels: size/XXL, release-note, approved, kind/bug, cncf-cla: yes, lgtm, ok-to-test

#8648 fix: Skip ensuring host in pool if the vm is not found
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#8732 fix: Remove the shared slb health probe after the last cluster servic…
  pkg/provider/azure_loadbalancer_healthprobe.go
  pkg/provider/azure_loadbalancer_healthprobe_test.go
  tests/e2e/network/sharedhealthprobe.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#8634 [release-1.31] Generate non-overlapping and non-mergable CIDRs with best effort (#8587)
  internal/testutil/fixture/fixture.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, ok-to-test, kind/testing

#8641 [release-1.30] fix empty string on DAP (#7854)
  pkg/provider/securitygroup/securityrule.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS, ok-to-test

#8763 [release-1.29] fix: Skip ensuring host in pool if the vm is not found
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#8768 Track2 sdk: pin golangci-lint-action to v6
  .github/workflows/lint-azclient.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/testing

#8758 [release-1.31] fix: Remove the shared slb health probe after the last cluster servic…
  pkg/provider/azure_loadbalancer_healthprobe.go
  pkg/provider/azure_loadbalancer_healthprobe_test.go
  tests/e2e/network/sharedhealthprobe.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#8761 [release-1.31] fix: Skip ensuring host in pool if the vm is not found
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/S

#8759 [release-1.30] fix: Remove the shared slb health probe after the last cluster servic…
  pkg/provider/azure_loadbalancer_healthprobe.go
  pkg/provider/azure_loadbalancer_healthprobe_test.go
  tests/e2e/network/sharedhealthprobe.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L
