Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2025-08, with the labels that each got.

#9308 chore: bump lbclient to latest API version for AzureStackCloud
  pkg/azclient/loadbalancerclient/interface.go
  pkg/azclient/loadbalancerclient/zz_generated_client.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS, tide/merge-method-squash, ok-to-test

#9309 test: Delete removed feature gates from CAPZ templates
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml
  tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-local.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
  tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
Labels: kind/bug, cncf-cla: yes, kind/failing-test, size/S, release-note-none, tide/merge-method-squash

#9339 chore: add option to list vmss vms without instance view
  pkg/provider/azure_vmsets_repo.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/config/azure_cache.go
Labels: size/XXL, release-note, approved, kind/bug, cncf-cla: yes, lgtm, tide/merge-method-squash

#9379 docs: document required permissions in GitHub Actions workflows
  .github/workflows/cleanupcache.yaml
  .github/workflows/lint-azclient.yaml
  .github/workflows/lint.yaml
  .github/workflows/release-azclient-trace.yml
  .github/workflows/release-azclient.yml
  .github/workflows/release-cache.yml
  .github/workflows/release-configloader.yml
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/cleanup, tide/merge-method-squash

#9380 chore: bump Go version to 1.24.6 across all modules and Docker builds
  Dockerfile
  cloud-node-manager.Dockerfile
  e2e.Dockerfile
  go.mod
  health-probe-proxy/go.mod
  kubetest2-aks/go.mod
  pkg/azclient/cache/go.mod
  pkg/azclient/client-gen/go.mod
  pkg/azclient/configloader/go.mod
  pkg/azclient/go.mod
  pkg/azclient/go.sum
  pkg/azclient/trace/go.mod
  tests/go.mod
Labels: release-note, approved, cncf-cla: yes, lgtm, size/M, kind/cleanup, tide/merge-method-squash

#9382 chore: bump distroless base image for CVEs
  Dockerfile
  cloud-node-manager.Dockerfile
  health-probe-proxy/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup, tide/merge-method-squash

#9270 Support node filtering feature
  cmd/cloud-controller-manager/app/config/config.go
  cmd/cloud-controller-manager/app/controllermanager.go
  cmd/cloud-controller-manager/app/options/options.go
  cmd/cloud-controller-manager/app/options/options_test.go
  examples/node-filtering-example.md
Labels: release-note, kind/feature, approved, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash, ok-to-test
