Repository kubernetes-sigs/cloud-provider-azure, pull requests merged in 2025-01, with the labels that each got.

#7776 Prevent panic when informer receives cache.DeletedFinalStateUnknown
  pkg/provider/azure_local_services.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none

#7960 Add 3, modify 1 annotation for Azure load balancer doc
  content/en/topics/loadbalancer.md
Labels: needs-ok-to-test, approved, cncf-cla: yes, lgtm, kind/documentation, size/S, release-note-none

#7982 Track2 sdk: expose get option in fileshareclient
  pkg/azclient/fileshareclient/custom.go
  pkg/azclient/fileshareclient/custom_test.go
  pkg/azclient/fileshareclient/fileshareclient_test.go
  pkg/azclient/fileshareclient/interface.go
  pkg/azclient/fileshareclient/mock_fileshareclient/interface.go
  pkg/azclient/fileshareclient/zz_generated_client.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#7987 Track2 sdk:add DisableAzureStackCloud to override arm endpoint when cluster is n…
  pkg/azclient/arm_conf.go
  pkg/azclient/client-gen/generator/clientfactory.go
  pkg/azclient/factory_gen.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/M, release-note-none

#8006 Chores:ignore mock files in coverage report
  .github/workflows/codeql-analysis.yml
Labels: approved, cncf-cla: yes, size/XS, release-note-none, kind/cleanup

#8002 Chores:move DisableAzureStackCloud to azclient package
  pkg/provider/config/azure.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#8009 Chores:ignore mock file in coverage test
  .github/workflows/codeql-analysis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note-none, kind/cleanup

#8003 Update vendor license for master
  LICENSES/vendor/github.com/Azure/azure-kusto-go/azkustodata/LICENSE
  LICENSES/vendor/github.com/Azure/azure-kusto-go/azkustoingest/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/containers/azcontainerregistry/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/internal/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/authorization/armauthorization/v2/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v6/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerregistry/armcontainerregistry/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v6/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/keyvault/armkeyvault/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/msi/armmsi/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v6/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/privatedns/armprivatedns/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/storage/armstorage/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/LICENSE
  LICENSES/vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azqueue/LICENSE
  LICENSES/vendor/github.com/Azure/go-autorest/LICENSE
  LICENSES/vendor/github.com/Azure/go-autorest/autorest/LICENSE
  LICENSES/vendor/github.com/Azure/go-autorest/autorest/adal/LICENSE
  LICENSES/vendor/github.com/Azure/go-autorest/autorest/date/LICENSE
  LICENSES/vendor/github.com/Azure/go-autorest/logger/LICENSE
  LICENSES/vendor/github.com/Azure/go-autorest/tracing/LICENSE
  LICENSES/vendor/github.com/go-task/slim-sprig/v3/LICENSE
  LICENSES/vendor/github.com/gofrs/uuid/LICENSE
  LICENSES/vendor/github.com/golang-jwt/jwt/v4/LICENSE
  LICENSES/vendor/github.com/google/pprof/LICENSE
  LICENSES/vendor/github.com/onsi/ginkgo/v2/LICENSE
  LICENSES/vendor/github.com/onsi/gomega/LICENSE
  LICENSES/vendor/github.com/shopspring/decimal/LICENSE
  LICENSES/vendor/golang.org/x/tools/LICENSE
  go.sum
Labels: size/XXL, approved, cncf-cla: yes, release-note-none, kind/cleanup

#8016 Chores:fetch acutal commit id when generate release note
  hack/generate-release-note.sh
Labels: approved, cncf-cla: yes, size/XS, release-note-none, kind/cleanup

#8021 Chores:Remove pr submission due to lack of permission.
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note-none, kind/testing

#8020 Update release notes for v1.32.0
  content/en/blog/releases/v1.32.0.md
Labels: approved, cncf-cla: yes, lgtm, kind/documentation, size/L, release-note-none

#8035 Chore: set batch size to great or equal to 1
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_test.go
  pkg/provider/config/azure.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#8039 track2 sdk: add etag support for compute client
  pkg/azclient/virtualmachineclient/interface.go
  pkg/azclient/virtualmachineclient/testdata/VirtualMachine.yaml
  pkg/azclient/virtualmachineclient/virtualmachineclient_test.go
  pkg/azclient/virtualmachineclient/zz_generated_client.go
  pkg/azclient/virtualmachinescalesetclient/interface.go
  pkg/azclient/virtualmachinescalesetclient/testdata/VirtualMachineScaleSet.yaml
  pkg/azclient/virtualmachinescalesetclient/virtualmachinescalesetclient_test.go
  pkg/azclient/virtualmachinescalesetclient/zz_generated_client.go
  pkg/azclient/virtualmachinescalesetvmclient/custom_test.go
  pkg/azclient/virtualmachinescalesetvmclient/interface.go
  pkg/azclient/virtualmachinescalesetvmclient/testdata/VirtualMachineScaleSetVM.yaml
  pkg/azclient/virtualmachinescalesetvmclient/zz_generated_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XL, release-note-none, kind/cleanup

#8083 Update License files only when it is changed.
  .github/workflows/update-vendor-license.yml
Labels: approved, cncf-cla: yes, size/XS, release-note-none, kind/testing

#8034 doc: Add design doc for blb migration
  content/en/development/design-docs/blb-migration.md
Labels: approved, cncf-cla: yes, kind/documentation, size/M, release-note-none

#8119 [relase-1.30] Fix: Preserve Whitespace for Tag Values Resembling "null" to Prevent ARM Assignment Errors
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  tests/e2e/network/service_annotations.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/L

#8116 Track2 sdk: remove unused code
  vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachinescalesetvmclient/custom.go
Labels: approved, cncf-cla: yes, lgtm, size/M, release-note-none, kind/cleanup

#8130 Chores: add release-1.28 release-1.29 to supported list.
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/L, release-note-none, kind/testing

#8129 [release-1.30] fix: AzureStack env var setting issue
  pkg/provider/azure.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/XS

#8115 Fix : Enable system tag support prefix match
  pkg/provider/azure_utils.go
  pkg/provider/azure_utils_test.go
  pkg/provider/config/azure.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, lgtm, size/M, ok-to-test

#8120 Chores: update test deps before run e2e test
  hack/test-ccm-e2e.sh
Labels: approved, cncf-cla: yes, size/XS, release-note-none, kind/testing

#8152 [release-1.30] feat: always match source account in restore and volume clone scenarios
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, kind/feature, approved, cncf-cla: yes, size/M

#8153 [release-1.30] fix: VirtualNetworkRule match issue during account search
  pkg/provider/azure_storageaccount.go
  pkg/provider/azure_storageaccount_test.go
Labels: release-note, approved, kind/bug, cncf-cla: yes, size/L

#8106 fix: add Etag field to request body to let Etag work
  pkg/provider/azure_loadbalancer_test.go
  pkg/provider/azure_vmss.go
  pkg/provider/azure_vmss_repo.go
  pkg/provider/virtualmachine/virtualmachine.go
Labels: approved, kind/bug, cncf-cla: yes, lgtm, size/S, release-note-none, ok-to-test
